### ISSUE TITLE
Support 

### ISSUE THREAD

**Issue by SusanthCom** [krisk/Fuse#101]
Hi @krisk,

Support Request,

Please up vote or comment there https://github.com/madrobby/microjs.com/pull/859 to get approved for an entry at http://microjs.com

Thanks

Susanth K

**Comment by krisk** [comment]
@SusanthCom thanks, upvoted 😄

**Comment by SusanthCom** [comment]
Fuse is already in http://javascripting.com/ 
http://www.javascripting.com/view/fuse

😄
