### ISSUE TITLE
What is indices?

### ISSUE THREAD

**Issue by Kreozot** [krisk/Fuse#104]
From the tests:
```javascript
    'When searching for the term "wor"': {
      topic: function (fuse) {
        var result = fuse.search('wor')
        return result
      },
      'we get a a non empty list': function (result) {
        assert.isTrue(!!result.length)
      },
      'whose indices are found': function (result) {
        var matches = result[0].matches
        var a = matches[0].indices[0]
        var b = matches[0].indices[1]
        assert.deepEqual(a, [4, 4])
        assert.deepEqual(b, [6, 8])
      },
    }
```

Why this `assert.deepEqual(a, [4, 4])`? What is first and second number in this case?
When can I find documentation about indices? Only one mention I've found is `indices: [start, length]` on demo page.

Thank  you.

**Comment by krisk** [comment]
By setting the option `include: ["matches"]`

> Whether the matches should be included in the result set. When true, each record in the result set will include the **indices** of the matched characters: `indices: [start, length]` . These can consequently be used for highlighting purposes.

Admittedly, it's not clear in the documentation. I will add a section to explain it.
