### ISSUE TITLE
clarify limitations of array length

### ISSUE THREAD

**Issue by markentingh** [krisk/Fuse#105]
How many objects could I have in my array potentially? How large would the array have to be before the fussy search starts to experience unacceptable (3+ seconds) lag?

**Comment by pezzell** [comment]
Any clarification on this?

**Comment by james2doyle** [comment]
It would be nice to see a table of different info on this. I'm sure the results would be different based on the number of objects in the array, as well as the number of properties being searched.

**Comment by nicholaswmin** [comment]
That should be totally dependent on the speed of your CPU.
