### ISSUE TITLE
Add '*' setting for keys, to search all keys.

### ISSUE THREAD

**Issue by CupOfTea696** [krisk/Fuse#110]
It'd be cool if the `keys` setting could be set to `'*'` to search all keys. 

Example:

``` js
var options = {
  shouldSort: true,
  threshold: 0.6,
  location: 0,
  distance: 100,
  maxPatternLength: 32,
  keys: '*'
};
var fuse = new Fuse(list, options); // "list" is the item array
var result = fuse.search("red");
```

Result: 

``` json
[
  {
    "title": "Backwards, Red Dwarf",
    "author": {
      "firstName": "Rob",
      "lastName": "Grant"
    }
  },
  {
    "title": "HTML5",
    "author": {
      "firstName": "Remy",
      "lastName": "Sharp"
    }
  },
  {
    "title": "The Book of Lies",
    "author": {
      "firstName": "Brad",
      "lastName": "Meltzer"
    }
  },
  {
    "title": "Lamb",
    "author": {
      "firstName": "Christopher",
      "lastName": "Moore"
    }
  },
  {
    "title": "Fool",
    "author": {
      "firstName": "Christopher",
      "lastName": "Moore"
    }
  },
  {
    "title": "The Preservationist",
    "author": {
      "firstName": "David",
      "lastName": "Maine"
    }
  }
]
```

**Comment by krisk** [comment]
A few questions come up:

1. What happens if there's an actual key labeled "*" ?

  ```js
  {
    "title": "hello",
    "*": "world"
  }
  ```

  Perhaps, instead of using "*", it could be "If the key option is empty, then search all keys".

2. How much nesting should Fuse really handle? Note that Nested array would also have to be taken into consideration. Doing this implicitly isn't straightforward when you don't know how many levels of nesting Fuse should handle. This is partly the reason as to why `keys` is explicit 😄

**Comment by CupOfTea696** [comment]
1. You could add an escape to allow for that, defining keys as `"\*"`. 
2. A max depth parameter could be added.

**Comment by fimius23** [comment]
I vote for the logic where "If the key option is empty, then search all keys". I think it's really on the developer using the logic to worry about the max depth. They can always write code to map() their array to something sane before they run the fuzzy search.

**Comment by Jonarod** [comment]
I'd love to see this feature as I am facing this problem. In fact, here is my array:

```
[
  "1": "orange",
  "2": "red",
  "3": "purple",
  "4": "yellow",
  "5": "blue",
  "6": "brown",
  //...
  "4800": "whatever",
]
```

So I cannot provide fuse a specific key :/

**Comment by ooker777** [comment]
The issue was opened in 2016. It's 2024 now. The issue is literally one of the first issues (it's number is #110). The author probably has abandoned the project.
