### ISSUE TITLE
Using with Angular

### ISSUE THREAD

**Issue by FilmCoder** [krisk/Fuse#118]
Is fuse recommended for use with the Angular 1.x framework?

Is there a function which allows you to compare singular items at a time?  For example,
compareSingleItem(searchString, targetString) ---> returns True if strings approximately match, False otherwise

If so, it would be easy to incorporate that into an Angular filter.

Thanks!

**Comment by krisk** [comment]
This question would be better for [StackOverflow](https://stackoverflow.com/questions/ask?tags=fuse.js) 😄 

Nonetheless, Fuse can be used with/by any JS framework, as it is simply pure JavaScript. To do what you're suggesting, you can consider the following:

```javascript
function compare(searchString, targetString) {
  // Initialize Fuse with an array of a single string, which
  // would `targetString`
  var fuse = new Fuse([targetString])
  var result = fuse.search(searchString)
  // If the result set is of length 1, then the search string has been found
  // in the target string, otherwise result is empty, thus no match is found
  return result.length === 1
}
```

You can then wrap the above function in an Angular service, or even a filter.

**Comment by mcblum** [comment]
I followed this exact code, but I'm getting a maximum stack size exceeded. Any idea what might be causing that?
