### ISSUE TITLE
index.d.ts not in npm

### ISSUE THREAD

**Issue by fsskeach** [krisk/Fuse#123]
We pulled fuse.js via using 'npm install fuse.js'. Version 2.5.0 came down, but the index.d.ts update from two weeks ago is not there. Any thought on when we might be able to get this change from npm?

**Comment by lengtche** [comment]
I tried manually adding `index.d.ts` from `master`, but I still get compilation errors.

In the meantime I've resorted to using `declare var Fuse: any;`. You won't get intellisense, but it'll at least compile without errors.

**Comment by krisk** [comment]
Will be pushing a new version very soon.

**Comment by krisk** [comment]
Fixed.
