### ISSUE TITLE
Typings error with noImplicitAny

### ISSUE THREAD

**Issue by fasterthanlime** [krisk/Fuse#125]
With the current typings file, the typescript compiler chokes with the following:

```
node_modules/fuse.js/index.d.ts(32,15): error TS7005: Variable 'Fuse' implicitly has an 'any' type.
```

A quick workaround would be to change `declare const Fuse` to `declare const Fuse: any`, although I'm sure recent versions of TypeScript have a much better way of doing that (that's for the exported global, right?)

**Comment by lengtche** [comment]
You probably want to exclude directory `node_modules` in your TypeScript configuration.

**Comment by fasterthanlime** [comment]
> You probably want to exclude directory node_modules in your TypeScript configuration.

I'm not 100% clear on that, but wouldn't that defeat the purpose of having typings as part of node modules in the first place?

**Comment by fasterthanlime** [comment]
Update; we're already ignoring `node_modules` in tsconfig.

It looks like recent version of fuse conflicts with [our own typings](https://github.com/itchio/itch/blob/master/typings/fuse.js.d.ts):

```
node_modules/fuse.js/index.d.ts(32,15): error TS7005: Variable 'Fuse' implicitly has an 'any' type.
typings/fuse.js.d.ts(29,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

but removing our own typing isn't the solution either:

```
appsrc/components/collections.tsx(23,9): error TS2304: Cannot find name 'Fuse'.
appsrc/components/collections.tsx(27,17): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
appsrc/components/game-grid.tsx(36,9): error TS2304: Cannot find name 'Fuse'.
appsrc/components/game-grid.tsx(43,17): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
appsrc/components/game-grid.tsx(72,22): error TS2339: Property 'item' does not exist on type '{}'.
appsrc/components/game-grid.tsx(73,29): error TS2339: Property 'score' does not exist on type '{}'.
appsrc/components/hub-search-results.tsx(139,9): error TS2304: Cannot find name 'Fuse'.
appsrc/components/hub-search-results.tsx(143,17): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
appsrc/components/hub-search-results.tsx(226,29): error TS2339: Property 'item' does not exist on type '{}'.
node_modules/fuse.js/index.d.ts(32,15): error TS7005: Variable 'Fuse' implicitly has an 'any' type.
```

I guess we'll just pin to an older Fuse version for the time being!

**Comment by krisk** [comment]
Well, that's less than ideal. Honestly, it’s great to have compile errors available to you

**Comment by krisk** [comment]
Well, that's less than ideal. I plan to re-work the structure.

**Comment by aluanhaddad** [comment]
This related to this https://github.com/krisk/Fuse/pull/124 and this https://github.com/krisk/Fuse/pull/129

Put bluntly, the declaration file `index.d.ts` is completely wrong.
