### ISSUE TITLE
Support ImmutableJS

### ISSUE THREAD

**Issue by andrewmclagan** [krisk/Fuse#127]
Functional programming styles, React, Redux and more importantly ImmutableJS have become some of the most used paradigms and libraries in the JS eco-system.

Is there any roadmap to have a immutableJS friendly version of this package?

**Comment by jdmunro** [comment]
Looks like this could be implemented easily with a custom ```getFn```.

**Comment by andrewmclagan** [comment]
Plus one

**Comment by lukaswelinder** [comment]
From the README:
```javascript
/*
@param obj The object being searched
@param path The path to the target property
*/

// example using an object with a `getter` method
getFn: function (obj, path) {
  return obj.get(path);
}
```

**Comment by krisk** [comment]
There's currently no roadmap for `immutableJS`, as Fuse.js is meant to be pure - requiring **no** dependencies and making **no** assumptions 😄 . Perhaps this can change in the future if I'm given a compelling argument? Nonetheless, you can, as the comments above suggest, use the `getFn` for your custom accessor.
