### ISSUE TITLE
Token Seperation Issue

### ISSUE THREAD

**Issue by wimoMisterX** [krisk/Fuse#131]
I have discovered an issue when `tokenize` and `matchAllTokens` is enabled. When you search for `white ` (with a trailing whitespace), the `tokens` are `['white', '']`. This causes fuse to return no results due to one empty token. Would removing empty tokens as below be a fix for this?

```
var tokens = pattern.split(options.tokenSeparator).filter(function(token){
    return token !== '';
})
```

**Comment by krisk** [comment]
Good find. Ideally, white spaces should be eliminated. Any takers? 😄

**Comment by jwmann** [comment]
I have applied a simple fix for this issue. Passes all tests and works as expected.

**Comment by jeffal** [comment]
@krisk Can we re-build @jwmann's PR?

**Comment by jwmann** [comment]
@jeffal I pulled in and re-built with the most recent master changes. Thank god Travis-CI didn't fall off a cliff this time and built successfully.

Just needs a merge.

**Comment by Tsourdox** [comment]
Can the PR be opened and merged? Seems like a simple fix no? ^^

**Comment by dlosie** [comment]
I solved this by using `String.prototype.trim()` on my search query to remove unwanted leading /trailing whitespace.

```javascript
fuse.search(query.trim());
```
