### ISSUE TITLE
Add support for non-ASCII search

### ISSUE THREAD

**Issue by maxcorbeau** [krisk/Fuse#133]
Hi all,

Currently, Fuse doesn't support searching through non-ASCII characters. For instance searching with `stro` on `strömberg` only matches `str`. This could be changed by
 - transliterating input to ASCII  (e.g. `stro` -> `stro`)
 - transliterating all strings within an item to ASCII when evaluating that item (e.g. `strömberg` -> `stromberg`)
 - performing the match on the transliterated item (e.g. `match [0,3]`)
 - returning original version item + matches (e.g. `strömberg` + `match [0,3]`)

This code seems to have a pretty complete transliteration table (see `char_map` object):
https://github.com/pid/speakingurl/blob/master/lib/speakingurl.js

Not that I have a need for it at the moment, just bringing it up as a suggestion :)

**Comment by drzraf** [comment]
`"string".normalize('NFD').replace(/[\u0300-\u036f]/g, "");` would do it as part of a lexer

**Comment by popod** [comment]
Any news about this feature ? Will it be implemented soon ? Thanks

**Comment by pinturic** [comment]
Lots of people need it...

**Comment by codebury** [comment]
Hi! Any news about this feature?

**Comment by bleuscyther** [comment]
I think this should solve the issue:
https://github.com/krisk/Fuse/issues/415 

It uses the [diacritics](https://www.npmjs.com/package/diacritics)  library.
