### ISSUE TITLE
Full text score location invariant

### ISSUE THREAD

**Issue by Toxinto** [krisk/Fuse#135]
Consider the query "Gamma" with the corpus: 

{
  'ISBN': 'A',
  'title': "Alpha Beta Gamma",
  'author': 'Alpha Beta'
}, {
  'ISBN': 'B',
  'title': 'Gamma Alpha Beta',
  'author': 'Alpha Beta'
}, {
  'ISBN': 'C',
  'title': 'Alpha Gamma Beta',
  'author': 'Alpha Beta'
}

The resultant scores are all different, with the earlier Gamma appears in the title, the higher the score. 

How do I get them to all be the same score? 

Is this desired in the implementation?

**Comment by mgalgs** [comment]
What are you using for `location` and `distance`?

**Comment by mgalgs** [comment]
Maybe just set a super high `distance`?

**Comment by krisk** [comment]
> Is this desired in the implementation?

Yes. The heart of string approximation (fuzzy-matching) is based on distance calculation. The distance is calculated from character at index zero (by default), which translates "how far is the pattern from the beginning of the text". As @mgalgs suggested, you can fiddle with the `distance` option to achieve your desired behavior.
