### ISSUE TITLE
Method to cancel search?

### ISSUE THREAD

**Issue by wbrickner** [krisk/Fuse#139]
Hello, I've just started using fuse.

I search a very large array of objects (~**15000**), each with one property (let's call it `name`).
Every search returns thousands of results.

I can't tell if fuse has performance issues, probably not, it's just a very large array.
Anyway, I put it in a web worker, and now the UI is perfectly responsive but the results returned from the web worker still lag behind because it's still executing old searches.

I'd like to be able to cancel all pending searches before I start a new one.

I imagine this wouldn't be very difficult to implement?

**Comment by krisk** [comment]
This is **not** a Fuse issue 😄  Sounds like you should throttle/debounce the searching that is executed on the Web Worker.

**Comment by wbrickner** [comment]
Yeah, I agree that it's not a _problem_ with Fuse.  I meant to make a feature request, sorry if I didn't communicate that clearly.  I tried implementing it myself, but I don't understand exactly how Fuse works internally.  I'll try again.

Also, I don't want to throttle the function and limit how often it can fire, I want to be able to cancel a search that was started that is no longer relevant because I have a new query to search by before the old search completes.  I'm using Fuse for a real time as-you-type suggestions drop down.  So the user plans to type "foo", it ends up searching for "f", then "fo", then "foo".  To avoid this, I'd like to be able to cancel any searches being performed, and then I'll call `search("foo")`.

I was thinking I could implement this by adding an internal variable, say `abort`, and then in `Fuse.js`, starting around line 187, I could modify it to have 
```
...

this._keyMap = {}
      // Otherwise, the first item is an Object (hopefully), and thus the searching
      // is done on the values of the keys of each item.
      // Iterate over every item
      for (i = 0; i < listLen; i++) {
         if (abort === true) { abort = false; break; }
...
```

This is just a guess.  You built and maintain Fuse, to your understanding would this method work?  (abort the current search by setting abort to true?)

**Comment by wbrickner** [comment]
Also, I don't understand what you mean by 

> The idea of a cancel operation would only make sense if Fuse contained some asynchronous behavior, which it doesn't have.

I don't mind if Fuse has async behavior or not, either way I would like a way to stop the execution of the search function before it has returned the results.

**Comment by krisk** [comment]
If you have Fuse running in a Web Worker, and you pass that `abort` keyword to that same worker, then yes, you could have Fuse stop searching. 

Also a though, perhaps you could opt to [terminate](https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate) that worker. The caveat would be that you'd have to create a new worker for every Fuse instance.

**Comment by wbrickner** [comment]
Perfect, that's exactly what I was looking for.  I don't want to terminate the worker and load the Fuse script and my data in every time the value of the input changes, I can only imagine how slow that would get.

Thank you for your help!

**Comment by KonradHoeffner** [comment]
You can also wait with searches if the last one was long and a short time ago and check later if it is still needed. I am using this implementation:

```
  search(query)
  {
    if(!query||query.length<2) {return this.data;}
    const start = new Date().getTime();
    this.lastSearchStart=start;
    const items = this.fuse.search(query).map(x=>x.item.bezeichnung);
    const hits = new Set(items);
    const filteredData = this.data.filter(row=>hits.has(row.bezeichnung));
    const end = new Date().getTime();
    this.lastSearchDuration=end-start;
    return filteredData;
  }

  throttledSearch(query)
  {
    // throttle searches to not overload the CPU
    const start = new Date().getTime();
    lastSearchTaskStart = start;
    if(lastSearchDuration>100&&(start-lastSearchStart<lastSearchDuration*4))
    {
      setTimeout(() =>
      {
        // do we still need the search?
        if(lastSearchTaskStart===start) {search(query);}
      }, lastSearchDuration*4);
    } else
    {
      search(query);
    }
  }

```
