### ISSUE TITLE
Unexpected result of matchAllTokens=true

### ISSUE THREAD

**Issue by ericfong** [krisk/Fuse#142]
Thanks for your really amazing package.

When I try to use `tokenize=true` and `matchAllTokens=true` with multiple keys, 
I found that result is quite different from what I think.

I think input will be tokenized and match all with all fields. 
If I have keywords 'old' and 'john', those two keywords can match with title and author field as shown below

```js
  var books = [{
    'title': 'Old Man\'s War',
    'author': 'John Scalzi',
  }, {
    'title': 'The Lock Artist',
    'author': 'Steve Hamilton',
  }]
  const fuse = new Fuse(books, {
    shouldSort: true,
    tokenize: true,
    matchAllTokens: true,
    threshold: 0,
    keys: ['title', 'author'],
  })
  expect( fuse.search('old john') ).toEqual([
    {
    'title': 'Old Man\'s War',
    'author': 'John Scalzi',
    },
  ])
```

But a empty array return. I would like to know this is expected / designed or ... ?
I should find some work around for that?

**Comment by krisk** [comment]
That's the correct behavior 😄 

When `matchAllTokens=true`, if you search `"old john"`, then **every** token in that pattern string must exist in either `title` or `author`. 

Specifically, it checks:

- Whether `"old"` AND `"john"` can be found in the `title`
- Whether `"old"` AND `"john"` can be found in the `author`

**Comment by ericfong** [comment]
Thx. then, I should think of some work around way

**Comment by chadwatson** [comment]
@krisk I actually expected this to work the same way that @ericfong did. And the product I am currently working on needs our search to work that way. Would you be open to a PR that adds an option for that behavior?

**Comment by sjungwirth** [comment]
Also running into this issue when processing objects with firstName and lastName using `keys`. If I use `matchAllTokens` I get no results, if I don't use `matchAllTokens` I get too many results. Yes I could combine first+last into `fullName` but I have other meta data keys I'd like to search as well, for example: 'john smith author'.
