### ISSUE TITLE
[Q] How to clear search?

### ISSUE THREAD

**Issue by JulianKingman** [krisk/Fuse#143]
I'm currently clearing the search by just doing `fuse.search('')`, but that is actually returning results (not quite sure why), what's the best way to clear the search results and start over?

**Comment by krisk** [comment]
No such way at the moment.

**Comment by hajkli** [comment]
Hello Krisk,
 Can I ask you about this "feature"? Can I clear search result by any way or thre is still no such way?

thanks

**Comment by JulianKingman** [comment]
What I've been doing is keeping a reference to the unfiltered data, then use it like this:
`this.state.searchFilter ? filteredData : unfilteredData`
