### ISSUE TITLE
Numbers not getting match

### ISSUE THREAD

**Issue by datpham23** [krisk/Fuse#144]
I'm not sure if this is a bug or not part of Fuse's scope, but numbers doesn't seem to be matching. 

var data = [{
name : 'john',
age : 75
}];

var fuse = new Fuse(data, {
      shouldSort: false,
      threshold: 0.2,
      minMatchCharLength: 1,
      keys: ['name', 'age']
    });

fuse.search("75")

**Comment by datpham23** [comment]
Found a hack that works. 
getFn: function (obj, path) {
        if(Number.isInteger(obj[path]))
          return JSON.stringify(obj[path]);
        return obj[path];
}

**Comment by baloodevil** [comment]
To implement @datpham23's workaround, override the getFn property of the _options object_ with the function he used.
