### ISSUE TITLE
String isn't sanitized before being turned into a pattern

### ISSUE THREAD

**Issue by yacinehmito** [krisk/Fuse#145]
I stumbled upon a critical bug that can make a search crash provided that the pattern to match contains some unusual characters.

## Steps to reproduce

```
const Fuse = require('fuse.js')
const f = new Fuse(['some fake data'])
f.search('searching with a sufficiently long string sprinkled with (parentheses)')
```

It will crash with:

```
TypeError: Cannot read property 'length' of undefined
```

It comes from this line: https://github.com/krisk/Fuse/blob/master/src/fuse.js#L657

## Causes

The real culprit is this line: https://github.com/krisk/Fuse/blob/master/src/fuse.js#L650
The string is turned into a pattern without sanitizing for characters of the Regex grammar.

This is a severe bug ; I would be very grateful if a fix is promptly released.

**Comment by meltuhamy** [comment]
I can reproduce this on http://fusejs.io/ by typing this in the console: 

```
var f = new Fuse(['some fake data']);
f.search('searching with a sufficiently long string sprinkled with (parentheses)');
```

And I get:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at o.search (fuse.min.js:20)
    at s._analyze (fuse.min.js:20)
    at s._startSearch (fuse.min.js:20)
    at s.search (fuse.min.js:20)
    at <anonymous>:2:3
```

**Comment by pharrukh** [comment]
I got similar behavior when I have brackets "()".

This is the string that breaks: 'App för spara filer i Office365 (word, powerpoint, excel)'

Removing the brackets solves the issue.
