### ISSUE TITLE
Fuse returns confusingly incorrect results

### ISSUE THREAD

**Issue by cozmo** [krisk/Fuse#150]
Was playing around with Fuse to see if it could work for some simple data we need to search over, but I'm seeing baffling results. Below we have 2 items of data, each with two keys. The search term is also two words, nothing misspelled or anything. This also happens if you have `tokenize` enabled. 

If you have `tokenize` _and_ `matchAllTokens` the below example returns _no results_. To my untrained eye this seems like a pretty cut and dry example, so either I'm missing something obvious or there's something very strange going on under the hood.

```js
const Fuse = require("fuse.js");
const assert = require("assert");

const data = [{
  firstName: "Nikki",
  lastName: "Wolfe",
}, {
  firstName: "Brian",
  lastName: "Wolfe",
}];

const searcher = new Fuse(data, {
  keys: ["firstName", "lastName"],
  shouldSort: true,
});

assert.deepEqual(searcher.search("brian wolfe"), [ // This test fails, but should pass. 
  { firstName: "Brian", lastName: "Wolfe" },
  { firstName: "Nikki", lastName: "Wolfe" },
]);
```

For posterity the above returns the following, which fails the test case. 
```js
[ { firstName: 'Nikki', lastName: 'Wolfe' }, { firstName: 'Brian', lastName: 'Wolfe' } ]
```

Happy to help fix if someone can point me in the right direction - I got pretty deep down adding logs into the searchflow but didn't know quite what I should be looking for.

**Comment by Sigmus** [comment]
The problem is with your assertion. If you do:

```
console.log(searcher.search("Brian Wolfe"));
```
You'll see the correct results.

**Comment by cozmo** [comment]
@Sigmus I actually did that in order to build the assertion. When I do that I see

```js
[ { firstName: 'Nikki', lastName: 'Wolfe' },
  { firstName: 'Brian', lastName: 'Wolfe' } ]
```

Notice the Nikki being listed first, rather than Brian. If you return scores as well you see

```js
[ { item: { firstName: 'Nikki', lastName: 'Wolfe' },
    score: 0.5454545454545454 },
  { item: { firstName: 'Brian', lastName: 'Wolfe' },
    score: 0.5454545454545454 } ]
```

Which has the scores being identical (which explains the incorrect order).

**Comment by Sigmus** [comment]
And if you search "Nikki Wolfe" the results are correct. 

Setting ```threshold ``` to ```1``` makes Brian appear as first. Not sure why the default returns Nikki as first.

**Comment by cozmo** [comment]
@Sigmus Yes if you search "Nikki Wolfe" that is returned first because the score is exactly the same, so they're returned in the order they exist in the input. You can see this by swapping the order of the input and verifying that Nikki is no longer returned first

```js
const Fuse = require("fuse.js");
const assert = require("assert");

const data = [{
  firstName: "Brian",
  lastName: "Wolfe",
}, {
  firstName: "Nikki",
  lastName: "Wolfe",
}];

const searcher = new Fuse(data, {
  keys: ["firstName", "lastName"],
  shouldSort: true,
});

// Nicki is returned second, even though she should be returned first, causing this test to fail
// [ { item: { firstName: 'Brian', lastName: 'Wolfe' },
//     score: 0.5454545454545454 },
//   { item: { firstName: 'Nikki', lastName: 'Wolfe' },
//     score: 0.5454545454545454 } ]
assert.deepEqual(searcher.search("brian wolfe"), [
  { firstName: "Brian", lastName: "Wolfe" },
  { firstName: "Nikki", lastName: "Wolfe" },
]);
```

*However* - You are correct about setting threshold to `1` fixing the problem. I've been able to narrow it down to anything >=0.909090 repeating working, and anything below that failing. 

Is it expected behavior that changing threshold changes the sort order? Reading the docs makes it sound like it determines at what point something is considered a match, not anything to do with sort order in the returned documents.
