### ISSUE TITLE
Rearchitecture broke our libraries

### ISSUE THREAD

**Issue by michaelgeorgeattard** [krisk/Fuse#152]
Can you kindly revert the changes, and commit your changes in 3.x?

I think your changes should have resulted in a major version change, not a minor one.

**Comment by krisk** [comment]
I reverted the changes, and committed the rearchitecture to `3.0.0`.

Versions `2.*.*` should all be good now. My apologies!

**Comment by michaelgeorgeattard** [comment]
Thank you for the fix!
