### ISSUE TITLE
Keep getting empty result, even though same data works in demo on fusejs.io

### ISSUE THREAD

**Issue by marinaalens** [krisk/Fuse#153]
Hi!

I am working on a project where I need to search a list of products in JSON format:

`[{"_id":"59077a74c00de719e8531f38","navn":"Okse spegepølse","enhed":"stk","pris":69.95,"beskrivelse":"","varekategori":{"_id":"59076e76f44961273860a8dc","navn":"Spegepølse","__v":0},"__v":0},{"_id":"59077a74c00de719e8531f39","navn":"Mexico spegepølse","enhed":"stk","pris":69.95,"beskrivelse":"","varekategori":{"_id":"59076e76f44961273860a8dc","navn":"Spegepølse","__v":0},"__v":0}]`

And here is my code - I am using an <input> for the search bar and tracking the input with 'keyup'. Then I pass the value to fuse and display them in a list. The result is empty no matter what I do, even though the search input is valid... I am using CDN v. 2.6.1. I tried the exact same data in the demo at fusejs.io and it worked perfectly.
Can someone take a look at it? Would be a huge help!
```
var options = {
    shouldSort: true,
    threshold: 0.6,
    location: 0,
    distance: 100,
    maxPatternLength: 32,
    minMatchCharLength: 1,
    keys: [
        "navn"
    ]
};
var fuse = new Fuse(varer, options);

$(document).on('keyup', '#søg_vare_felt', function () {
    var search = $('#søg_vare_felt').val();
    var result = fuse.search(search);

    $.get("vare_oversigt.hbs", function(template){
        var compiled = Handlebars.compile(template);
        var obj = {vare: result};
        var html = compiled(obj);
        $("#vare_oversigt").html(html);
    })
});
```

**Comment by Tikotik** [comment]
How is it solved? @marinaalens
