### ISSUE TITLE
Indices doesn't support array of objects for use highlight

### ISSUE THREAD

**Issue by golinmarq** [krisk/Fuse#161]
When we have an array like this
```javascript
const data =[
    {fullname: "John Doe",
    articles: [
        {title: "A Hello World!", body: "Bla bla bla"},
        {title: "A Bye World!", body: "Bla bla bla"},
    ]},
    ...
];
```
and you are looking for "Bye" for example, the **matches** key shows the indices of the word but, the key will be "articles.title". Sure, this one is ok but, the indices are refereed to the second item in the articles array, and by this info I can't get it. Probably, the key should "articles[1].title"

**Comment by jamealg** [comment]
This pull request addresses this:
https://github.com/krisk/Fuse/pull/156

I tried it out and it seems to work well.

**Comment by golinmarq** [comment]
@jamealg sure, it's a great PR but I don't know if @krisk is going to merge it

**Comment by krisk** [comment]
@jamealg, @golinmarq  - I plan to approve that PR, once the output comment is addressed 😄
