### ISSUE TITLE
minMatchCharLength doesn't work properly

### ISSUE THREAD

**Issue by zecaptus** [krisk/Fuse#164]
Hello,

As I said in the title, this `minMatchCharLength` doesn't work properly.

Here is my Fuse config : 

```JS
new Fuse(this.props.data, {
      shouldSort: true,
      tokenize: true,
      includeScore: true,
      includeMatches: true,
      threshold: 0.3,
      location: 0,
      distance: 100,
      maxPatternLength: 32,
      minMatchCharLength: 4,
      keys: [
        "label",
        "children.label"
      ]
    });
``` 

if I search for a string with a length lower than my `minMatchCharLength`, fuse still return some results with an empty `indices` array ... 

![capture d ecran 2017-05-30 a 11 00 14](https://cloud.githubusercontent.com/assets/7048870/26575900/52b2d142-4527-11e7-9c64-ac8475ca8df1.png)

**Comment by Hypnosphi** [comment]
From http://fusejs.io/
>Minimum character length  
>
>When set to include matches, only the matches whose length exceeds this value will be returned. >(For instance, if you want to ignore single character index returns, set to 2)

So it shouldn't affect the results, only the matches

**Comment by jhabdas** [comment]
@zecaptus looks like this wasn't closed with the merged pr. should this still be open?

**Comment by FuadEfendi** [comment]
I think it still doesn't work. Search for "abc" returns the same number of results without any dependency on minMatchCharLength being 1 or 3.

Setting `findAllMatches=true/false` doesn't impact neither.

**Comment by FuadEfendi** [comment]
perhaps because some parameters hardcoded, and some lowercased?
``` 
{{- $options := dict "ignoreLocation" true "includeMatches" true "includeScore" true "keys" $keys -}}
{{- $optionWhitelist := slice "ignoreLocation" "isCaseSensitive" "minMatchCharLength" "threshold" "distance" "useExtendedSearch" -}}
{{- with .Site.Params.search.fuse -}}
  {{- range $key, $value := . -}}
    {{- range $optionWhitelist -}}
      {{- if eq $key (lower .) -}}
```
