### ISSUE TITLE
Limit results by score

### ISSUE THREAD

**Issue by LindenWalsh** [krisk/Fuse#166]
Is there a way to limit results by score? I've started filtering the results themselves by their score value but wondering if there is a built in way to do it. One reason I don't want to filter it afterwards is that for some reason I haven't been able to figure out yet is that the score isn't being returned for me. 

Cheers!

**Comment by krisk** [comment]
For questions please read the [where-to-post summary](https://github.com/krisk/Fuse#where-to-post-summary) 😅 

Nonetheless, if you want to filter by score, you first need to include the score in the options. You can check the [demo](http://fusejs.io/) for details. If that doesn't work, how have you initiated the Fuse instance?

**Comment by ernsheong** [comment]
I believe the `threshold` is the variable to use to limit what results by score, but the correlation is not exact (i.e. threshold is not a score threshold)
