### ISSUE TITLE
set() function is gone from 3.0.5 (or maybe earlier)

### ISSUE THREAD

**Issue by odabrunz** [krisk/Fuse#170]
which is a breaking change (breaking my module), so probably introduced with 3.0.0.

The `set()` function is not mentioned on [fusejs.io](http://fusejs.io/) anyway, but I believe it was mentioned on [the npm package page](https://www.npmjs.com/package/fuse.js), which is gone now ([this fork](https://www.npmjs.com/package/fuse-js-latest) still has those docs).

So this is probably intentional.

I am just wondering because this is a silent change, I did not see any mention of it anywhere, even in the [changelog](https://github.com/krisk/Fuse/blob/master/CHANGELOG.md).

```javascript
$ node
> var f = require('fuse.js')
undefined
> var fuse = new f(['testing', 'toasting'], {});
undefined
> fuse.set(['new', 'word', 'list'])
TypeError: fuse.set is not a function
    at repl:1:6
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
>
```

So I guess now I have to write:

```javascript
let options = { ... };
let results = [];
for (let list of listOfLists) {
  let fuse = new Fuse(list, options);
  results = results.concat( fuse.search(pattern) );
}
```
instead of
```javascript
let options = { ... };
let results = [];
let fuse = new Fuse([], options);
for (let list of listOfLists) {
  fuse.set(list);
  results = results.concat( fuse.search(pattern) );
}
```
right?

**Comment by krisk** [comment]
Ah yeah, a silent change. Should've been added into the CHANGELOG.

**Comment by odabrunz** [comment]
Thanks for the clarification. :)

**Comment by KagamiChan** [comment]
There's a new method call `setCollection`, but I think assigning directly `fuse.list` is OK, at least for now?
