### ISSUE TITLE
React Native : TransformError with babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by Freddy03h** [krisk/Fuse#171]
Hello,

Fuse does'nt work with React Native since 3.X

Importing Fuse in a react-native projet causes an issue with babel-plugin-add-module-exports :
```
TransformError: […]/node_modules/fuse.js/dist/fuse.js: Unknown plugin "babel-plugin-add-module-exports" specified in "[…]/node_modules/fuse.js/.babelrc" at 0, attempted to resolve relative to "[…]/node_modules/fuse.js"
```

Is there an extra step to do on a react-native project ?
Thank's

**Comment by Noitidart** [comment]
I am having this same issue. I am trying to import/require it in all kinds of ways. I am also using this in a react-native project.

I tried the following ways:

```
const Fuse = require('fuse.js/dist/fuse.js');
const Fuse = require('fuse.js/src');
const Fuse = require('fuse.js');
import Fuse from 'fuse.js'
import Fuse from 'fuse.js/src'
import Fuse from 'fuse.js/dist/fuse'
```

**Comment by Noitidart** [comment]
What I did was copy the the `src` dir from `node_modules/fuse.js/src` and pasted it into my ./app/ dir but renamed it to `fuse`. So from `./node_modules/fuse.js/src` to `./app/fuse` and then I import it like this:

    const Fuse = require('./fuse');

Its a workaround for now.

**Comment by Noitidart** [comment]
Thank you @krisk for such a fast fix! I didn't test it yet but will sure do so soon :)

**Comment by ismaeldcom** [comment]
The last version available in npm 3.0.5 doesn't have .babelrc in .npmignore file yet.

Thanks @krisk for your amazing work with fuse.

**Comment by meriadec** [comment]
Hey there, following the discussion, @krisk would you mind publish a release to npm?
Thanks in advance!

**Comment by defualt** [comment]
try `import Fuse from 'fuse.js/src';`

**Comment by KasparasGud** [comment]
@defualt  Solution worked for me !
