### ISSUE TITLE
Custom size CameraView is distorted

### ISSUE THREAD

**Issue by banil-la** [krisk/Fuse#174]
When I create custom size CameraView, I expect that CameraView will be masked by size properties.
```
<App>
	<Panel>
		<NativeViewHost>
			<CameraView ux:Name="cameraView" Facing="Back" Height="200"/>
		</NativeViewHost>
	</Panel>
</App>
```

but it is distorted like below photos.

(100% x 100%)
![origin](https://user-images.githubusercontent.com/7641973/28098815-72694abe-66f3-11e7-9552-40f970b4dc42.jpeg)

(100% * 400px)
![custom](https://user-images.githubusercontent.com/7641973/28098814-7263b36a-66f3-11e7-9217-03cf9b1c1c36.jpeg)

**Comment by nxz91** [comment]
are you sure this is the right repository? 🤔

**Comment by banil-la** [comment]
Oh, my. Sorry :( It isn't
