### ISSUE TITLE
The dist package doesn't work as-is with RequireJS

### ISSUE THREAD

**Issue by fwextensions** [krisk/Fuse#178]
I'm not sure if this is an issue with RequireJS or Webpack, but I stumbled upon it when trying to use the `fuse.js` file in `dist` with a project that was using RequireJS.  For some reason, the factory function defined in the Webpack boilerplate (`define("Fuse", [], factory);`) is never called by RJS, and therefore the module that's trying to require the Fuse module gets `undefined` instead.

Changing that line in the boilerplate to just `define([], factory)`, creating an anonymous module, solves the issue.  I think changing `umdNamedDefine: true` to `false` in `webpack.config.js` would fix the issue, though I'm not sure what other ramifications that might have.

**Comment by WhereJuly** [comment]
@fwextensions thanks a lot for the heads up. I just changed in the minified version. It works.
