### ISSUE TITLE
Weighted keys should return weighted exact matches

### ISSUE THREAD

**Issue by paulfalgout** [krisk/Fuse#179]
In the case of:
```javascript
 var fuse = new Fuse(books, {
   keys: [{
     name: 'title',
     weight: 0.3
   }, {
     name: 'author',
     weight: 0.7
   }],
 });
```
An exact match in either title or author or both will give the same score so the weights don't matter.  But I would expect that an exact match in both would weight better than an exact match in only author which would weight better than an exact match in title.

**Comment by seanmt13** [comment]
I am also seeing this issue. I would expect that if you return the exact matches on less weighted items should not have a score of 0.

**Comment by sheldonrong** [comment]
@krisk @seanmt13  @paulfalgout 

I am also experiencing this issue. A quick fix from my understanding is that when weighted search is enabled, even exact match cannot have a score of 0, so in this case:

`@@ -884,8 +884,8 @@ var Fuse = function () {
         var bestScore = 1;
 
         for (var j = 0; j < scoreLen; j += 1) {
-         var score = output[j].score;
           var weight = weights ? weights[output[j].key].weight : 1;
+         var score = weight === 1 ? output[j].score : output[j].score || 0.001;
           var nScore = score * weight;
           if (weight !== 1) {`
I cannot say if this is the correct way to go, but from the superficial level, it does seems to work (I've setup some test cases, and all your test cases passed).

Happy to send you a pull request if you do not object this idea.

**Comment by sheldonrong** [comment]
PR : #192
