### ISSUE TITLE
Searching with number and threshold of 1 not getting any match

### ISSUE THREAD

**Issue by oryangit** [krisk/Fuse#182]
> a threshold of 1.0 would match anything.

but when searching number it doesn't work.

```
var data = [
        title: "Old Man's War",
        author: "John"
];

var fuse = new Fuse(data, {
shouldSort: true,
threshold: 1,
keys: ['title', 'author']
});

fuse.search("2")
```

**Comment by moritz-h** [comment]
I can confirm this. And it is not limited to numbers, also with other strings (i.e. search 'q' on fusejs.io) I only get a subset of the original list as result.
I would like to use the threshold=1 option to sort the list by similarity, therefore it would be nice if the full list would be returned as documented.

**Comment by otmichael** [comment]
I'm having the same issue, would like `threshold: 1` to return a sorted version of the full list.

**Comment by moritz-h** [comment]
@github-actions This is still an issue.
