### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by mlucool** [krisk/Fuse#184]
Hi,

You have an Apache-2.0 license text in the project, but just write 'Apache', a invalid SPDX name, in the license field of package.json. Can you please ensure these match? I assume you mean to have this in package.json: `"license": "Apache-2.0"`

See: https://docs.npmjs.com/files/package.json#license

**Comment by ravjsdev** [comment]
+1 I agree - please can you update the license key in the package.json so that it is explicit which Apache license it is and also use the valid SPDX license identifier as per @mlucool 's comment
thanks.
