### ISSUE TITLE
Results with filtered children?

### ISSUE THREAD

**Issue by iamvitali** [krisk/Fuse#186]
Hi,
So if we have an array of objects and search for them, Fuse returns the objects that match the criteria.
But if said objects have an array of children which we want to search, is it possible to filter those to the search criteria as well?

Examples:
```
[
	{
		label: 'parent123',
	},
	{
		label: 'parent321',
	}.
]
```

If we search for `parent123` we will get:
```
[
	{
		label: 'parent123',
	}
]
```

But if it's a group with children:
```
[
	{
		label: 'parent123',
		children: [
			{
				label: 'child1'
			},
			{
				label: 'child2'
			},
			{
				label: 'child3'
			},
		]
	},
...
```

Is it possible for a search of `parent123` to return back that object (as usual) but for a search of `child2` to get back:
```
[
	{
		label: 'parent123',
		children: [
			{
				label: 'child2'
			},
		]
	}
]
```
? :)

**Comment by ashusdn** [comment]
Hi ,

I also want same behavior in my project. My array as below

var test= [
  {
    "title": "Floor A",
    "id": "55fea689216b519578bc1b3a",
    "units": [
      {
        "unitTitle": "A.0.1",
        "unitID": "55fea689216b519578bc1b6e"
      },
      {
        "unitTitle": "A.0.2 - EG",
        "unitID": "55fea689216b519578bc1b6f"
      }
    ]
  },
  {
    "title": "Floor B",
    "id": "55fea689216b519578bc1b3b",
    "units": [
      {
        "unitTitle": "B.0.1",
        "unitID": "55fea689216b519578bc1b98"
      },
      {
        "unitTitle": "B.0.2 - EG",
        "unitID": "55fea689216b519578bc1b99",
      },
  ]
  }
]

suppose I want to search "Floor" then it should return all the record that matches with it. If I search "B.0.2" then my expected result will be:

{
        "unitTitle": "B.0.2 - EG",
        "unitID": "55fea689216b519578bc1b99",
      }

But I get the result as mentioned below:

{
    "title": "Floor B",
    "id": "55fea689216b519578bc1b3b",
    "units": [
      {
        "unitTitle": "B.0.1",
        "unitID": "55fea689216b519578bc1b98"
      },
      {
        "unitTitle": "B.0.2 - EG",
        "unitID": "55fea689216b519578bc1b99",
      },
  ]
  }

can you please provide any solution for it. I am waiting for your response.

**Comment by juliancoleman** [comment]
@ashusdn you may want to consider formatting your response using triple-backticks to render code blocks. That'll make it easier to read and allow others to help you out quicker.

**Comment by ccoeder** [comment]
@iamvitali If you have solved the problem, can you help me?

**Comment by pratikt-cuelogic** [comment]
Any luck here;

I'll add my usecase here;
List =>

```
[
	{
		id: 1,
		title: this is my title-ABC,
		items: [
			{
				title: this is my subitem-ABC,
				description: this is my descriptionA,
			},
			{
				title: this is my subitem-QQQ,
				description: this is my description-ABC,
			},
			{
				title: this is my subitem-WWW,
				description: this is my description,
			}
		]
	},
	{
		id: 1,
		title: this is my title,
		items: [
			{
				title: this is my subitem,
				description: this is my descriptionA,
			},
			{
				title: this is my subitem,
				description: this is my description-ABC,
			},
			{
				title: this is my subitem,
				description: this is my description,
			}
		]
	},
	{
		id: 1,
		title: this is my title,
		items: [
			{
				title: this is my subitem,
				description: this is my descriptionA,
			},
			{
				title: this is my subitem,
				description: this is my description,
			},
			{
				title: this is my subitem-WWW,
				description: this is my description,
			}
		]
	}
]
```

```
var options = {
  ...
  keys: [
    "title",
    "items.title",
    "items.description"
]
};
var fuse = new Fuse(list, options); // "list" is the item array
var result = fuse.search("ABC");
```

Expected search result;

```
[
	{
		id: 1,
		title: this is my title-ABC,
		items: [
			{
				title: this is my subitem-ABC,
				description: this is my descriptionA,
			},
			{
				title: this is my subitem-QQQ,
				description: this is my description-ABC,
			}
		]
	},
	{
		id: 1,
		title: this is my title,
		items: [
			{
				title: this is my subitem,
				description: this is my description-ABC,
			},
		]
	}
]
```

**Comment by ccoeder** [comment]
Hi, I could not solve this problem with fuse, but I think that I can solve my own problem, maybe it helps you. I put the values I need to search into another array. And I did the search here.

You can find the demo [here](https://jsfiddle.net/W4QfJ/14867/). 

I also share the codes here github.

```
const list = [{
    id: 1,
    title: "this is my title-ABC",
    items: [{
        title: "this is my subitem-ABC",
        description: "this is my descriptionA",
      },
      {
        title: "this is my subitem-QQQ",
        description: "this is my description-ABC",
      },
      {
        title: "this is my subitem-WWW",
        description: "this is my description",
      }
    ]
  },
  {
    id: 1,
    title: "this is my title",
    items: [{
        title: "this is my subitem",
        description: "this is my descriptionA",
      },
      {
        title: "this is my subitem",
        description: "this is my description-ABC",
      },
      {
        title: "this is my subitem",
        description: "this is my description",
      }
    ]
  },
  {
    id: 1,
    title: "this is my title",
    items: [{
        title: "this is my subitem",
        description: "this is my descriptionA",
      },
      {
        title: "this is my subitem",
        description: "this is my description",
      },
      {
        title: "this is my subitem-WWW",
        description: "this is my description",
      }
    ]
  }
];

const subItems = _.flatMap(list, data => data.items);

var options = {
  shouldSort: true,
  threshold: 0.1,
  location: 0,
  distance: 100,
  maxPatternLength: 32,
  minMatchCharLength: 1,
  keys: [
    "title",
    "description"
  ]
};

var fuse = new Fuse(subItems, options);
var result = fuse.search("this is my subitem-ABC");

console.log(result);
```

**Comment by shishirraven** [comment]
The solution provided by @ccoeder is kind of close but different. Thanks @ccoeder for it
 It strips off the hierarchy. 
But does anyone has a closer solution to this problem? Please share.
