### ISSUE TITLE
How do i search in this?

### ISSUE THREAD

**Issue by onigetoc** [krisk/Fuse#191]
How do i search in this?

```
{
  "list": {
    "service": "movies",
    "item": [
      {
        "service": "iptv",
        "title": "Newsmax TV",
        "url": "http://website.com/test.file.m3u8",
      },
      {
        "service": "iptv",
        "title": "Infowars Live",
        "url": "http://website.com/test.file.m3u8",   
      }
    ]
  }
}
```

**Comment by lunaroyster** [comment]
As far as I've learnt, Fuse searches arrays of objects. If you want to search the item element in the list,

    var options = {
      keys: ['service', 'title', 'url'],
    };
    var fuse = new Fuse(list.item, options)

If you want to search all of it, you need to pass the list elements as an array, perhaps something like this

    var lists = [
        {list: {"service": "movies", "item":[...] }},
        {list: {"service": "podcasts", "item":[...] }}
    ]

    var options = {
      keys: ['list.service', 'list.item.service', 'list.item.title'],
    };
    var fuse = new Fuse(lists, options)

**Comment by acomito** [comment]
I'm currently trying to search "jurisdictions" by their id.... not sure the options setup for this.



`
    "stateOptions": Array [
      Object {
        "abbreviation": "AL",
        "id": 2,
        "jurisdictions": Array [
          Object {
            "abbreviation": "",
            "id": 3,
            "name": "Autauga County",
          },
          Object {
            "abbreviation": "",
            "id": 4,
            "name": "Baldwin County",
          },
          Object {
            "abbreviation": "",
            "id": 5,
            "name": "Barbour County",
          },
          Object {
            "abbreviation": "",
            "id": 6,
            "name": "Bibb County",
          },
          Object {
            "abbreviation": "",
            "id": 7,
            "name": "Blount County",
          },
          Object {
            "abbreviation": "",
            "id": 8,
            "name": "Bullock County",
          },
          Object {
            "abbreviation": "",
            "id": 9,
            "name": "Butler County",
          },
          Object {
            "abbreviation": "",
            "id": 10,
            "name": "Calhoun County",
          },
          Object {
            "abbreviation": "",
            "id": 11,
            "name": "Chambers County",
          },
          Object {
            "abbreviation": "",
            "id": 12,
            "name": "Cherokee County",
          },
          Object {
            "abbreviation": "",
            "id": 13,
            "name": "Chilton County",
          },
          Object {
            "abbreviation": "",
            "id": 14,
            "name": "Choctaw County",
          },
          Object {
            "abbreviation": "",
            "id": 15,
            "name": "Clarke County",
          },
          Object {
            "abbreviation": "",
            "id": 16,
            "name": "Clay County",
          },
          Object {
            "abbreviation": "",
            "id": 17,
            "name": "Cleburne County",
          },
          Object {
            "abbreviation": "",
            "id": 18,
            "name": "Coffee County",
          },
          Object {
            "abbreviation": "",
            "id": 19,
            "name": "Colbert County",
          },
          Object {
            "abbreviation": "",
            "id": 20,
            "name": "Conecuh County",
          },
          Object {
            "abbreviation": "",
            "id": 21,
            "name": "Coosa County",
          },
          Object {
            "abbreviation": "",
            "id": 22,
            "name": "Covington County",
          },
          Object {
            "abbreviation": "",
            "id": 23,
            "name": "Crenshaw County",
          },
          Object {
            "abbreviation": "",
            "id": 24,
            "name": "Cullman County",
          },
          Object {
            "abbreviation": "",
            "id": 25,
            "name": "Dale County",
          },
          Object {
            "abbreviation": "",
            "id": 26,
            "name": "Dallas County",
          },
          Object {
            "abbreviation": "",
            "id": 27,
            "name": "DeKalb County",
          },
          Object {
            "abbreviation": "",
            "id": 28,
            "name": "Elmore County",
          },
          Object {
            "abbreviation": "",
            "id": 29,
            "name": "Escambia County",
          },
          Object {
            "abbreviation": "",
            "id": 30,
            "name": "Etowah County",
          },
          Object {
            "abbreviation": "",
            "id": 31,
            "name": "Fayette County",
          },
          Object {
            "abbreviation": "",
            "id": 32,
            "name": "Franklin County",
          },
          Object {
            "abbreviation": "",
            "id": 33,
            "name": "Geneva County",
          },
          Object {
            "abbreviation": "",
            "id": 34,
            "name": "Greene County",
          },
          Object {
            "abbreviation": "",
            "id": 35,
            "name": "Hale County",
          },
          Object {
            "abbreviation": "",
            "id": 36,
            "name": "Henry County",
          },
          Object {
            "abbreviation": "",
            "id": 37,
            "name": "Houston County",
          },
          Object {
            "abbreviation": "",
            "id": 38,
            "name": "Jackson County",
          },
          Object {
            "abbreviation": "",
            "id": 39,
            "name": "Jefferson County",
          },
          Object {
            "abbreviation": "",
            "id": 40,
            "name": "Lamar County",
          },
          Object {
            "abbreviation": "",
            "id": 41,
            "name": "Lauderdale County",
          },
          Object {
            "abbreviation": "",
            "id": 42,
            "name": "Lawrence County",
          },
          Object {
            "abbreviation": "",
            "id": 43,
            "name": "Lee County",
          },
          Object {
            "abbreviation": "",
            "id": 44,
            "name": "Limestone County",
          },
          Object {
            "abbreviation": "",
            "id": 45,
            "name": "Lowndes County",
          },
          Object {
            "abbreviation": "",
            "id": 46,
            "name": "Macon County",
          },
          Object {
            "abbreviation": "",
            "id": 47,
            "name": "Madison County",
          },
          Object {
            "abbreviation": "",
            "id": 48,
            "name": "Marengo County",
          },
          Object {
            "abbreviation": "",
            "id": 49,
            "name": "Marion County",
          },
          Object {
            "abbreviation": "",
            "id": 50,
            "name": "Marshall County",
          },
          Object {
            "abbreviation": "",
            "id": 51,
            "name": "Mobile County",
          },
          Object {
            "abbreviation": "",
            "id": 52,
            "name": "Monroe County",
          },
          Object {
            "abbreviation": "",
            "id": 53,
            "name": "Montgomery County",
          },
          Object {
            "abbreviation": "",
            "id": 54,
            "name": "Morgan County",
          },
          Object {
            "abbreviation": "",
            "id": 55,
            "name": "Perry County",
          },
          Object {
            "abbreviation": "",
            "id": 56,
            "name": "Pickens County",
          },
          Object {
            "abbreviation": "",
            "id": 57,
            "name": "Pike County",
          },
          Object {
            "abbreviation": "",
            "id": 58,
            "name": "Randolph County",
          },
          Object {
            "abbreviation": "",
            "id": 59,
            "name": "Russell County",
          },
          Object {
            "abbreviation": "",
            "id": 60,
            "name": "Shelby County",
          },
          Object {
            "abbreviation": "",
            "id": 61,
            "name": "St. Clair County",
          },
          Object {
            "abbreviation": "",
            "id": 62,
            "name": "Sumter County",
          },
          Object {
            "abbreviation": "",
            "id": 63,
            "name": "Talladega County",
          },
          Object {
            "abbreviation": "",
            "id": 64,
            "name": "Tuscaloosa County",
          },
          Object {
            "abbreviation": "",
            "id": 65,
            "name": "Walker County",
          },
          Object {
            "abbreviation": "",
            "id": 66,
            "name": "Washington County",
          },
          Object {
            "abbreviation": "",
            "id": 67,
            "name": "Wilcox County",
          },
          Object {
            "abbreviation": "",
            "id": 68,
            "name": "Winston County",
          },
        ],
        "name": "Alabama",
      },
`

**Comment by ccoeder** [comment]
@onigetoc If you have solved the problem, can you help me?
