### ISSUE TITLE
Are the number of matches being factored in?

### ISSUE THREAD

**Issue by lunaroyster** [krisk/Fuse#193]
![](https://i.imgur.com/c1Uwha4.png)

Results with a higher number of matches show up below results with only a few matches.

I think there should be a metric for factoring in the number of matches. Unless there already exists something, and I'm just missing it.

Perhaps a setting like `sortByMatchCount` which places the last three results up above the first two ones.

Config for the example above:

    var fuseOptions = {
        shouldSort: true,
        findAllMatches: true,
        includeScore: true,
        includeMatches: true,
        threshold: 0.6,
        location: 0,
        distance: 50,
        maxPatternLength: 32,
        minMatchCharLength: 4,
        keys: ["name", "longName", "tags", "description"]
    };

**Comment by sheldonrong** [comment]
You can override the default sorting function via passing= in the sortFn option atm.

I think this is a specific case that does not work well when you are doing fuzzy search. You could end up with results with more errors showing first than those that had one exact match.
