### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by kovart** [krisk/Fuse#196]
Library uses JSON.strigify to log objects in which it searches, but I use objects with circular structure so I catch "TypeError: Converting circular structure to JSON".
Can you fix that?

**Comment by ThinkTankShark** [comment]
@kovart Fixes it in this #197. It might not be the best solution but it definitely unblocks production code for now.

**Comment by avbentem** [comment]
As this was introduced in #183 (version 3.1.0, September 2017), a downgrade to version 3.0.5 (June 2017) worked for me as a workaround until the merged fix #219 is released; `npm i --save fuse.js@3.0.5`.

**Comment by krisk** [comment]
Has been fixed.
