### ISSUE TITLE
[Enhancement] Showing results for ... 

### ISSUE THREAD

**Issue by yarnball** [krisk/Fuse#201]
Hi,

Amazing work on this. Thank you.

I have an enhancement idea. It would be great to get a "did you mean _word_" for mis-spellings. 

Similar to a Google search, this way when a user types "treas", it could say "Showing results for Trees" as there we no matches of "treas" but there were matches of "Trees".

Is this possible?

Thanks

**Comment by krisk** [comment]
Interesting idea, but I'm not sure if this is a behavior that Fuse should handle. It seems to me that it should live as a feature **apart** from Fuse, but built **using** Fuse.
