### ISSUE TITLE
some time search not match

### ISSUE THREAD

**Issue by craigcosmo** [krisk/Fuse#203]
This example matches the keywords
```js
let item = {text:'car will mom'}
var fuse = new Fuse([item], option)
var result = fuse.search('car add list mom')
console.log(result) // matched
```

However below will not match keywords
```js
let item = {text:'mom love car'}
var fuse = new Fuse([item], option)
var result = fuse.search('car add list mom')
console.log(result) // []
```

My expectation: both examples should match the keywords. because sentence contains the words in keywords

**Comment by juliancoleman** [comment]
Many things can factor this. Would you mind pasting an example of your `option` variable? A few things can happen here: your `minimum character length` may be too low, `match all tokens` should be `false`, and `find all matches` should be `true` to extend searches. You may also want to check your `threshold` to make sure it's at a comfortable number.

**Comment by craigcosmo** [comment]
yes sure

```js
var searchop = {
	shouldSort: true,
	includeScore: true,
	threshold: 0.6,
	location: 0,
	distance: 100,
	maxPatternLength: 32,
	minMatchCharLength: 1,
	keys: ["text"]
};
```

**Comment by juliancoleman** [comment]
can you try this?

```js
const R = require("ramda");

const additionalOptions = {
  minMatchCharLength: 2,
  matchAllTokens: false,
  findAllMatches: true,
};

const newOpts = R.merge(searchop, additionalOptions);
```

you'll need to add Ramda using `npm` or `yarn`. I use it because it's a lot nicer than `Object.assign()` which has no semantic value. Now when you call `new Fuse(list, searchop);`, you'll want to replace `searchop` with `newOpts`.
