### ISSUE TITLE
indices for which element in array?

### ISSUE THREAD

**Issue by Noitidart** [krisk/Fuse#205]
When a match happens in an array of strings, and we want match indices, it is not clear to us which element in the array the indices belong to. For instance with this data:

```
[{
        name: "rabbit",
        alts: ["furry", "habit"]
    },
    {
        name: "bat",
        alts: ["stick", "wood"]
    }
]
```

Search for "wood" gives us:

```
[{
    "item": {
        "name": "bat",
        "alts": [
            "stick",
            "wood"
        ]
    },
    "matches": [{
        "indices": [
            [
                0,
                2
            ]
        ],
        "key": "alts"
    }],
    "score": 0.001
}]
```

We don't know if the indices are in `alts[0]` or in `alts[1]`. In this example its clear its `alts[1]` but programmatically how can this be inferred?

**Comment by Dyljyn** [comment]
I've added "friendly" to the alts for rabbit and searched on "f". There are 2 matches found but it does indeed not mention where. Without an index, this feature is sadly useless for nested arrays.

```
[
  {
    "item": {
      "name": "rabbit",
      "alts": [ "furry", "habit", "friendly" ]
    },
    "matches": [
      {
        "indices": [
          [ 0, 0 ]
        ],
        "key": "alts"
      },
      {
        "indices": [
          [ 0, 0 ]
        ],
        "key": "alts"
      }
    ]
  }
]
```

My suggestion is to add the `index` to the match object, either when an `Array` is detected or at all times and return `index: 0` for other types.

```
[
  {
    "item": {
      "name": "rabbit",
      "alts": [ "furry", "habit", "friendly" ]
    },
    "matches": [
      {
        "indices": [
          [ 0, 0 ]
        ],
        "key": "alts",
        "index": 0
      },
      {
        "indices": [
          [ 0, 0 ]
        ],
        "key": "alts",
        "index": 2
      }
    ]
  }
]
```

**Comment by Dyljyn** [comment]
I've dug into the code and believe this issue is actually closed. The matches return `arrayIndex`.

https://github.com/krisk/Fuse/blob/f68a18a9b94eedfc82dfc7d7def8a8966c9f5b33/src/index.js#L365-L368

**Comment by Noitidart** [comment]
@Dyljyn you're totally correct. I'll close this. There is a stacking issue with arrayIndex though - https://github.com/krisk/Fuse/issues/222
