### ISSUE TITLE
Only call JSON.stringfiy during format if verbose option is specified

### ISSUE THREAD

**Issue by Karankang007** [krisk/Fuse#218]
This will add a performance benefit, and prevent issue [196](https://github.com/krisk/Fuse/issues/196) in a production environment.

**Comment by Karankang007** [comment]
I have submitted a pull request to close this issue.

**Comment by aprilmay** [comment]
+1

**Comment by snowcxt** [comment]
Can you push the changes to npm?

**Comment by krisk** [comment]
Has been addressed.
