### ISSUE TITLE
Comparison with other search solution / services?

### ISSUE THREAD

**Issue by isteven** [krisk/Fuse#221]
Hi @krisk and all,

I'm currently trying to find a text search solution, and I wonder what are the pros & cons of Fuse compared with other search solutions, like Lucene, Elastic, Azure Search, etc.

To give some context, let's say: 
- The main goal is to get the most accurate fuzzy search result
- Can be easily configured / tweaked
- Database size is small to medium
- Running NodeJS
- Implementation effort is not an issue
- Money is not an issue

Also, another question: what is the string matching algorithm used in Fuse?

Any info / insight is greatly appreciated! Thanks!

**Comment by strideynet** [comment]
Elastic/Azure Search is database side, Fuse is a server-side or client-side tool.
