### ISSUE TITLE
Feature request: array of arrayIndex

### ISSUE THREAD

**Issue by Noitidart** [krisk/Fuse#223]
May we please get an array of arrayIndex, or indexs in the key - Like in this runnable code here - https://github.com/krisk/Fuse/issues/222

the `arrayIndex` is only the index for the most recent array.

**Comment by k3zi** [comment]
I prefer indices in the key as was suggested in this pull request: https://github.com/krisk/Fuse/pull/156 
Depending on the collection size, the array could get pretty funky and it would be hard to tell what index maps to what key. It would be much more cleaner to use just the key property. As to the eval comment I currently use lodash's 'get' and 'set'. They would work perfectly if the key represented the actual position with array indices in the data.

Possibly adding an option to embed the indices in the key wouldn't be such a bad idea? Not sure if that pull request is still plug-and-play with the current version, but it appeared to be only a minor addition to the code.
