### ISSUE TITLE
Does not look for exact match first

### ISSUE THREAD

**Issue by dhawalavalara** [krisk/Fuse#225]
No way in the configuration I am able to have a setting where the exact match should come first and then the rest of results. Am I missing something here?

**Comment by jessegavin** [comment]
I am having the same issue. I realize the primary use case for Fuse is a fuzzy search, but I feel like the fuzzy search should be a fall back to an exact match.

**Comment by isteven** [comment]
+1 

I'm also wondering why, because I need to use some highlighting function: I set the "includeMatches" to TRUE, and I get the indices. One work around I can think of is to highlight the longest indices index, but.. I don't know if it's reliable to show the exact match.

**Comment by alejandroiglesias** [comment]
Are you guys using the `shouldSort` option? It sorts the results by score.
