### ISSUE TITLE
feat request: Disable specific fields from weighing at all

### ISSUE THREAD

**Issue by corysimmons** [krisk/Fuse#227]
Use case: fuzzy searching phone contacts by name, phone number, and email address array of objects.

I want to search the emails, but not their labels.

Even if I do:

```js
{
  name: 'emails.label',
  weight: 0.000000000001,
}
```

..it still has weight and will put things like a `work` email label above other things.

It's a minor complaint in my use case, but I bet some others would get use out of being able to not weight specific fields.

Maybe just something like `weight: -1` could invalidate them?

**Comment by hellocosmin** [comment]
I think the whole point of `weight` is to include a field in search, but mark it as "less important".

If you don't want a field searchable, simply not have that field in your `keys` maybe?

**Comment by corysimmons** [comment]
I omitted it but it still seems to carry weight. Maybe I'm doing something wrong. I'll close and investigate and reopen if I'm onto something.
