### ISSUE TITLE
Error that needs to be fixed

### ISSUE THREAD

**Issue by nakbill** [krisk/Fuse#231]
Hi 
I am using  your project that it is very useful but i noticed a problem that needs to be fixed.
In Fuse.php file at line 226 your code is 
$averageScore = $averageScore / $scoresLen;

I noticed that sometimes the $scoresLen in my project is 0 so the the action of division prints out an error
I suggest adding the following in order to avoid this error
        if($scoresLen !=0){
            $averageScore = $averageScore / $scoresLen;
        }
Best Regards

**Comment by Sigmus** [comment]
This is a JavaScript project, not a PHP one. Are you sure you posted your issue in the correct repository?

**Comment by nakbill** [comment]
Hi again 
 
I apologies for the inconvenience. I posted in the wrong thread through wrong copy - paste
