### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [krisk/Fuse#239]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by krisk** [comment]
@mirzazulfan I would definitely be interested, and your name / desired contact info would definitely be put on the page 😄

**Comment by mirzazulfan** [comment]
Hi @krisk . I've designed a logo for your project, If you need something else i'll make it for this awesome project, If you have an idea please share with me, it would be better for me.
![fuse](https://user-images.githubusercontent.com/36124339/41517827-459edaba-72e8-11e8-9c53-9c2137bb0cc4.png)
mockup
![mockup](https://user-images.githubusercontent.com/36124339/41517834-5076f08a-72e8-11e8-8928-d9e620750c3d.png)

**Comment by scramble45** [comment]
Might just try this: [http://openlogos.org/](http://openlogos.org/)

**Comment by mirzazulfan** [comment]
Hi sir @krisk ... how about this ? i'm waiting your feedback.
![v2](https://user-images.githubusercontent.com/36124339/42136195-42e48650-7d81-11e8-8af8-e59620ebf45c.png)
