### ISSUE TITLE
Use Bitap to search approximate substring?

### ISSUE THREAD

**Issue by janga1997** [krisk/Fuse#241]
I need to use the Bitap's implementation in this module on its own, without relying on Fuse. Or with. However I can.
Is there a way to reference Bitaps' functions implemented in this library?

**Comment by janga1997** [comment]
ahh. Never Mind. Spoke too soon.

**Comment by janga1997** [comment]
Sorry, reopening as my issue wasn't solved.
Its my understanding that Bitap is primarily used to approximately search a string in a larger string, forming the basis for agrep.

But Fuse.js' functionality primarily is to find approx. matches in an array of strings.

Could I use the existing module's Fuse/Bitap functions for the approximate substring problem?

**Comment by krisk** [comment]
You would have to import the [bitap implementtion directly](https://github.com/krisk/Fuse/tree/master/src/bitap)

That is:

```javascript
let bitap = require('fuse.js/bitap')
```

or something to that effect.
