### ISSUE TITLE
minMatchCharLength doesnt work

### ISSUE THREAD

**Issue by sudarshanc** [krisk/Fuse#245]
setting minMatchCharLength to greater than 1 for eg "minMatchCharLength: 3" still gives result for single character

**Comment by kyds3k** [comment]
I'm having the same problem. I get matches as soon as I type any letter.

`const fuse = new Fuse(response, {
      keys: ['content'],
      shouldSort: true,
      threshold: 0.1,
      distance: 20000000,
      minMatchCharLength: 3
    });`
