### ISSUE TITLE
serialize index

### ISSUE THREAD

**Issue by cekvenich** [krisk/Fuse#250]
Is it possible to save an index so I don't have to build it but once?
ex:
https://lunrjs.com/guides/index_prebuilding.html

**Comment by laran** [comment]
I would like to see this as well. I have a static site. I would like to:

1. index the site locally at build time
2. simply upload the pre-built index as a static file to my server
3. load the index into the browser on the client-side
4. run search fully in the browser

Is fuse able to save an index to a file and then load an index from a file/url and search from it?

**Comment by vladimiry** [comment]
As far as I can see by looking at the source code there is no indexing process involved. Each time you execute the search it iterates through the original data portion passed to the constructor.

**Comment by baer** [comment]
I believe this was answered and closed here: https://github.com/krisk/Fuse/issues/55
