### ISSUE TITLE
Search over 32 chars gives back whole set

### ISSUE THREAD

**Issue by ErikLarsson82** [krisk/Fuse#254]
Hello, I need help how to troubleshoot this, since I can reproduce it in our codebase but not in the example code.

I have a set of 590 items. While searching up to 32 chars I get a reasonable score that approaches 0 and perhaps 4-5 results.

However, when reaching 33 chars i get the whole set as result - all 590. They also have suspiciously similar scores, like first 47 entries have 0.00009999999999999998.

I also never get 0, even when matching the string exactly.

```
//Config
{
    caseSensitive: false,
    findAllMatches: true,
    includeScore: true,
    includeMatches: true,
    shouldSort: true,
    threshold: 0.6,
    location: 0,
    distance: 100,
    maxPatternLength: 40,
    keys: [{name:'Name'}]
  }
```

I'm running version 3.2.0

I've seen issues like [#38](https://github.com/krisk/Fuse/issues/38) and [#48](https://github.com/krisk/Fuse/issues/48) is this issue perhaps reintroduced?

**Comment by sebilasse** [comment]
see also https://github.com/krisk/Fuse/issues/136
