### ISSUE TITLE
Js Fatal error if tokenSeparator is not defined.

### ISSUE THREAD

**Issue by iruzevic** [krisk/Fuse#255]
Version: 3.2.1
Browser: chrome latest
Os: osx

I'm using fuse.js in my project, everything is fine when I build it in production mode using webpack.
But when I run it via code optimisations and minification from Wp rocket cache plugin it breaks.

The problem  occurs in the console:
```js
SyntaxError: Invalid regular expression: /+/: Nothing to repeat
```

I debugged and the problem and it occures here:
```js
tokenSeparator = _ref$tokenSeparator === undefined ? / +/g : _ref$tokenSeparator,
```

I have managed to fix this by adding this to my options:
```js
tokenSeparator: '|',
```

Generally I think that the problem lies in  the spacing in this line: "/ +/g" 
Optimisation plugin removes all unnecesery white spaces that are not strings inside quotes and when it does, your plugin will not work. Please check this and provide a fix, this is a nasty bug that happends in edge cases. At lease write this inside the documentation.

tnx. If you need any more code samples please ask.

**Comment by krisk** [comment]
Good find. Taking a look.

**Comment by iruzevic** [comment]
great tnx. I have a new update. 
when I put this inside options:
```js
tokenSeparator: '|',
```

it works great on modern browsers but IE11 returns fatal error
