### ISSUE TITLE
FuseOptions<T> prevents nested key search

### ISSUE THREAD

**Issue by LiamEntrostat** [krisk/Fuse#261]
Version: 3.3.0
Type: Potential Bug

Hi,

With the recent addition of typing to FuseOptions<T> and Fuse<T> nested key search is now giving Typescript compile errors. 

The particular culprit is this line in the FuseOptions<T> interface
```typescript
keys?: (keyof T)[] | { name: keyof T; weight: number }[];
```

An example of how this was used in my application:

```typescript
  fuseOptions: FuseOptions<Template> = {
    shouldSort: true,
    threshold: 0.6,
    keys: [
      { name: 'metadata.title', weight: 0.8 },
      { name: 'metadata.category', weight: 0.1 },
      { name: 'metadata.summary', weight: 0.1 },
    ],
  };
```

Where _metadata_ was a key in template and _title_ is a key in _metadata_. This is no longer allowed by the interface. As a temporary solution I've included a ```// @ts-ignore``` above the fuseOptions definition and functionality is fully  #restored.

**Comment by krisk** [comment]
@ceymard want to take a look at this?

**Comment by ceymard** [comment]
To further explicit what I meant, the change in the code would look like this. I'm aware that there are more places to look for than just `index.js@268`, but that's just for the idea

```javascript
          // this is the original extraction of the item
          key,
          value: this.options.getFn(item, key),

          // here is what I meant. This is untested and probably wouldn't work as is, but it's just a general idea
          key: typeof key === 'function' ? key.toString() : key,
          value: typeof key === 'function' ? key(item) : this.options.getFn(item, key)
```

**Comment by ceymard** [comment]
Or, even better (and sorry for the spam), respecify a `getfn` for each key.

```typescript
  var fuse = new Fuse(my_list, {
    shouldSort: true,
    threshold: 0.6,
    keys: [
      { name: 'title', getfn: t => t.metadata.title, weight: 0.8 },
      { name: 'category', getfn: t => t.metadata.category, weight: 0.1 },
      { name: 'summary', getfn: t => t.metadata.summary, weight: 0.1 },
    ],
  });

```

**Comment by Favna** [comment]
@ceymard Hi there, I just stumbled on this exact same issue and I'm glad it has been addressed already. Would happen to have an ETA for seeing these changes in a next stable release? (Presumably 3.3.1).

For now I'm fine with using `yarn add krisk/Fuse`, however it would be nice to be working with stable versions.

**Comment by doug-a-brunner** [comment]
My workaround is to turn off type safety where I'm using nested properties, by adding a type assertion `as { name: any, weight: number }[]` to `keys`.

**Comment by ceymard** [comment]
@Favna I have no idea, I'm not a maintainer on this project - I used it for a while but I don't anymore.

I'm willing to do a PR, but I'll do so only if @krisk or another maintainer indicates that they're interested. After all, what I'm suggesting in the changes impacts the source code as well.

**Comment by camposmichel** [comment]
Hello guys
I solved the problem by declaring my variable as any

```
const myItems = [...]

let fuseOptions: any = {
      keys: [
        "description"
      ]
};

const fuse = new Fuse(myItems, fuseOptions)
let response = fuse.search('water')
```

Hope this helps

**Comment by Favna** [comment]
@camposmichel yeah that will indeed work. Personally I try to avoid `any. The whole point of choosing to use TypeScript over vanilla JavaScript is to gain Type Safety and using `any` goes against that very principle as you're basically saying "this thing can be anything and I don't really care what it is".

Admittedly it certainly has it uses however so it's not like it should never be used.

**Comment by camposmichel** [comment]
@Favna I agree! But it was the way I found it to resolve quickly for me

**Comment by Favna** [comment]
Just to share my personal solution:

1. Use Ceymard's fork (the `individual-getfn` branch to be exact, `yarn add ceymard/fuse#individual-getfn`)

2. Define types and use them as listed below:

---

In the file where we search:

```ts
const itemOptions: Fuse.FuseOptions<UnionPokeItem> = {
	shouldSort: true,
	keys: [
		{ name: 'alias', getfn: t => t.alias, weight: 1 },
		{ name: 'item', getfn: t => t.item, weight: 1 },
		{ name: 'id', getfn: t => t.id, weight: 1 },
		{ name: 'name', getfn: t => t.name, weight: 1 }
	],
	location: 0,
	distance: 100,
	threshold: 0.3,
	maxPatternLength: 32,
	minMatchCharLength: 1,
};
const aliasFuse = new Fuse(ItemAliases, itemOptions); // automatically inferred as Fuse<IPokeItemAliases>
const itemFuse = new Fuse(BattleItems, itemOptions); // automatically inferred as Fuse<IPokeItem>
const aliasSearch = aliasFuse.search(item); // automatically inferred as IPokeItemAliases[]
const itemSearch = aliasSearch.length ? itemFuse.search(aliasSearch[0].item) :  itemFuse.search(item); // automatically inferred as IPokeItem[]
```

The data file that is being searched:
```ts
import { IPokeItem } from '../../components';

export const BattleItems: IPokeItem[] = [
    {
        id: 'abomasite',
        name: 'Abomasite',
        num: 674,
        gen: 6,
        desc: 'If held by an Abomasnow, this item allows it to Mega Evolve in battle.',
    },
    {
        id: 'absolite',
        name: 'Absolite',
        num: 677,
        gen: 6,
        desc: 'If held by an Absol, this item allows it to Mega Evolve in battle.',
    },
...
];

// and the aliases:

export const ItemAliases: IPokeItemAliases[] = [
    { alias: 'assvest', item: 'Assault Vest' },
    { alias: 'av', item: 'Assault Vest' },
    { alias: 'band', item: 'Choice Band' },
    { alias: 'cb', item: 'Choice Band' },
...
];
```

The interfaces and types being used:
```ts
interface IPokeAlias {
    alias: string;
}

export interface IPokeItemAliases extends IPokeAlias {
    item: string;
}

export interface IPokeItem {
    id: string;
    name: string;
    desc: string;
    gen: number;
    num: number;
    shortDesc?: string;
}

export type UnionPokeItem = IPokeItem & IPokeItemAliases;

**Comment by Favna** [comment]
Updating the issue with the notice that this should (finally) be fixed if the here above referenced PR gets merged.

**Comment by mmajko** [comment]
Can someone explain how this is solved? The example code for TypeScript at https://fusejs.io is a complete nonsense. Tests aren't readable enough to be used as example for using nested keys and TypeScript together.

**Would someone be so kind and add the missing examples** of using nested keys (with weights preferably) in the TypeScript example on the website?

**Comment by Favna** [comment]
@mmajko I can replicate the issue and it is something I overlooked when adding to the docs and improving the typings. That said, this is exclusively a typings thing so while I need time to look into the issue it should be noted that in the meantime you can still use it by adding `// @ts-ignore` above the `keys` line.

Confirmation of issue:
![image](https://user-images.githubusercontent.com/4019718/58346142-6f3dfa80-7e5a-11e9-990b-809c5950eca2.png)

**Comment by Favna** [comment]
@mmajko #309 and #310 have been created to cover deep nested keys. Furthermore https://github.com/piotrwitek/utility-types/issues/85 has been created to provide an even better solution, although that won't be any near-future addition likely.
