### ISSUE TITLE
How can I know which key my search results came from?

### ISSUE THREAD

**Issue by SoYoung210** [krisk/Fuse#267]
I would appreciate your understanding that my English is not great.

I have data 

```javascript
const mydata = [
  {
     "title" : "Blueberry Dream",
    "user" : {
         "username" : "kang"
      }
   },
   {
     "title" : "Swang",
    "user" : {
         "username" : "blueberry"
      }
    }
]
```

if i search keyword : `blueberry`
the result would be `mydata[0] and mydata[1]` 

`mydata[0]` is came from  **title** , `mydata[1]` is came from **username**

can i know this? 
because, I want to sort the results like this. 
> Artists, Title, Lyrics ... 

![image](https://user-images.githubusercontent.com/18658235/48633050-d4c1b200-ea05-11e8-9d08-01a19a0a8caf.png)

**Comment by FBNitro** [comment]
includeMatches: true

**Comment by andru** [comment]
Add `includeMatches: true` to the options.  The `key` property of each entry in the `match` array shows the keypath matched against.
