### ISSUE TITLE
maxPatternLength does not error in 3.3.0

### ISSUE THREAD

**Issue by FBNitro** [krisk/Fuse#269]
I'm on Fusejs 3.3.0, and I've noticed that the maxPatternLength isn't doing anything.  My length is the set to 32.  But when I put in term that are longer, it will still run the search, whereas in 3.2.1 it would error stating that the "Pattern length is too long".

If I navigate to: http://fusejs.io/ it appears to be running version 3.2.1.  If I leave the maxPatternLength to be 32 and search for: 
"oldoldoldoldoldoldoldoldoldoldoldold" (36 chars) I get the above exception text in the result box.

If I use my code which is on version 3.3.0 has the maxPatternLength set to 32, and search for the same term ("oldoldoldoldoldoldoldoldoldoldoldold") it returns a match instead of throwing the exception.

**Comment by krisk** [comment]
Will take a look. Thanks for flagging!
