### ISSUE TITLE
Add install instructions to site

### ISSUE THREAD

**Issue by fabiosantoscode** [krisk/Fuse#276]
Greetings! I was trying to use fuse.js and had to look at the package.json to find its name.

Maybe it would be an improvement if there was an `npm install fuse.js` note in the site?

Just my two cents.

Thanks for reading!

**Comment by ryanhliu** [comment]
I agree that this would be helpful for people to quick start fuse. In my opinion, just a small import/require statement somewhere in the `# Examples` section of the webpage would suffice

**Comment by fabiosantoscode** [comment]
Why not both? :)

**Comment by krisk** [comment]
Don't the install directions within https://fusejs.io/ suffice? 😄
