### ISSUE TITLE
Update the search without resubmitting the search query

### ISSUE THREAD

**Issue by steve-cahn** [krisk/Fuse#278]
Is there a way to update the search results? For example, calling `fuseSearch.update();`

The benefit of that, is when an option gets changed, such as `fuzeSearch.options.keys = ['anotherKey']`, then the search result updates automatically.

**Comment by heyimalex** [comment]
This doesn't make sense to me: Fuse is purely pull-based so you _always_ need to call `search` to get results. There is no "update automatically".
