### ISSUE TITLE
Release 3.3.1 breaks application on production

### ISSUE THREAD

**Issue by Saifadin** [krisk/Fuse#280]
The latest release of Fuse `3.3.1` breaks our production application, on `new Fuse`.

Downgrading to 3.3.0 fixed this issue and our application is running again.

I created this [gist](https://gist.github.com/Saifadin/66fd49bf8e94f7c89d150a36a7645da3#file-error-js-L336) that has the prettified minified code out of chrome. The error happens in line 336 as highlighted.

**Comment by krisk** [comment]
Thanks @Saifadin - will be looking at this in the evening. Will update this thread.

**Comment by krisk** [comment]
@Saifadin, do you have sample code which surfaces this issue?
