### ISSUE TITLE
Add support for search operators like "title:man"

### ISSUE THREAD

**Issue by ProLoser** [krisk/Fuse#290]
I would like to be able to filter or search specific properties using search operators frequently found in google search and gmail. I would like to be able to do things like `-{someexpression}` or `tag:someTag` or other ways to search specific properties instead of just general fuzzy searching.

**Comment by VamsiDharmaji** [comment]
@krisk any update on the estimated or plan to release this feature. We need this feature for one of requirements. Wanted get some insight nf the priority and plan .
