### ISSUE TITLE
Error while uglifying (Unexpected token: operator (>)) using fuse.js 3.4.3

### ISSUE THREAD

**Issue by BogdanDenis** [krisk/Fuse#293]
I'd like to report an issue with the latest version (3.4.3)

After updating to the latest version my build started failing on minification step.

Steps to reproduce:

1) Use the following package.json
```
{
  "name": "fusetest",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "fuse.js": "3.4.3"
  },
  "devDependencies": {
    "uglifyjs-webpack-plugin": "^2.1.2",
    "webpack": "^4.29.6"
  }
}
```

And index.js
```
import { Fuse } from 'fuse.js';
```
Run
2) ```npm install```
3) ```npm run build```

Verify output:
```
Hash: 7accaba6ecc9b73295f3
Version: webpack 4.29.0
Time: 574ms
Built at: 03/07/2019 1:18:41 PM
 1 asset
Entrypoint main = main.js
[0] ./index.js 31 bytes {0} [built]
    + 1 hidden module

ERROR in main.js from UglifyJs
Unexpected token: operator (>) [main.js:109,1019]
```

Then try changing version of fuse.js to 3.4.2 in package.json

4) ```rm -rf ./node_modules/ && rm package-lock.json && npm i```
5) ```npm run build```

Verify output:
```
Hash: e4077f215de091ea71fc
Version: webpack 4.29.0
Time: 940ms
Built at: 03/07/2019 1:25:03 PM
  Asset      Size  Chunks             Chunk Names
main.js  14.1 KiB       0  [emitted]  main
Entrypoint main = main.js
[0] ./index.js 31 bytes {0} [built]
    + 1 hidden module
```

Tried with uglifyjs-webpack-plugin using webpack and also grunt-contrib-uglify. Both fail.

Could you please look into this issue?
Thanks!

**Comment by timbomckay** [comment]
Based on the [v3.4.3 changes](https://github.com/krisk/Fuse/commit/fb062da4c3a7b23c848e1c30d61b1cd8e65513b3) it looks like removing `node` from the `node_js` list is the only change that could've impacted this. All the other changes are just formatting.

**Comment by krisk** [comment]
Taking a look!
