### ISSUE TITLE
Unable to load fuse.js with webpack on IE10

### ISSUE THREAD

**Issue by maritaria** [krisk/Fuse#296]
Importing fuse.js into a project compiled with webpack results in a syntax exception for IE10.
This is caused by usage of lambda's. Also I noticed the compiled output has code that uses the keyword const which IE10 cannot parse either.

This could be solved by adjusting the babel configuration to add transformers which compile to code usable by IE10.

PS: I don't like that I have to support IE10 for my project :(

**Comment by krisk** [comment]
I think this should be resolved with the latest version. No?

**Comment by krisk** [comment]
@maritaria is this working for you on the latest version?
