### ISSUE TITLE
Threshold is not ignored when Tokenize is set to true. (Doc says it should)

### ISSUE THREAD

**Issue by ziadrida** [krisk/Fuse#298]
Use standard example, search for "Lost" and you will get one record back if you use the following settings:
var options = {
  shouldSort: true,
  tokenize: true,
  matchAllTokens: true,
  includeScore: true,
  threshold: 1,
  location: 0,
  distance: 100,
  maxPatternLength: 32,
  minMatchCharLength: 1,
  keys: [
    "title",
    "author.firstName"
  ]
};
var fuse = new Fuse(list, options); // "list" is the item array
var result = fuse.search("Lost");

Next change threshold to 1 then to zero and the result will change! It should not.

**Comment by insulatir** [comment]
I found that fusejs.io says 
"the threshold, distance, and location are inconsequential for individual tokens, and are thus ignored." 
but src/index.js says 
"the `threshold`, `distance`, and `location` are inconsequential for individual tokens."
