### ISSUE TITLE
Search matching improvement, split search string by space

### ISSUE THREAD

**Issue by alexgrozav** [krisk/Fuse#302]
Hey! First of all, amazing work on Fuse.js. I've moved my search functions from Algolia to a completely front end solution using Fuse.

Comparing Fuse and Algolia, I've encountered a few differences which I believe could be easily improved.

Let's take the following data set:
~~~
[
  { title: 'Alert', subtitle: 'Variants' },
  { title: 'Button', subtitle: 'Sizes' }
];
~~~

Searching using the following search string: `Alert Variants` or `Button Sizes` will yield an empty results array.

Algolia would split the search string and identify the two keywords in the two different search keys, `title` and `subtitle`. 

I know the current behaviour might be intended, but it would be nice to add an option to split the search string by the space separator and use both words individually.

**Comment by KWierso** [comment]
I'm hitting a similar issue. I have a data set like this:
```
[
  {name: 'Android web platform test', symbol: 'wpt'},
  {name: 'Linux web platform test', symbol: 'wpt'},
  {name: 'Android some other test', symbol: 'se'}
]
```

For the search options, I have `keys: ['name', 'symbol'], tokenize: true, matchAllTokens: true`

I'd like to be able to have the first item in the dataset returned if I search for `android wpt`, but it returns an empty array.

**Comment by rastalamm** [comment]
Possible duplicate of issue #235
