### ISSUE TITLE
Match the entire word

### ISSUE THREAD

**Issue by josehernandezv** [krisk/Fuse#311]
Hi, I have a little problem, I am trying to search from a list of lessons which have a structure like this one.
`
{
    ....,
    minutes: 10,
    instructorId: '5bc343asvdaf
}
`
when I try to search for lessons of 5 minutes I also get unexpected results because the instructorId begins with '5', I need to search for both so I can't exclude de instructorId from the keys, but is there any way to just get the results that matches the entire word?

**Comment by MarcelloTheArcane** [comment]
Could you add a weight to the minutes field? [https://fusejs.io/#weighted-search](https://fusejs.io/#weighted-search)
