### ISSUE TITLE
Allow functions as keys

### ISSUE THREAD

**Issue by matt-tingen** [krisk/Fuse#313]
#261 discusses the issues with the type definitions with nested keys, but the resolution is not type safe. To make it type safe, functions could be allowed as keys (e.g. `keys: [item => item.foo.bar]`) as described by @ceymard. 

This also allows for simplifying the case of searching derived fields such as full name e.g. ``item => `${item.firstName} ${item.lastName}` `` which faces issues similar to those described in #302. Obviously, an intermediate object could be used for this, but that seems excessive compared to having functional keys to search.

I'd be happy to implement a PR for this if the behavior is desired.

**Comment by krisk** [comment]
This sounds interesting, @matt-tingen :)

**Comment by matt-tingen** [comment]
After messing around with it some, I ended up on the same solution as @ceymard which can be summed up with the following:

```ts
  export type FuseKey<T> =
    | keyof T
    | { name: keyof T; weight: number }
    | { name: string, weight?: number, getFn: (obj: T) => string }
```

We can't trivially use a bare function as the key because of how the `weights` are stored. There's a couple of techniques involving `Map`s which could work around this, but that would increase the minimum browser/node version which makes them non-starters in my opinion.

Unless @ceymard is still interested in this change and wants to champion it, I'll pull in their changes, update it, and make a PR later this weekend.

**Comment by ceymard** [comment]
I don't use this library anymore for now, feel free to go ahead.

Thank you.

Le ven. 21 juin 2019 à 22:39, Matt Tingen <notifications@github.com> a
écrit :
