### ISSUE TITLE
HTML to Fuse.JS converter

### ISSUE THREAD

**Issue by simonelnahas** [krisk/Fuse#317]
Would it make sence to be able to input a HTML document to Fuse.js format using the Metadata provided in the HTML?

**Comment by lopugit** [comment]
do you mean converting dom to json or just plaintext?

**Comment by SimonElNahasChristensen** [comment]
weighing a H1 over a H2 and so on

**Comment by upandfine** [comment]
I'm interested, too. Would be enormously helpful to be able to use fuse.js on smaller, static pages.
