### ISSUE TITLE
Search in Array<String> returns indexes instead of items

### ISSUE THREAD

**Issue by isnifer** [krisk/Fuse#319]
Hello, I used Live Demo page to check a search in flat array:
```js
const list = [
  { value: "85626400800" },
  { value: "81323902061" },
  { value: "8079842032" },
  { value: "7825731309" },
  { value: "9492224473" },
  { value: "81323902062" },
  { value: "71509915863" },
  { value: "84718105204" },
  { value: "81323902013" },
  { value: "80487910890" },
]

var options = {
  shouldSort: true,
  tokenize: true,
  matchAllTokens: true,
  threshold: 0,
  location: 0,
  distance: 0,
  maxPatternLength: 32,
  minMatchCharLength: 1,
  keys: [
    "value"
  ]
};
var fuse = new Fuse(list, options); // "list" is the item array
var result = fuse.search("804");

/* SEARCH RESULTS */
[
  {
    "value": "80487910890"
  }
]
```

#### But when I try to search by flat list it returns indexes instead of items
```js
const list =  [
  "85626400800",
  "81323902061",
  "8079842032",
  "7825731309",
  "9492224473",
  "81323902062",
  "71509915863",
  "84718105204",
  "81323902013",
  "80487910890",
]

// Options without a "key" property
var options = {
  shouldSort: true,
  tokenize: true,
  matchAllTokens: true,
  threshold: 0,
  location: 0,
  distance: 0,
  maxPatternLength: 32,
  minMatchCharLength: 1,
};
var fuse = new Fuse(list, options); // "list" is the item array
var result = fuse.search("804");

/* SEARCH RESULTS */
[
  9
]
```

Looks like issue is here — https://github.com/krisk/Fuse/blob/master/src/index.js#L136
Why is that?

**Comment by heyimalex** [comment]
It's probably just a weird decision that was made a long time ago. Not so hard to get around:

```js
// Fuse has a quirk where, when the input is an array of strings instead of
// objects, it only returns the index to each result. That means we need to
// re-map those indexes to the original list items after the search completes.
var result = fuse.search("804").map(i => list[i]);
```

**Comment by isnifer** [comment]
@heyimalex it's ok for small lists. But one more `map` over 1k+ items can be slow.

**Comment by heyimalex** [comment]
@isnifer Is that something you've measured? I think whatever time you save will be a rounding error compared to the internals of fuse. I just tried in node and it was sub 0.1ms for 10k iterations.

I don't disagree with you fwiw, but I'm also not a maintainer on this lib!

**Comment by goliney** [comment]
Even though it might be a weird decision from a long time ago and has a workaround, the typings still define `items` as an array of strings, not an array of indices which it in fact is:

```js
const list = ['aaa', 'bbb'];
// result is FuseResult<string>[], but should be FuseResult<number>[]
const result = new Fuse(list, {}).search('a'); 
```

https://github.com/krisk/Fuse/blob/fe1ff83645a55b6ea9f9488893a32495c132529f/dist/fuse.d.ts#L21-L25

**Comment by heyimalex** [comment]
I wonder if it's possible to type correctly? Maybe with conditional types.

```ts
export interface FuseResult<T> {
    item: T extends string ? number : T;
    matches?: any;
    score?: number;
  }
```

**Comment by scallaway** [comment]
Would be really great to have this addressed at some point - mapping over the filtered list just to return the actual values is an unnecessary step. Especially given the typings indicate otherwise (as pointed out by @goliney).

**Comment by sharifme04** [comment]
how will do filter without transforming this array of arrays first value array[1,] ? 
Here is my array exaxmple : [ ["1 A-Bauchemie", "Am Bürohochhaus 2-4, Potsdam", " info@1a-bauchemie.de"]
["Ab 1986 Atlas-Fliesenbau", "Albrechtstr. 15c 12167 Berlin-Steglitz", "info@atlas-fliesen.de"]
 ["Alpha Baustoffvertrieb", "Mariendorfer Damm 337 12107 Berlin-Mariendorf", "info@alpha-baustoffvertrieb.de"]]
