### ISSUE TITLE
Random results from search query

### ISSUE THREAD

**Issue by AymanxD** [krisk/Fuse#320]
I'm attempting to do to a basic query with a dictionary of over 1000 merchants. For many of my queries, I get results which just seem to be wrong. 

Query: ``` BIKKURIJAPANESE RESTAURATORONTO ON ```

My options:
```
var options = {
  shouldSort: true,
  includeScore: true,
  includeMatches: true,
  threshold: 0.03,
  location: 0,
  distance: 10,
  maxPatternLength: 100,
  minMatchCharLength: 8,
  keys: [
    "merchant_name"
  ]
};
```
My example dictionary: 
```
[
    {
    "merchant_name": "FINN AIR",
    "category_code": 5260,
    "master_code": "Business_Expense"
  },
  {
    "merchant_name": "AER LINGUS",
    "category_code": 5260,
    "master_code": "Business_Expense"


  },
  {
    "merchant_name": "AIR LANKA",
    "category_code": 5260,
    "master_code": "Business_Expense"
  }
 ]
```

My result: 
```
[
  {
    "item": {
      "merchant_name": "FINN AIR",
      "category_code": 5260,
      "master_code": "Business_Expense"
    },
    "matches": [],
    "score": 0.029411764705882353
  },
  {
    "item": {
      "merchant_name": "AIR LANKA",
      "category_code": 5260,
      "master_code": "Business_Expense"
    },
    "matches": [],
    "score": 0.029411764705882353
  }
]
```

Why is my query matching ```FINN AIR``` if they do not seem to be similar at all? How can this be with a high threshold of 0.03? Lastly, are minimum character length, location, and threshold being overwritten by threshold? If not what role are they playing in this case?

Thanks for your help!

**Comment by novumcoder** [comment]
Same problem here. Fuse.JS alwasy produces wrong results, does not match at all. I simply follow one of the examples having an array of objects.

**Comment by lukas1994** [comment]
Having similar issues; cc @krisk

**Comment by kittaakos** [comment]
> Query: `BIKKURIJAPANESE RESTAURATORONTO ON`

`"BIKKURIJAPANESE RESTAURATORONTO ON".length === 34`

[Search over 32 chars gives back whole set ](https://github.com/krisk/Fuse/issues/254) issue?

**Comment by cshoredaniel** [comment]
This lack a great deal of information.

1) Please read the new README which includes pointers to writing a good 
issue

2) You haven't specified what data set you are searching in.

3) Code please.

**Comment by cshoredaniel** [comment]
Oops sorry for the noise.  I though this was  new issue but I see it's a 
comment on an old (detailed) one.

**Comment by krisk** [comment]
Is this still a problem in the latest version?

**Comment by krisk** [comment]
Close this issue, as there hasn't been any update.
