### ISSUE TITLE
Patch release (3.4.6) request?

### ISSUE THREAD

**Issue by cbrock** [krisk/Fuse#337]
Thank you, @krisk, for all your work on Fuse!

In light of 5e8e2ccb302f1eeacad1b78b5ae70722542aa008 and b1fe7cc67b06c9bf45eee11035fe7465e5fff7b3 landing in `master` recently, is it possible to cut a new patch release of Fuse?

Thank you and apologies if this isn't the appropriate venue for this type of request.

**Comment by krisk** [comment]
Pardon the hiatus. Yes, I'll be releasing a new version this evening. Will update this thread :)
