### ISSUE TITLE
Sort and pagination

### ISSUE THREAD

**Issue by lludol** [krisk/Fuse#339]
Hello,

I really like Fuse it's so easy to use but there two things that I don't know how to do it :
1) Sorting
Let's imagine I want to sort my results by Firstname DESC how can I do that?

2) Pagination
Ok there is a limit (by the way where the documentation about it) but how can I get a pagination from it?
I need to get : page, pages, total and also be able to go to the next page.

Thank you.

**Comment by heyimalex** [comment]
```js
const results = executeMySearch();
results.sort((a, b) => b.name.localeCompare(a.name));
const resultsPerPage = 50;
const pages = [];
for (let i = 0; i < results.length; i += resultsPerPage) {
   pages.push(results.slice(i,i+resultsPerPage));
}
```

**Comment by lludol** [comment]
Thanks, at the end I did that with lodash

But it would be great if it was in the lib directly

**Comment by krisk** [comment]
@lludol  - There's the `sortFn` option , which by default sorts by score. You can override it:

```js
let fuse = new Fuse(items, {
  sortFn: (a, b) => { /* your comparison check */ }
  /* rest of the options */
})
```

**Comment by krisk** [comment]
Regarding pagination - I think it should be handled outside of Fuse.js.
