### ISSUE TITLE
weight is not "heavy" enough

### ISSUE THREAD

**Issue by zsolt-dev** [krisk/Fuse#341]
how to reproduce:

1. open the demo:
https://fusejs.io

2. change the firstName of the first authors book to this:
```
firstName: "Codenar",
```

3. enter this as keys:
```
[{
    name: 'title',
    weight: 0.7
  }, {
    name: 'author.firstName',
    weight: 0.3
}]
                            
```

The first result will be "Old Man's War" which is not expected, since the title has much higher weight. It seems like the location of the keyword within the field (if its the first, second or third word...) is more important than the weight.

Is there something I could do about it?

**Comment by kurozael** [comment]
I would also like to know the answer to this 👍

**Comment by faizanu94** [comment]
@zsolt-dev what keyword to search?

**Comment by zsolt-dev** [comment]
sorry for incomplete steps.

Keyword is: "code"

results:
```
[
  {
    "title": "Old Man's War",
    "author": {
      "firstName": "Codenar",
      "lastName": "Scalzi"
    }
  },
  {
    "title": "The Code of the Wooster",
    "author": {
      "firstName": "P.D",
      "lastName": "Woodhouse"
    }
  },
```

I would expect the second result to be first since the weight  of the title is much higher number than  the weight of the authors name

**Comment by krisk** [comment]
Part of the issue that the score for `"author.firstName":"Codenar"` ranks higher than  `"title":"The Code of the Wooster"` by quite a very large margin, even without the weight applied. With the weight applied  `"Codenar"` still ranks higher.  

**Before** weight is applied:
```javascript
"Codenar" -> score = 0.001
"The Code of the Wooster" -> score = 0.04
```

**After** the weight is applied:
```javascript
"Codenar" -> score = 0.0007
"The Code of the Wooster" -> score = 0.012
```

Ultimately, `0.0007`  ranks higher than `0.012`. 

Perhaps I need to rethink the entire weighting system.

**Comment by krisk** [comment]
Just fixed this (hopefully).
