### ISSUE TITLE
'tokenize' issue

### ISSUE THREAD

**Issue by shepitchakpavlo** [krisk/Fuse#342]
Problem: When I have a search string "Desk 1" I get the expected result. But When I continue typing "1 1 1 1 1 1...." to the end of the search string, I get the same result. If I type "Desk 1 1 1 1 1 1 1 1..." I expect an empty result.

input data:
`[{
      "name": "Desks group 1",
      "floorName": "Floor 1",
      "buildingName": "R&D office",
      "siteName": "name site"
}]`
config: 
`{
  tokenize: true,
  matchAllTokens: true,
  findAllMatches: true,
  includeScore: true,
  includeMatches: true,
  threshold: 0,
  location: 0,
  distance: 100,
  maxPatternLength: 31,
  minMatchCharLength: 0,
  keys: [
    "name",
    "floorName",
    "buildingName",
    "siteName"
  ]
}`

**Comment by krisk** [comment]
Tokenization no longer exists as of the latest version(s).
