### ISSUE TITLE
weight: 1 does not act as expected

### ISSUE THREAD

**Issue by maszaa** [krisk/Fuse#344]
Per code, weight is allowed to be `0 < weight <= 1`.

Per documentation, key with higher weight is favored over a key with lower one: https://fusejs.io/#weighted-search

So one would expect a key with `weight: 1` to be favored the most as the weight is set to the highest possible value.

So with following keys
```js
keys: [
    {name: "title", weight: 0.5},
    {name: "author", weight: 1}
  ]
};
```
and with following items
```js
var items = [
  {author: "Donald Duck", title: "Mickey Mouse"},
  {author: "Mickey Mouse", title: "Donald Duck"}
];
```

The object at `items[0]` should be the first result of `fuse.search("Donald")` but it's not, `items[1]` is.

If I set the `author` `weight` to, let's say, `0.999`, `items[0]` is the first result.

Demo: https://runkit.com/embed/j4q5u5mm0715

The problem probably lies where the weight is transformed to the actual score multiplier: https://github.com/krisk/Fuse/blob/master/src/index.js#L159 because when weight is 1 the following line evaluates to `(1 - 1) || 1` ==> `0 || 1` ==> `1`.

To fix this problem I think there are couple of options:

1. State in the documentation that `weight: 1` is a special weight which means that no weighting is applied to the key in question.
2. Allow weight to be only in range `0 < weight < 1`.
3. Threat `weight: 1` as a special, very heavy weight. e.g.
```js
if (weight === 1) {
  weight = Number.EPSILON;
}
```

**Comment by maszaa** [comment]
Test case: https://github.com/maszaa/Fuse/commit/0510eb720a45d584e03e3567687a971b79de384c

I could create a PR with 2. or 3. implemented or the test modified to pass (option 1.).

**Comment by krisk** [comment]
The latest version of Fuse should account for this.
