### ISSUE TITLE
Find similar documents

### ISSUE THREAD

**Issue by stupkad** [krisk/Fuse#345]
Hi there,

I am lookig for a fulltext search library for a private wiki and found this library (but did not use it yet). Is there a way to find similar documents, like discussed in this article?

https://stackoverflow.com/questions/7657673/how-to-find-similar-documents

Regards,
Dietmar

**Comment by krisk** [comment]
Similar documents? Based on title? content? 

The way I would do it is probably via [tl-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf), and not via this library. 

Basically, I'd leverage **tl-idf** to determine the number of terms the documents have in common. The higher the number, the more likely they're very closely-related documents.
