### ISSUE TITLE
What are the default values for options object?

### ISSUE THREAD

**Issue by whyboris** [krisk/Fuse#349]
From reading the [documentation](https://fusejs.io/) it's not at all clear what the defaults are for the library if you do not provide them.

Could we get a clear list?

From the _code_ it looks like we have these:

| property | default |
| -------- | ------- |
| location           | 0 |
| distance           | 100 |
| threshold          | 0.6 |
| maxPatternLength   | 32  |
| caseSensitive      | false |
| tokenSeparator     | / +/g |
| findAllMatches     | false |
| minMatchCharLength | 1 |
| id                 | null  |
| keys               | []  |
| shouldSort         | true  |
| getFn              | deepValue |
| sortFn             | (a, b) |> (a.score - b.score) |
| tokenize           | false |
| matchAllTokens     | false |
| includeMatches     | false |
| includeScore       | false |
| verbose            | false  |

```
location = 0,
distance = 100,
threshold = 0.6,
maxPatternLength = 32,
caseSensitive = false,
tokenSeparator = / +/g,
findAllMatches = false,
minMatchCharLength = 1,
id = null,
keys = [],
shouldSort = true,
getFn = deepValue,
sortFn = (a, b) => (a.score - b.score),
tokenize = false,
matchAllTokens = false,
includeMatches = false,
includeScore = false,
verbose = false
```
Ref: https://github.com/krisk/Fuse/blob/master/src/index.js#L7

Would a PR for `gh-pages` branch be welcome _and_ merged in if I make one?
https://github.com/krisk/Fuse/blob/gh-pages/index.html#L376

**Comment by whyboris** [comment]
@krisk - I'm happy to create a PR, but don't want to spend time unless it's likely to be merged in.

If you think having a nice table / chart of default values would be an improvement, please comment where you'd like it to live, on `gh-pages` or README.md or elsewhere 🤝

**Comment by MetalCar** [comment]
Can confirm that the default value for `shouldSort` is `true`. Please update it in the documentation @krisk :)

**Comment by krisk** [comment]
`deepValue` => `get` in the latest version

**Comment by whyboris** [comment]
Would a PR that includes this table of defaults to be merged into the `gh-pages` branch be welcome and merged in if I make one?

**Comment by krisk** [comment]
@whyboris instead of a separate table, I think it’d be good to simply have the defaults inline with the option name. I’m going to be updating these this week as I’m already pushing subsequent versions.

**Comment by whyboris** [comment]
I wonder if, given that there are so many options now, it would also make sense to alphabetize them (for ease of finding) 🤔
