### ISSUE TITLE
Different scores for the same match

### ISSUE THREAD

**Issue by koreno** [krisk/Fuse#352]
This seems like a bug - the two titles match identically to the search string, yet they produce quite a different score. 
![image](https://user-images.githubusercontent.com/180551/73309968-fcc4bc00-422b-11ea-96a1-b5da77c9a0f1.png)

**Comment by krisk** [comment]
They're not the same though.  The words "Artist" and "Symbol" are also checked, and each of those, given`tokenize:true` will yield different scores.
