### ISSUE TITLE
r.search is not a function in v5.0.6-beta when using ExtendedSearch

### ISSUE THREAD

**Issue by SOTL** [krisk/Fuse#363]
If you install v5.0.6-beta and try to use the ExtendedSearch via the option `useExtendedSearch`, searching something results in a "r.search is not a function" error.
  
This is also observable on the demo page https://fusejs.io/ when you click the Extended Search checkbox.

**Comment by krisk** [comment]
Thanks for flagging. Just fixed it, and have updated the site.
