### ISSUE TITLE
White space not acting as AND operator on extended search

### ISSUE THREAD

**Issue by SOTL** [krisk/Fuse#364]
When using the extended search, searching for "John Doe" with a threshold of 0, i would expect to match ```{ firstName: 'John', lastName: 'Doe' }```. This isn't the case tho, it matches nothing.
 
Also i think the extended search operator discriptions for fuzzy-match and exact-match got switched up.

![image](https://user-images.githubusercontent.com/25790948/77087936-0389d700-6a04-11ea-9672-94a9820d70d2.png)

**Comment by krisk** [comment]
A threshold of zero means it has it be an exact match. "John Doe" is not an exact match for either  `firstName: 'John'` or `lastName: 'Doe'`. The entry it is searching in *has* to be "John Doe".

> Also I think the extended search operator descriptions for fuzzy-match and exact-match got switched up.

No. They're correct 😄

**Comment by SOTL** [comment]
Okay so i misunderstood how this works. Thanks for clarifying! I fiddled around with tokenizing on lower versions of fuse.js but i couln't get the result i was hoping for. Is there a way to configure fuse so it searches for each word in the search string, separated by white space, as an own "query" / token?
