### ISSUE TITLE
Fresh List Per Search

### ISSUE THREAD

**Issue by bswank** [krisk/Fuse#371]
Hey, thanks for all the great work!

I am filtering an array of users which gets updated by a drag & drop interface between searches. When I remove a user from the list and then start a fresh search, the list returns to its original state since that’s what I passed into the `new Fuse()` call.

Since my list is updated between searches, I’m thinking I’ll have to call `new Fuse()` with my updated list prior to every search (on every `@input` call). Is there a better way?

**Comment by krisk** [comment]
You could create a new instance, or can also call the instance’s `setCollection `

**Comment by bswank** [comment]
Thank you, @krisk! This is exactly what I was looking for.

On another note, I may be totally missing something, but I was having a hard time finding any docs related to this even after knowing it existed and searching for it directly.
