### ISSUE TITLE
Typescript definitions incorrect

### ISSUE THREAD

**Issue by Oblarg** [krisk/Fuse#372]
When using fuse with an `options` object that specifies only keys, the type definition suggests the return type ought to be the same as the type of the elements in the searched array.  However, this is not the case - the return type is a wrapper object with an `item` property (containing the item) and a `refIndex` property (which is a number).

Setting `includeScore` to true results in a correct type definition.

**Comment by krisk** [comment]
Thus is true, and a problem. I will fix it before end of week.

**Comment by krisk** [comment]
Can you share example code?

**Comment by Oblarg** [comment]
```typescript
import Fuse from "fuse.js";

interface Foo {
  bar: string;
  baz: number;
}

const foos: Foo[] = [
  { bar: 'Hello', baz: 1 },
  { bar: 'Goodbye', baz: 2 },
];

export const test = () => {
  const fuse = new Fuse(foos, {keys: ["bar"]});

  // Compiles fine, errors at runtime
  fuse.search("Hello").forEach(foo => console.log(foo.bar.length));
};```

**Comment by Oblarg** [comment]
It is also worth noting that the examples on the main page (below the interactive example) appear to be incorrect for the same reason.

**Comment by krisk** [comment]
Perhaps I am misunderstanding something, but the type definition is this:

```typescript
export type FuseResult<T> = {
  item: T
  refIndex: number
  score?: number
  matches?: ReadonlyArray<FuseResultMatch>
}
```

Your code should be changed to this:

```js
fuse.search("Hello").forEach(foo => console.log(foo.item.bar.length));
```

No compile or runtime errors when I do that.

**Comment by Oblarg** [comment]
That generates a compiler error, for me (the `item` prop is not present on the type).  If I suppress the error, it works correctly.

**Comment by krisk** [comment]
Got it. This was fixed as of v5. Those type definitions do not exist in the latest version. Could you upgrade and check?

**Comment by Oblarg** [comment]
That's strange; according to my `package.json`, my version is 5.0.7.

**Comment by krisk** [comment]
Sorry, meant v5.0.9+

**Comment by Oblarg** [comment]
Updating to 5.0.9 fixed the issue.  Thanks!
