### ISSUE TITLE
The extended search should be extended with a syntax to search literal phrases

### ISSUE THREAD

**Issue by isiahmeadows** [krisk/Fuse#376]
Basically, there should be some sort of quoting or escaping mechanism for spaces.

Not a dupe of #206 as this is a feature request, not a 2.5-year-old question of a feature that didn't exist then.

**Comment by krisk** [comment]
Yes, that's a good thing to have, and thinking about it, should be simple to include. Perhaps double quotes (`"`) can serve as that.

**Comment by krisk** [comment]
@isiahmeadows check this out on the [v5.2.0 branch](https://github.com/krisk/Fuse/tree/v5.2.0). Let me know your thoughts.

**Comment by v0n0** [comment]
just FYI this is not in the docs for extended search

**Comment by dryu99** [comment]
Is there any way to escape the pipe operator?
