### ISSUE TITLE
Search results seem incorrect?

### ISSUE THREAD

**Issue by StringKe** [krisk/Fuse#377]
```json
[
    {
        "id":1,
        "name":"Francois One",
    },
    {
        "id":3,
        "name":"Elsie Black",
    },
    {
        "id":4,
        "name":"Alibaba Sans",
    }
]
```
When I type ```Francois One```, but he is not the first, how do I set up verbatim matching?
![image](https://user-images.githubusercontent.com/31089228/78227499-ebd04980-74ff-11ea-96df-a39db5436f8c.png)
This puzzles me, but the exact search term is not the correct answer

**Comment by krisk** [comment]
Can you share how you set up fuse (i.e, the options, etc..)?

**Comment by StringKe** [comment]
I set the `keys` and everything else is the default

**Comment by krisk** [comment]
@StringKe can you please show me your exact code?

**Comment by krisk** [comment]
Closing the issue, as there hasn't been any update from OP.
