### ISSUE TITLE
Add different builds: Full and Basic

### ISSUE THREAD

**Issue by krisk** [krisk/Fuse#385]
To save on size, it would be great to have different builds

- **Full**: Builds that contain standard fuzzy searching, extended searching, and long pattern searching. These builds are larger.

- **Basic**: Builds that contain only standard fuzzy searching. Use these if you're not going to enable extended searching and if the patterns that are searched are typically less than 32 characters in length.

**Comment by krisk** [comment]
Added in`fuse.js@5.2.0-alpha.0`.

 [Full explanation](../blob/master/docs/getting-started/different-builds.md) of build files.

cc: @cshoredaniel, @sidvishnoi - let me know your thoughts.

**Comment by cshoredaniel** [comment]
I like the idea.  In the future I wonder if it'd be possible to make the Byteap hack I pointed you at sufficiently performant (I haven't looked deeply so it's just a thought for now) handle all lengths of string that Fuse wishes to support.  It might not be possible from an algorithmic view but I'd rather like the ability to have fuzzy short and long strings without extended search included.

**Comment by krisk** [comment]
@cshoredaniel indeed, I tested the Byteap solution you provided (which, btw - I forgot to thank you for - so, thank you!) and I'm still trying to get adequate performance out of it. The 2D array computation is the bottleneck. 

Curious to know your thoughts: For very long patterns, it would seem that there would be a far smaller error-to-pattern-length ratio than on smaller patterns. Because of this, I went the ngram route, and it does seem to provide pretty good results. 

Nonetheless, I'll still fiddle with byteap sample 😄

**Comment by cshoredaniel** [comment]
Hi, sorry for the long delay.  For a longer patterns against the same text I think your observation holds.  I suspected the 2D array would be an issue, but hopefully not insurmountable.  I see you've been keeping busy and I have some reading to do.
