### ISSUE TITLE
github-actions bot not working correctly

### ISSUE THREAD

**Issue by moritz-h** [krisk/Fuse#387]
The github-actions bot seems to not work correctly. See #182.
The bot added the `Stale` label and wrote `Remove stale label or comment or this will be closed in 5 days`. As this is still an issue, I commented below, but the issue was closed nevertheless.

Would be nice if the github-actions bots can check for comments before actually closing the issue.
(And of course reopening #182 would also be nice.)

**Comment by krisk** [comment]
Oh that's no good. I can temporarily disable the bot, and also jump on that question.

**Comment by moritz-h** [comment]
@github-actions
False close of #182 is still an issue.
Let's see if this issue will be closed in 5 days to see if bot is working or not.

**Comment by moritz-h** [comment]
@krisk 
github-actions ignored the comment and closed also this issue.
