### ISSUE TITLE
Returns wrong data on manipulating entered input text

### ISSUE THREAD

**Issue by ektaSahani** [krisk/Fuse#394]
Configuration for Fuse Js:-
this.fuse = new Fuse(data, {
      threshold: 0.1,
      keys: searchKeys
    });

When I search for 'Last Hour' in following dataset
{
data:[
{
  "name": "Last Hour",
  "id": "A1",
  "age": "23"
},
{
  "name": "First Hour",
  "id": "A2",
  "age": "24"
},
{
  "name": "Second Hour",
  "id": "A3",
  "age": "25"
},
{
  "name": "Third Hour",
  "id": "A4",
  "age": "26"
},
{
  "name": "Fourth Hour",
  "id": "A5",
  "age": "27"
},
]
}

Result is - {
  "name": "Last Hour",
  "id": "A1",
  "age": "23"
}

When I change input text **Last Hour** to **Latt Hour**,
I still get the following result
 {
  "name": "Last Hour",
  "id": "A1",
  "age": "23"
}

**Comment by krisk** [comment]
Curious to know why you think it's no working correctly..

Seems to be working fine. `"Latt Hour"` is matching `"Last Hour"`, which is 1 character way from being an exact match (`t` -> `s`), and within the threshold specified.
