### ISSUE TITLE
TypeError when empty string is used for a index in the latest version.

### ISSUE THREAD

**Issue by qwefgh90** [krisk/Fuse#399]
### Describe the bug
If one of values for indice is empty string, `TypeError: Cannot read property 'length' of null` is shown.

### Version
A version used for Live Demo and v5.2.1

### Is this a regression?
I don't have an idea about it.

### 🔬Minimal Reproduction
When title property is used for a index and one of title values is empty string, this bug is reproduced.

### Additional context
![image](https://user-images.githubusercontent.com/7572251/79714686-8e643700-830c-11ea-9a7b-7aab5f6ebeff.png)

**Comment by Shmasya** [comment]
I get the exact same error.
