### ISSUE TITLE
Space separated patterns

### ISSUE THREAD

**Issue by super-cache-money** [krisk/Fuse#40]
Let's assume I have multiple keys for example, `firstName`, `lastName`, and `profession`.

Now if given the following entry:
     {
      firstName : 'joe'
      lastName: 'bloggs'
      profession: 'banker'
     }

I'd like a hit to occur for the following search values: 
    "joe"
    "bloggs banker"
    "joe bloggs" 

What's the most efficient way of accomplishing this?

**Comment by kylehalleman** [comment]
Would like to know the answer to this one too. Or if there is a way to do searches like "keyword + other keyword" or "keyword AND other keyword" like you would in Google.

**Comment by krisk** [comment]
@super-cache-money, @kylehalleman - you can simply set the `keys` values in the options:

```javascript
var options = {
 keys: ['firstName', 'lastName', 'profession']
}
var fuse = new Fuse(/*your list*/, options)
```
