### ISSUE TITLE
Why is Node.js 10 required?

### ISSUE THREAD

**Issue by sebbert** [krisk/Fuse#400]
Hi,
In `package.json`, you specify that fuse.js requires `node >= 10`. What's the reason for this? Fuse.js should run in a browser without any node.js runtime, right?

Because of reasons, I am required to use node 8 (the node 10 runtime for Firebase functions is still in beta), so this is blocking me from upgrading.

**Comment by Stradivario** [comment]
I think they did this since some of the Dev Dependencies requires it. I think when bundled there is no restriction for nodejs.

**Comment by jahed** [comment]
The engines field in package.json has nothing to do with browser support. For that, look at the Babel config and dist output.

Node 8 is no longer in LTS, it's legacy and no longer gets security updates. Expect more packages to drop Node 8. You can use older versions of Fuse.js if you need to.

https://nodejs.org/en/about/releases/

It's a shame Firebase is still on Node 8, they had 30 months to upgrade...

**Comment by Stradivario** [comment]
Look 
![Screenshot_20200522-105729](https://user-images.githubusercontent.com/19847933/82645175-23639400-9c1b-11ea-9b10-fbb14680e3de.png)
