### ISSUE TITLE
Error: Missing "name" property in key object

### ISSUE THREAD

**Issue by zaweb** [krisk/Fuse#410]
Hello. I just updated fuse.js from version 3.4.6. to 5.2.3, which is a significant jump. Unfortunately, my app no longer works. Fuse.js is giving me this error:

`Error: Missing "name" property in key object`

I'm not sure what it means by "key object" unless it's referring to the "keys" parameter in 'options.' Here is what the keys option looks like:

```
keys: [
    { name: 'article', weight: 0.7 },
    'author',
    'artist',
    'tags',
    'games',
    { name: 'issueTitle', weight: 0.6 },
    { name: 'summary', weight: 0.5 }
  ]
```
I am calling Fuse like this:
`const fuse = new Fuse(theArr, options) `

Am I doing something wrong? This worked fine until I updated it. 
Thank you in advance for your help.

**Comment by krisk** [comment]
All keys have to either be a string, or an object with `key`, `name`. You can't have a mix of both.
