### ISSUE TITLE
Option to ignore accents (diacritics) [feature]

### ISSUE THREAD

**Issue by DocBouCou** [krisk/Fuse#415]
I am using fuse.js to fuzzy-search in french language. In french (as in other languages) we have accentuated characters (é, è, ê, and e for instance). 
Some users will search with no accents, others using wrong ones (quite common misspelling), and others with the exact correct spelling, leading to different search score. I would like, if possible, an option "isAccentSensitive" (for instance) so I can choose if the score should be the same even with the wrong accent-spelling.
Thank you. It would really help if it is by default included in fuse :) .
(edit: sorry, close to #181 )

**Comment by mathieutu** [comment]
Hello!
My ~deux centimes~ two cents on this topic:
Here are a good method I use to remove accents:
```js 
export const removeAccents = str => str.normalize('NFD').replace(/[\u0300-\u036F]/g, '')
```

**Comment by mjbcopland** [comment]
You could use a custom `getFn` which wraps the existing implementation. This will work for any method of normalising strings, so it's more flexible than a built-in `isAccentSensitive` option, but there is already a built-in `isCaseSensitive` so it could be worth including too if there's high demand.

https://fusejs.io/api/options.html#getfn
https://fusejs.io/api/config.html

```js
import diacritics from 'diacritics';

function getFn() {
  return diacritics.remove(Fuse.config.getFn.apply(this, arguments));
}
```

You'll probably also want to remove diacritics from the search query.

```js
fuse.search(diacritics.remove(query))
```

**Comment by marceloverdijk** [comment]
I had some issues using above code with undefined values and string arrays like:

```
const list = [
  {
    title: "Old Man's War",
    author: 'John Scalzi',
    tags: ['fiction']
  },
  {
    title: 'The Lock Artist',
    // no author defined but in keys
    tags: ['thriller']
  }
]
```

So I did it as below.

```
function removeAccents(obj) {
  if (typeof obj === 'string' || obj instanceof String) {
    return obj.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  }
  return obj
}

function getFn: (obj, path) => {
  var value = Fuse.config.getFn(obj, path);
  if (Array.isArray(value)) {
    return value.map(el => removeAccents(el));
  }
  return removeAccents(value);
}
```

Maybe this is helpful for others.

**Comment by craPkit** [comment]
One problem with the proposed workarounds is that you lose diacritic characters from the original value in the returned matches array (when using option `includeMatches`).

**Comment by boydkelly** [comment]
> So I did it as below.
> 
> ```
> function removeAccents(obj) {
>   if (typeof obj === 'string' || obj instanceof String) {
>     return obj.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
>   }
>   return obj
> }
> 
> function getFn: (obj, path) => {
>   var value = Fuse.config.getFn(obj, path);
>   if (Array.isArray(value)) {
>     return value.map(el => removeAccents(el));
>   }
>   return removeAccents(value);
> }
> ```
> 
> Maybe this is helpful for others.

What calls getFn?  Not sure what to do here... I tried to reference in the options getFn: getFn:()

also tried:

`  // fieldNormWeight: 1,
  getFn: (obj, path) => {
    var value1 = Fuse.config.getFn(obj, path);
    if (Array.isArray(value1)) {
      return value1.map(el => removeAccents(el));
    }
    return removeAccents(value1);
  },
  keys: ["h4Id"]
};
`
Would really like to get this working...
