### ISSUE TITLE
IE11 fat arrow errors

### ISSUE THREAD

**Issue by timrhaynes** [krisk/Fuse#420]
### Describe the bug
const LOGICAL_SEARCH_INVALID_QUERY_FOR_KEY = (key) =>
  `Invalid value for key ${key}`;

Such statements in fuse.js are failing in IE11, as IE11 lacks big arrow syntax support.

### Version
6.0.0

### Is this a regression?
I believe it was working in 3.4.2.

### 🔬Minimal Reproduction
Include fust.js npm package in an Angular 9 project. Run with ng serve and then view with IE11.

**Comment by avilv** [comment]
#423

**Comment by bleuscyther** [comment]
Waiting for the pull-request it should fix that issue
