### ISSUE TITLE
Ability to just search a string?

### ISSUE THREAD

**Issue by SumNeuron** [krisk/Fuse#421]
### Description
 A clear and concise description of the problem or missing capability...
Currently it appears that fusejs is designed to search lists of objects matching specified interior keys for the pattern. However, this limits its use and integration with other options. 

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Add an option to just test a string for a pattern

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by krisk** [comment]
You can already do this, by providing simply an array of strings (though I realized the docs lack an example):

```js
const list = [“one”, “two”]
const fuse = new Fuse(list, { includeScore: true, includeMatches: true })
fuse.search(“on”)
```

**Comment by SumNeuron** [comment]
So I’d just pass a list with one element?
