### ISSUE TITLE
Allow selecting which keys you want to use for a particular search

### ISSUE THREAD

**Issue by Ktar5** [krisk/Fuse#424]
### Description
If I have two keys: tags and name, and sometimes I want to search through the tags, sometimes the names, sometimes both, I can't really do that

### Describe the solution you'd like
Add a keys array to the search as an optional parameter

**Comment by krisk** [comment]
You can already do this with [logical query expressions](https://fusejs.io/api/query.html).

**Comment by Ktar5** [comment]
@krisk Sorry but I don't see anything in the documentation that you linked to that shows specifying what key the search has to be from, maybe I'm just blind, but could you maybe give me some more direct advice for this issue?

The link you sent me seems to only be about specifying contents of the text pattern matching, but not actually choosing which keys are allowed/disallowed.

**Comment by krisk** [comment]
Suppose this is your list:

```js
const books = [
 {
    "title": "Old Man's War",
    "author": {
      "firstName": "John",
      "lastName": "Scalzi"
    }
  },
  {
    "title": "The Lock Artist",
    "author": {
      "firstName": "Steve",
      "lastName": "Hamilton"
    }
  }
]
```

```js
const fuse = new Fuse(books, {
  keys: ["title", "author.fistName", "author.lastName"]
})
```

At search time, you can specify which keys you want to search, for example:

```js
// Search for entries whose title is like “man”
fuse.search({ title: "man" })

// Search for entries who title is like “man” *and* author.firstName is like “Jon”
fuse.search({ $and: { title: "man", "author.firstName" : "Jon" }}) 
```

**Comment by Ktar5** [comment]
Thank you very much @krisk ! Much appreciated!!
