### ISSUE TITLE
False positive when searching for strings with a length of 33, 65, 129, 257 etc

### ISSUE THREAD

**Issue by JeffaloBob** [krisk/Fuse#426]
### Describe the bug
 A clear and concise description of what the bug is.
I get false positives from Fuse when looking for a length of 33, 65, 129, 257 513 etc... It seems like all(?) words appear instead of none/the closest.
### Version
 The Fuse.js version where this bug is happening.
6.0.0
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ...
not sure, but i found an issue #136 where it looks like it was fixed
### 🔬Minimal Reproduction

use the script linked by another user at #136 or in my website https://is.wasteof.money/ put 33 letter string in
### Additional context

it seems like it was fixed and then unfixed?

**Comment by krisk** [comment]
Fixed as of fuse.js@6.0.1
