### ISSUE TITLE
What is the "indices" key in the matches object

### ISSUE THREAD

**Issue by matias-miranda** [krisk/Fuse#427]
Hi! I couldn't find docs about the `indices` key present in the matches object when `includeMatches: true`.

example

```
{
    indices: [ [ 0, 19 ] ],
    value: 'Backend Development',
    key: 'projects.tasks.name',
    refIndex: 7
  }
```
What does it represent?

thanks!

**Comment by krisk** [comment]
Each entry in `indices` denotes the start and end index of a match in `value`.

**Comment by matias-miranda** [comment]
ahh great.. thanks @krisk !
