### ISSUE TITLE
Live Demo on fusejs.io is not working

### ISSUE THREAD

**Issue by stacyirish** [krisk/Fuse#433]
I have used the demo before while considering using fuse.js for a project, but now it is not working (the page seems to hang).  I have tried on multiple machines, with multiple browsers.

**Comment by rasteiner** [comment]
same here. 
Also using it in a project seems to hang the page, so I don't think it's a problem with the demo... Maybe with the latest release?

**Comment by stacyirish** [comment]
Thanks, @rasteiner.  I was wondering that but I'm not using it in any projects yet so I wasn't sure.

**Comment by rasteiner** [comment]
Just checked, downgrading to 6.0.2 solved my issue :)

So it definitely seems to be a regression in 6.0.3

**Comment by krisk** [comment]
Thanks for flagging. Just updated.

**Comment by stacyirish** [comment]
Thanks for the quick fix!
