### ISSUE TITLE
Unexpected token '...'. Expected a property name

### ISSUE THREAD

**Issue by WilliamALiang** [krisk/Fuse#445]
### Describe the bug
 A clear and concise description of what the bug is.
Unexpected token '...'. Expected a property name
### Version
 The Fuse.js version where this bug is happening.
fuse.js@6.0.4
ios 10.3.1
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ...

**Comment by krisk** [comment]
Using this in IE?

**Comment by jmheldsans** [comment]
Not sure about OP, but I am attempting to use it in IE11.  The arrow function in fuse.esm.js prevents this.  Is there a different way I should be using Fuse?

**Comment by WilliamALiang** [comment]
@krisk Using this in android 5.1-7.1 and ios 10.3.1
Must be brought in manually /dist/fuse.min.js

**Comment by daphnesmit** [comment]
Types for fuse min:
```
declare module 'fuse.js/dist/fuse.min.js' {
  import Fuse from 'fuse.js';
  export default Fuse;
}
```

**Comment by daphnesmit** [comment]
I used the dist version, but still seeing object spread in the main bundle...
