### ISSUE TITLE
Mixing logical and fuzzy search

### ISSUE THREAD

**Issue by jlismore** [krisk/Fuse#448]
From the docs it seems there are two ways of searching a list

- via a string that searches every key for matches e.g. `fuse.search('blue')`
- via the new logical method that searches explicit keys for matches e.g. `fuse.search({ $and: [{ author: 'abc' }, { title: 'xyz' }] })`

However it doesn't look like it's possible to combine the two methods simply. Imagine I want to search my list for every item where color === 'blue' AND any field contains 'new'. I could do this by combining `$and` and `$or` operators, but the $or becomes really verbose once there are more than a few keys.

```
const result = fuse.search({
  $and: [
    { color: "'blue" }, // Exact match for blue
    {
      $or: [
        { title: 'new' }, 
        { type: 'new' },
        { family: 'new' },
        { group: 'new' },
        ...
      ]
    }
  ]
})
```

Is there a better way to accomplish this?

**Comment by belvederef** [comment]
Maybe there is a better solution but if you need to search a word in _any_ field of the object `obj`, and given you have already defined a set of keys `keys` to index, then I can recommend using:
```js
$or: keys.map(k => { k: 'new' })
```

**Comment by krisk** [comment]
> Maybe there is a better solution but if you need to search a word in _any_ field of the object `obj`, and given you have already defined a set of keys `keys` to index, then I can recommend using:
> 
> ```js
> $or: keys.map((k) => ({ [k]: 'new' }))
> ```

That's a pretty good solution.
