### ISSUE TITLE
Stale CHANGELOG / Releases Page

### ISSUE THREAD

**Issue by jahed** [krisk/Fuse#452]
I noticed the "Release Notes" link on the website links to the "[Releases](https://github.com/krisk/Fuse/releases)" page on GitHub. However, there are no notes explaining what's changed. The [CHANGELOG](https://github.com/krisk/Fuse/blob/master/CHANGELOG.md) also has not been updated. So I tried looking through the commit history to figure out what's changed between `6.0.4` and `6.2.1` but it's too confusing as features are added and removed between commits (alpha/beta releases) before a stable release is made.

Having a Releases/CHANGELOG updated as part of the stable release process would be a great help to anyone using this library to keep track of new features, bug fixes, etc.

Thanks,
Jahed

**Comment by krisk** [comment]
Good flag. Thanks for raising. I've updated the [release page](https://github.com/krisk/Fuse/releases) with details.

**Comment by jahed** [comment]
Thanks for the quick update. I was going to recommend conventional commits too, but it doesn't fit everyone's workflow. Good to know it's being considered :+1:
