### ISSUE TITLE
Support for japanese fuzzy search ( Hiragana/Katakana/Romaji )

### ISSUE THREAD

**Issue by mastef** [krisk/Fuse#456]
I just wanted to check if this fuzzy search library supports Japanese fuzzy search. If I understood it correctly then searching for `ワナカナ` would also highlight `WanaKana` and `わなかな`

See https://github.com/WaniKani/WanaKana

I'm asking because I'm evaluating fuzzy search engines for my extension, and have also received a Japanese fuzzy search feature request.

**Comment by krisk** [comment]
I would love for Fuse.js to support different languages. I've been thinking about it for a while. Unfortunately, at this moment, it's difficult for me to justify the time investment to do that. It's quite laborious 😓

**Comment by RuslanZavacky** [comment]
Hey @krisk maybe you can do some pointers on what/where might need to be changed/updated to support localization? We use fuse for our in-browser search and I might have time to add support for some other languages (as a starter to search in Japanese)

Some hints where to start would be greatly appreciated 👍

**Comment by jmaver-plume** [comment]
@RuslanZavacky potential solution we are using is Kuroshiro.js which implements Kuromoji.js. We convert Kanji, Hiragana, Katana into Romaji. It seems to work well enough.
