### ISSUE TITLE
Is there a way to build a query on the fly?

### ISSUE THREAD

**Issue by chrisjmccrum** [krisk/Fuse#462]
First off - want to say this library is great and very useful already! I'm looking to build a search panel that has more than just a simple text input for search. For the sake of simplicity, let's say I only have two search fields.

**Text Input**
Keyword Search of Account Names

**Dropdown**
Account Type [Options are: Any, Commercial, Residential, Government] (Default Value is Any)

The data object looks like this:
`[{ name: 'ABC Company', accountType: 'Commercial' }, { name: 'Lakehouse', accountType: 'Residential' }]`

What I would like to do is to be able to either:
- Always search on all fields but use a wildcard operator in the search that really doesn't filter anything in the situation of dropdown being set to "Any"
- Or, if there's a way to dynamically build a Logical Query that would solve the problem. I could then piece together it like this:
```
    var result = this.fuse.search({
      $and: [{ name: searchCriteria.keywords }],
      if (searchCriteria.industry !== "any") {
        $and: [{ accountType: searchCriteria.accountType }]
      }
    });

```
Perhaps I'm overcomplicating it and there's a much simpler approach lol? Any help would be appreciated

**Comment by krisk** [comment]
Can't you simply set a variable and modify it based on the search criteria? For example:

```js
let conditions = [{ name: searchCriteria.keywords }]

if (searchCriteria.industry !== "any" {
  conditions.push({ accountType: searchCriteria.accountType )
}

var result = this.fuse.search({ $and: conditions })
```

**Comment by chrisjmccrum** [comment]
Thank you - I had a feeling I was over complicating it! This works just fine :)
