### ISSUE TITLE
Fuse.js constructor options typing are widened

### ISSUE THREAD

**Issue by whitecolor** [krisk/Fuse#470]
### Describe the bug
Typings of options allow to privide illegal options:
https://github.com/krisk/Fuse/blob/master/src/index.d.ts#L4

So currently this is possible:
```ts
new Fuse(items, {
  whatever: true
})
```

Is there a reason why not change it to:
```ts
declare class Fuse<T> {
  constructor(list: ReadonlyArray<T>, options?: Fuse.IFuseOptions<T>, index?: FuseIndex<T>)
```
?

**Comment by krisk** [comment]
Good catch. Will update.
