### ISSUE TITLE
Search with pattern.length > 32 doesn't work

### ISSUE THREAD

**Issue by danielhoey** [krisk/Fuse#48]
If I set maxPatternLength > 32 and use a search pattern that is 33 characters, all items are matched. Looking at the code, I *think* that this is because matchmask wraps rolls over back to 1 when patternLen is 33 (I don't really have a handle on the algorithm though).

     this.matchmask = 1 << (this.patternLen - 1);

Maybe an error should be thrown when setting maxPatternLength > 32 as it doesn't appear to be a valid value.

**Comment by mrienstra** [comment]
See #38

**Comment by krisk** [comment]
Fixed in version 2.0.0
