### ISSUE TITLE
Custom results formatting function

### ISSUE THREAD

**Issue by sytolk** [krisk/Fuse#482]
### Description
 A clear and concise description of the problem or missing capability...
Now fuse.js return results like {item: {..}} I needs to reformat (strip item) and skip some properties from results.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Its better to have default getResults() function. User can provide custom getResults() like:
```
const customResults = (result) => {
cutomItem: {
  customProps: result.props
  }
}
const fuse = new Fuse(results, fuseOptions);
results = fuse.search('searchQuery', customResults); 
```
### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

 Alternatively results can be fultered after searching but if you search in bigger text and this text properties its not needed in result object this solution will be with very bad performance (its need extra RAM usage)

**Comment by kesylo** [comment]
yes this will be pretty handy. A way to get only the properties you need from the result instead of all the object

**Comment by sytolk** [comment]
Not stale
