### ISSUE TITLE
ignoreLocation=true does not apply when useExtendedSearch=true

### ISSUE THREAD

**Issue by Kijit** [krisk/Fuse#489]
### Describe the bug
The scoring logic is not ignoring Field Norm when using extended search. When not doing pattern matching, ignoreFieldNorm works as expected but with extendedSearch, it returns results with shorter string scoring higher.

### Version
v6.4.0

### Is this a regression?
Not sure

### 🔬Minimal Reproduction
data = [ longest string, longer string, long string];

fuse.search('string');

// with extendedSearch=false & ignoreLocation= true
result = [ longest string, longer string, long string];

// with extendedSearch=true & ignoreLocation= true
result = [ long string, longer string, longest string ];

### Additional context
We are sorting data alphabetically, and so we want to use IgnoreFieldNorm to maintain this order and show matches while ignoring length of strings it matches with.

**Comment by p0fi** [comment]
Is this still an issue? It seems the be case for me too!

**Comment by imnotjames** [comment]
Also seeing this issue. It's a bit of a problem because without the flag the search defaults to only 60 characters

**Comment by imnotjames** [comment]
6.4.3 fixes this!
