### ISSUE TITLE
Callback in search items?

### ISSUE THREAD

**Issue by jfuehner** [krisk/Fuse#496]
I was curious if it is possible to include a function in the array of items that is passed to the `Fuse` constructor? 

```
[
  {
    "title": "Old Man's War",
    "author": {
      "firstName": "John",
      "lastName": "Scalzi",
      click: function() {
    console.log("test");
  }
    }
  },
...
]
```

I attempted this using the Fuse demo but the function was stripped out of the results displayed...

**Comment by krisk** [comment]
No, that's not possible. The list is serialized into an index for simpler and speedier processing.
