### ISSUE TITLE
Getting wrong results, is it possible two combine search keys?

### ISSUE THREAD

**Issue by karahan** [krisk/Fuse#499]
These are my settings.
```
shouldSort: true,
threshold: 0.8,
keys: ['make', 'model']
```
and this is the searched array
```
[
    { make: "Audi", model: "A5" },
    { make: "Audi", model: "A6 avant" },
]
```
If I search "Audi A5"
the audi a6 avant shows up first. I think it has to do with the fact that the whole "Audi A5" string is being matched with both the Make and Model

**Comment by karahan** [comment]
Is it possible to combine the keys in the search so it searches both Make and Model together like a concatenated string?

**Comment by karahan** [comment]
So far i've tried mapping the make + model in one string and using that new key as the searchkey as option (this works good). But i was wondering if there is any functionality like this built-in and im just missing it

**Comment by krisk** [comment]
Yes, there is a way. You can use logical query operators [$AND](https://fusejs.io/api/query.html#and).
