### ISSUE TITLE
Describe fuzziness in a little more detail?

### ISSUE THREAD

**Issue by hadley** [krisk/Fuse#504]
e.g.

* Exactly how is it different from the bitap algorithm?
* What is the scale? I assume 0 = perfect match and 1 = perfect mismatch, but it would be useful to spell that out. 
* How does fuzziness interact with location/distance/threshold to compute the final score? In particular, what happens when `ignoreLocation` is true?

**Comment by krisk** [comment]
The scale is you listed is correct. I’ll give a bit more details on the differences though. Did you see the explanation on the [scoring theory](https://fusejs.io/concepts/scoring-theory.html#scoring-theory)?

**Comment by hadley** [comment]
Yeah, the problem is the main description doesn't include fuzziness:

> With the above options, for something to be considered a match, it would have to be within (threshold) 0.6 x (distance) 100 = 60 characters away from the expected location 0.
