### ISSUE TITLE
New demo showcasing options in real time

### ISSUE THREAD

**Issue by james2doyle** [krisk/Fuse#506]
I was talking with my team about using Fuse in our product for building a filter UI. I showed the demo but it didn't really showcase some of flexibility. They are mostly non-technical so explaining the options didn't quite help and having them tweak JSON is not really feasible.

I whipped up [this alternative demo](https://rn869.csb.app/) that shows the options, the search output, as well as the dataset used in the filter.

![demo gif](https://p198.p4.n0.cdn.getcloudapp.com/items/qGuvZwJd/Screen%20Recording%202020-10-26%20at%2009.57.00%20AM.gif?v=d4e97b895acbcbe6609ebf16ef34e692)

I just wanted to share this as it helped my team imagine how this would be used and see the flexibility. If you'd like, I can submit a PR or update the docs with a link to this demo as well

**Comment by krisk** [comment]
Could be nice to have on the site. Feel free to start a PR. Thanks!

**Comment by james2doyle** [comment]
Closed with #513
