### ISSUE TITLE
Can you add information about the "tokenize" option?

### ISSUE THREAD

**Issue by carlinmack** [krisk/Fuse#511]
I only found out about it through [this stackoverflow post](https://stackoverflow.com/questions/47241583/fuse-js-how-to-return-an-exact-match-when-there-are-two-words-to-search-for) with 2,000 views

**Comment by krisk** [comment]
No such option anymore. This was deprecated earlier this year.

**Comment by carlinmack** [comment]
maybe a comment about it's deprecation then? people will still use it as there's no error or documentation about it
