### ISSUE TITLE
FuseIndex type isn't exported in Fuse namespace

### ISSUE THREAD

**Issue by yunyu** [krisk/Fuse#519]
### Describe the bug
The type for FuseIndex isn't exported in the Fuse namespace

### Version
6.4.1

### Is this a regression?
No

### 🔬Minimal Reproduction
import { FuseIndex } from "fuse.js"

### Additional context
This makes it impossible to type the result of Fuse.createIndex without actually calling the method (say, storing the value in a map or loading from disk).

A non-obvious workaround is to do:

```ts
ReturnType<Fuse<GenericArgument>["getIndex"]>
```

**Comment by krisk** [comment]
Good point. Will address this.
