### ISSUE TITLE
Not working in TypeScript

### ISSUE THREAD

**Issue by dmurawsky** [krisk/Fuse#521]
### Describe the bug

TypeScript can't import the library

```
ERROR in ./node_modules/fuse.js/dist/fuse.esm.js
       Module parse failed: Unexpected token (271:2)
       You may need an appropriate loader to handle this file type.
       | 
       | var Config = {
       |   ...BasicOptions,
       |   ...MatchOptions,
       |   ...FuzzyOptions,
        @ ./app/javascript/helpers/on-demand.ts 17:0-27
        @ ./app/javascript/apps/customer/pages/on-demand.tsx
        @ ./app/javascript/apps/customer/index.tsx
        @ ./app/javascript/packs/customer.tsx
```

### Version

`6.4.3`

### Is this a regression?

No

### 🔬Minimal Reproduction

Import Fuse into a TypeScript app

**Comment by dmurawsky** [comment]
@krisk is this a known issue. I'm a patreon supporter if that helps :)

**Comment by krisk** [comment]
Hey! Would you have a sample project I can check? Have you tried just doing `import Fuse from 'fuse.js'`?

**Comment by dmurawsky** [comment]
Thanks Krisk, I created a [basic TS CRA example](https://github.com/dmurawsky/fuse-ts) and it seems to be working fine. It's failing in a Ruby on Rails project that uses the webpacker ruby gem so that's probably the issue. We're moving this project out of webpacker pretty soon so we're not worried about it.

**Comment by NorthBei** [comment]
I also encouter this problem like below, after I use CRA build my react rpoject, but I don't use typescript
```
./node_modules/fuse.js/dist/fuse.esm.js
Module parse failed: Unexpected token (271:2)
You may need an appropriate loader to handle this file type.
| 
| var Config = {
|   ...BasicOptions,
|   ...MatchOptions,
|   ...FuzzyOptions,
```
