### ISSUE TITLE
TypeError: fuse_js_1.default is not a constructor

### ISSUE THREAD

**Issue by utsavagrawal** [krisk/Fuse#529]
`

    import Fuse from 'fuse.js';
    let a = ["Utsav Agrawal", "David Agrawal", "Johny Agrawal", "Joseph Agrawal", "Imran Khan"]
    const newWord = "Agra";
    const opts = {
      threshold: 0.5,
      ignoreLocation: true
    }
    let result;
    try {
      let fuse = new Fuse(a, opts);
      result = fuse.search(newWord as string)
      console.log('result')
      console.log(result)
    }
    catch (e){
      console.log('errrorrrrrrr')
      console.log(e)
    }
`

Getting the above mentioned error. 

tsconfig.json>compilerOptions 

```
"compilerOptions": {
    "target": "es6",
    "lib": ["es5", "es6", "dom"],
    "types": ["reflect-metadata", "node", "jest"],
    "outDir": "dist",
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "allowJs": true,
    "preserveWatchOutput": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },

```

**Comment by saran1856** [comment]
Any idea how would this solve the problem for client side services aka web components?

**Comment by utsavagrawal** [comment]
> 

How are you trying to import it? Did you download a min.js file or was it another way?
