### ISSUE TITLE
Add an option to return the raw search data

### ISSUE THREAD

**Issue by danitrod** [krisk/Fuse#532]
### Description

I'm not sure if I'm missing something, but I would like Fuse to return the search objects for me without refIndex and the item labeling. Right now I have to loop one more time after having the search results, to have my objects again.

### Describe the solution you'd like

What I have is this response:
```js
[
  {
    "item": {
      "title": "Right Ho Jeeves",
      "author": "P.D. Mans",
      "tags": ["fiction", "war"]
    },
    "refIndex": 1
  },
  {
    "item": {
      "title": "Old Man's War fiction",
      "author": "John X",
      "tags": ["war"]
    },
    "refIndex": 0
  }
]
```

What I would like is this response:
```js
[
  {
    "title": "Right Ho Jeeves",
    "author": "P.D. Mans",
    "tags": ["fiction", "war"]
  },
  {
    "title": "Old Man's War fiction",
    "author": "John X",
    "tags": ["war"]
  }
]
```

It would be useful when the score/refIndex are not needed.

### Describe alternatives you've considered

I looked at the available options but none seem to solve this. The current workaround is to loop through and 'restore' the search results, but it's more complexity added for no reason.

**Comment by danitrod** [comment]
I'd be willing to add this feature if the maintainers are interested in merging this.

**Comment by charliegroll** [comment]
I'm curious if this is that useful to you since all that's needed is `.map(r => r.item)` on the results

**Comment by danitrod** [comment]
True. I think it would be nice to have the option to get the raw values, though. It would decrease the loading time a little bit with larger amounts of data, and it doesn't seem to have any drawbacks.
