### ISSUE TITLE
Add score to matches result

### ISSUE THREAD

**Issue by ibedarev** [krisk/Fuse#535]
### Description
Add score to matches result. It allows filter nested arrays

### Describe the solution you'd like
change transformMatches function to `function transformMatches(includeScore) return function (result, data)`
inside add 
```
if (includeScore && isDefined(match.score)) {
        obj.score = match.score
      }
```

### Use case
Sorting nested arrays in search result 

```
const sortMatches = (a: Fuse.FuseResultMatch, b: Fuse.FuseResultMatch) => {
  if (a.score !== b.score) return a.score! - b.score!
  return a.refIndex! - b.refIndex!
}
```

`matches.filter((m) => m.key === 'specific.neste.path').sort(sortMatches)`

**Comment by ibedarev** [comment]
https://github.com/krisk/Fuse/pull/536

**Comment by lawrence-laz** [comment]
I hit the same use case: searching through complex objects with array property, each object usually has multiple matches inside the array property which are scored individually (can be seen in `FuseSortFunctionArg`), but these scores are unavailable in `FuseResult`, where we only get overall scores for each object as a whole.

It's useful to know each matches score individually so as to be able to display only the selected best matches from the array to the user.
