### ISSUE TITLE
Is there any way to just look thru all the nested string without specify the keys?

### ISSUE THREAD

**Issue by sooxt98** [krisk/Fuse#546]

**Comment by krisk** [comment]
Could you provide an example of what exactly you're looking for? Is it that you're searching through a list of strings?

**Comment by sooxt98** [comment]
@krisk Instead of specify the keys, i wish there's a way to include everything into the search with *
``` js
const fuse = new Fuse(books, {
  keys: ['title', 'author.firstName']
})
```

``` js
const fuse = new Fuse(books, {
  keys: ['*']
})
```

**Comment by sooxt98** [comment]
Remove Stale
