### ISSUE TITLE
findAllMatches broken

### ISSUE THREAD

**Issue by dodlhuat** [krisk/Fuse#547]
### Describe the bug
there seems to be an issue with scores already mentioned here https://github.com/krisk/Fuse/issues/545 which may lead to the problem that findAllMachtes never finds a perfect match and therefore always shows partial matches

### Version
6.4.6.

### Is this a regression?
already happened in 6.4.1

### 🔬Minimal Reproduction
```
    const options = {
        findAllMatches: false,
        threshold: 0.3,
        keys: ["name"],
      };

   const results = (new Fuse([{name: 'Auditor'}, {name: 'Auditee'}], options)).search('Auditor');
```

**Comment by dodlhuat** [comment]
Unfortnuately it seems like fuse is dead and I have to switch to another option for fuzzy search.

**Comment by krisk** [comment]
As I mentioned in the #545, this is by design. See [scoring theory](https://fusejs.io/concepts/scoring-theory.html) for more info.

**Comment by dodlhuat** [comment]
In this case findAllMatches can be removed as it never will work, or needs to be tweaked to already work with very low comparison differences

**Comment by dodlhuat** [comment]
For anyone also running into this problem, as score never returns 0 and findAllMatches is looking for a zero which will never appear, I simply added a check on my own that looks for a score near 0 which counts as an exact match. This might not be the best solution as it can return false positives, but was the only way I could think of.

**Comment by jenjen75** [comment]
Hello, this workaround, could help : 
```ts
const perfectMatch = fuse.value.search(q).find(e => e.score === Number.EPSILON)
```
