### ISSUE TITLE
Logical Operators with Extended Search Returning Unexpected Results

### ISSUE THREAD

**Issue by nminchow** [krisk/Fuse#548]
### Describe the bug
Logical operators with extended search expressions are not returning expected results.

### Version
6.4.6

### Is this a regression?
This is the first version I have used

### 🔬Minimal Reproduction
```js
const Fuse = require('fuse.js');

const data = [
  {
    type: 'foo bar',
    name: 'hit',
    stub: 'hit',
  },
  {
    type: 'qux quz',
    name: 'miss',
    stub: 'miss',
  },
];

const db = new Fuse(data, {
  keys: ['name', 'stub', 'type'],
  includeScore: true,
});

const notQux = db.search({
  $and: [
    {
      type: '!^qux',
    },
    {
      $or: [
        { name: 'hit' },
        { stub: 'hit' },
      ],
    },
  ],
})[0];

console.log(notQux); // undefined

const isBar = db.search({
  $and: [
    {
      type: '^bar',
    },
    {
      $or: [
        { name: 'hit' },
        { stub: 'hit' },
      ],
    },
  ],
})[0];

console.log(isBar);
// {
//   item: { type: 'foo bar', name: 'hit', stub: 'hit' },
//   refIndex: 0,
//   score: 0.0021180204984211294
// }
```

### Additional context
In the above example, I would expect the opposite behavior. If my understanding is correct, the first query should be returning the `foo bar` object, and the second query should be `undefined`.

**Comment by krisk** [comment]
Seems to work just fine:

<img width="760" alt="Screen Shot 2021-05-08 at 9 32 16 AM" src="https://user-images.githubusercontent.com/565580/117546653-4c259a80-afe0-11eb-8aae-1d3b9a02dc3b.png">
