### ISSUE TITLE
Comparison with other JS search engine

### ISSUE THREAD

**Issue by manhluong** [krisk/Fuse#552]
Hi, thank you for your work!

I was wondering, what is the main advantage of fuse over other js search engines like lunr? https://lunrjs.com/

I think a short page in the docs of fuse would be helpful.

**Comment by krisk** [comment]
Good question. I think there's a few posts comparison this solution with various others, include Lunr. Now, I don't necessarily agree with all that's been said, so maybe I should write up a post about it 😄. It's laborious, so give me some time. 

In the meantime, check out some of the responses in this Twitter [thread](https://twitter.com/delucioux/status/1328008527630241799):

**Comment by phal0r** [comment]
I found this little evaluation, which describes their opinion on the best use cases for the different libraries: https://wiki.gpii.net/w/Technology_Evaluation_-_Static_Site_Search

**Comment by manhluong** [comment]
Thank you everyone for the answers!

Those are very interesting reads!
