### ISSUE TITLE
Safari11/IE11 compatibility. Why ESM target is es6? 

### ISSUE THREAD

**Issue by nghiepit** [krisk/Fuse#553]
### Describe the bug
Currently, the browser of my clients broken when they use `Mobile Safari 11` browser.
Because `fuse.js` set the target is `es6`.

So, Why `fuse.js`  set target is `es6` in tsconfig.json? But not `es5`.
```json
{
  "compilerOptions": {
    "module": "es6",
    "lib": ["es6"],
    "target": "es6"
  }
}
```
You can see https://github.com/krisk/Fuse/blob/master/dist/fuse.esm.js contains a syntax of es6.

### Version
`fuse.js@6.4.6`

**Comment by jdanil** [comment]
I'm facing this one too. @krisk it looks like there are two open prs that would address this #383 and #423.
Would it be possible to merge and release one of these?

**Comment by stevenwchien** [comment]
Hit this bug as well - is this going to be addressed? It sounds like es5 is the correct target
