### ISSUE TITLE
How to search a single word?

### ISSUE THREAD

**Issue by hieuvts** [krisk/Fuse#565]
Fuse search not match if field value is only a single word.

![image](https://user-images.githubusercontent.com/38729512/128328535-583012f8-aac7-48a4-881a-1b872127e7f0.png)

Code: 
```
  const fuse = new Fuse(characters, {
    // keys: ["name", "company", "species"],
    keys: [{ name: "title"}],
    threshold: 1.0,
    ignoreLocation: true,
    includeScore: true,
  });
```

I have to inseart a space (after a stand alone word) to make Fuse recognize it.
Is it a bug or I'm using wrong Fuse search options?

**Comment by JordanMalan** [comment]
@hieuvts I've opened your sandbox and tested a few scenarios and could not reproduce the issue. I have also tested locally with no issue.

Is it possible your build did not update when you first added that entry? That could explain why it wasn't available when searching... If you continue to have this issue, try refreshing the sandbox window (to the left of the address bar) and try again.

**Comment by hieuvts** [comment]
@JordanMalan I'm sorry for didn't provide a sandbox link.
Please take a look in: https://codesandbox.io/s/confident-easley-k9l83?file=/src/App.js

"John" and "Michael" are not listed in the search results. But "Oliver " (with a white space) does.
![image](https://user-images.githubusercontent.com/38729512/128963516-4beae1c9-4696-49fc-89c6-73f10daf0068.png)

**Comment by hieuvts** [comment]
@JordanMalan  
Thank you for helping me solve the problem with a nice solution. It's easy to understand.
