### ISSUE TITLE
Fuse is not a constructor

### ISSUE THREAD

**Issue by mikeymckay** [krisk/Fuse#567]
I am requiring fuse:

Fuse = require('fuse.js')

When I run it in locally in node it works fine. Then in order to deploy it to an AWS Lambda function I package it up with webpack. The error that I get from the AWS logs is:

Fuse is not a constructor. 

I've seen people posting similar errors with Fuse and angular, which also uses webpack. So I am guessing that it is the webpack step that is breaking stuff. Any suggestions on how to resolve this?

**Comment by TimShilov** [comment]
For anyone encountering this issue, I managed to solve this error by replacing the require part
```js
const Fuse = require("fuse.js");
```
with this:
```js
const Fuse = require("fuse.js").default;
```
