### ISSUE TITLE
Threshold values per field: fuzzy matching for some, exact for others

### ISSUE THREAD

**Issue by ndrsn** [krisk/Fuse#576]
First of all, thank you for fuse.js!

### Description
For each document in my index, I have some fields of which some are text, others are numbers or IDs. For the text fields I'd like to search with a certain (non-zero) threshold value, but for the ID fields I only want exact matching (i.e. `threshold = 0`).

So for example, with

```json
{
  "name": "John Doe",
  "internalId": "63B5JOX13",
  "externalId": "Y45HNXXZ"
}
```

searching on "Jo" should _only_ match on the `name` field.

### Describe the solution you'd like
Perhaps we could extend the functionality of the `threshold` argument to the constructor? Now it accept a `Number`, but if it were to also accept a dictionary, we could specify thresholds per field, like so:

```js
new Fuse(collection, {
  threshold: {
    name: 0.45,
    internalId: 0,
    externalId: 0
  }
});
```
If there are more fields than are specified in the dictionary, Fuse could rely on a fallback threshold option, say `defaultThreshold`.

I have not yet looked into the internal workings of Fuse, so I am not sure how realistic this is, but if it's of interest, I could draft  up a pull request? Let me know what you think?

**Comment by colbyfayock** [comment]
@UserJHansen im running into a similar situation. from what i'm experiencing, you need to enable extended search to use that exact match feature and as soon as you do, the whitespace in the `name` field is treated differently per the docs

> White space acts as an AND operator, while a single pipe (|) character acts as an OR operator.

https://fusejs.io/examples.html#extended-search

i have the exact same thing where i need to provide exact match on an ID but i need fuzzy search on a title-like string (like a blog post title)

**Comment by colbyfayock** [comment]
actually nevermind, i think my issue may have been misuse of `minMatchCharLength`, where in my example, setting `minMatchCharLength` to `3` would prevent me from matching strings like "how to ..." with a query of "how to" (i dont totally understand this one but fixed without it)
