### ISSUE TITLE
Texts with spaces are filtered out

### ISSUE THREAD

**Issue by megamind2301** [krisk/Fuse#580]
I just want to ingore white spaces in search text and data both, while filtering. 

```
data = [ {name: "Avenger"}, {name: "Ave nger"}, {name: "avenger ultron"} ]
searchText = "aven ger" // should return all three
searchText = "avengeras" // should return none
```
Current config looks like: 

```
{
    shouldSort: true,
    threshold: 0.05,
    location: 0,
    distance: 800,
    maxPatternLength: 32,
    minMatchCharLength: 1,
    keys: ["name"],
    tokenize: true,
    matchAllTokens: true
  }
```

**Comment by megamind2301** [comment]
@krisk ^

**Comment by krisk** [comment]
This looks like a custom search logic. You cannot pick and choose which results to return at such a granular level. For example, `"avengeras"` is sufficiently close to `"avenger"` and `"Ave nger"`, so they would always (and frankly _should_) be returned.

Note that if you're interested in ignoring space in the search query, then you can simply remove it before passing it to the fuse search function:

```js
const removeSpace = (text) => text.replace(/\s/g, '');

let results = fuse.search(removeSpace("aven ger"))
```
