### ISSUE TITLE
Fuse on deno.land/x/ is outdated

### ISSUE THREAD

**Issue by timonson** [krisk/Fuse#587]
Would you mind updating https://deno.land/x/fuse/dist/fuse.esm.min.js for the latest release? It is still at version `v6.4.1` there. Did something go wrong with the webhooks implementation?
Thanks!

**Comment by timonson** [comment]
Remove label `Stale`

**Comment by chmac** [comment]
This was auto closed by the GitHub bot but is still an open issue. The version on deno.land/x is still stuck at 6.4.1.
