### ISSUE TITLE
Feature request: Highlighting Search key's in the result.

### ISSUE THREAD

**Issue by Abhinav1217** [krisk/Fuse#6]
Very simple and nice plugin. I have been looking for such fuzzy search library for calender app i am trying to build. I was hoping if there was some way to highlight or mark the query string in the result set.  
What i am asking is based on command pallet in sublime text. I search for string _'rown'_ in search box ( [eg.. on your website](http://kiro.me/projects/fuse.html) ). And the result set are shown with the query value visible. eg like in bold, "dan b **rown** ", " **ro** b gra **n** t ".

**Comment by krisk** [comment]
Wow. Long hiatus here. Feature was suggested almost 2 years ago. Mea culpa. Confession: still didn't get around to doing this, but clearly there's still some interest in this feature. Anyone interested in tackling this problem? As it stands, the underlying bitap algorithm would most likely have to change to support this.

**Comment by Abhinav1217** [comment]
This really still is a desirable feature.  I haven't worked with fuse since the time I asked the question. As far as I remember, I chained the outputs to another function which used a regex script I found on gist, and modified it to insert `<b></b>` tag around the matched string, Before I displayed it.   
That itself have a significant performance degradetion, but it was usable for project at `thrashold of 0.0`.

I would re-quote from my last reply here,     
>Do think about extending it with extra plugins. It will add shines to this already excellent masterpiece.

**Comment by dalgard** [comment]
+1

What @fxck said – the library is great, highlighting is the only thing that's really missing.

**Comment by AtmoEntity** [comment]
I totally support this! This is the one thing this library is missing.

**Comment by AtmoEntity** [comment]
I ended up modifying fuse.js to get it to work the way I needed, although I'm using a custom searcher. I'm super busy, but maybe I'll fork and recreate the changes if I get a spare moment.

Basically what I did is in the searcher is this:

        return {
            isMatch: true,
            score: totalScore,
            highlight: calculatedHighlight,
        };

Then I added an additional option to Fuse:

            search = new Fuse(books, {
                keys: k,
                searchFn: values,
                include: ['score', 'highlight']
            });

Very simple to implement, and I was only digging in the code for a few minutes. Then of course the main task would be to implement the highlighting efficiently in BitapSearcher, which I didn't really look at (since I'm using a custom searcher).

Hope that helps someone! If not, like I said, I may come along and implement this myself at some point.

**Comment by mapsam** [comment]
+1 this library is great.

**Comment by marcoala** [comment]
Any news?

**Comment by marcoala** [comment]
I digged a little bit into the code and I've something working, still need some test and better name for variables, but the basic idea is to have a _charmask_ (not sure if is a thing) that represent the match, so:

https://github.com/marcoala/Fuse/commit/af05432f357e2bde71e8df835b9716dbb9428a1e

Search: _rown_
dan b**rown** --> '000001111'
**ro**b gra**n**t -->  '11000010'

0 for not match, and 1 for match. Maybe the final can be represented with something in the form of [index, length] as pointed before, but I didn't figure out a way to do it without passing for the mask first.
So @kriskwhat do you think? If you like the approach I can proceed with writing test and submitting an actual pull request.

**Comment by krisk** [comment]
@marcoala, thanks for looking into this :+1:  

Instead of a character mask, I've made some changes to the codebase to use a match mask array, which simplifies the computation, and returns the matched indices:

```javascript
var items = ['FH Mannheim', 'University Mannheim']
var fuse = new Fuse(items, {
  include: ['score', 'matchedIndices']
})
var result = fuse.search('Uni Mannheim')

// output
[{
  item: 1,
  matchedIndices: [ [ 0, 2 ], [ 4, 4 ], [ 7, 7 ], [ 10, 18 ] ],
  score: 0.32
}, {
  item: 0,
  matchedIndices: [ [ 1, 10 ] ],
  score: 0.25
}]
```

I've published a beta version. Thoughts?

**Comment by krisk** [comment]
Ok, I'm thinking this instead:

Input:

```javascript
var items = [{
  name: 'FH Mannheim',
  title: 's Uni'
}, {
  name: 'University Mannheim',
  title: 'd Uni'
}]
var fuse = new Fuse(items, {
  verbose: true,
  keys: ['name', 'title'],
  include: ['score', 'matches']
})
var result = fuse.search('Uni')
```

Output:

```javascript
[{
  item: {
    name: 'University Mannheim',
    title: 'd Uni',
    author: {
      more: 'un'
    }
  },
  matches: [{
    key: 'name',
    indices: [[0, 2]]
  }, {
    key: 'title',
    indices: [[2, 4]]
  }],
  score: 0.11811111111111111
}, {
  item: {
    name: 'FH Mannheim',
    title: 's Uni',
    author: {
      more: 'un'
    }
  },
  matches: [{
    key: 'title',
    indices: [[2, 4]
    ]
  }],
  score: 0.17666666666666667
}]
```

This way you'll know to which keys the matched indices belong.

**Comment by janraasch** [comment]
Sounds great. Is that part of `2.2.0-beta`?

**Comment by krisk** [comment]
@janraasch yes, I just updated it. Have not published to npm yet. Nonetheless, try it out. Let me know what you think. I still need to create a list of tests against it.

**Comment by janraasch** [comment]
Alright, cool. I'll check it out.

**Comment by krisk** [comment]
For reference, once you have the matched indices, you can then do a simple string builder to format the text according to those indices:

```javascript
var text = 'hello world' // assume this is the text 
var result = []
var matches = [[1, 3], [6, 8]] // assume these are the matched indices
var pair = matches.shift()
// Build the formatted string
for (var i = 0; i < text.length; i++) {
  var char = text.charAt(i)
  if (pair && i == pair[0]) {
    result.push('<b>')
  }
  result.push(char)
  if (pair && i == pair[1]) {
    result.push('</b>')
    pair = matches.shift()
  }
}
console.log(result.join(''))
// h<b>ell</b>o <b>wor</b>ld
```

**Comment by janraasch** [comment]
Works great.

**Comment by krisk** [comment]
@janraasch glad to hear. I'll run through some tests, and perhaps intermittently there will be some feedback from this thread. If all goes well, we can expect version 2.2.0 before the end of the week.

**Comment by janraasch** [comment]
I'd say, we wait for 29th, then this thread will be 3 years old. :dart: :dancers: 

:wink: (I am kidding of course, I am actually really glad, that this library is still under development and even older threads like this are alive and kickin!)

**Comment by marcoala** [comment]
@krisk I like your of approach, mine was just a rude attempt to hack a solution, I just spent an hour in an unknown code.

As final user the couples [`start`,`end`] give me the opportunity to do nice things like "highlight only group of at least 3 characters" or "highlight at most 3 group of match", to avoid things like '**e**x**a**m**p**l**e** s**t**r**i**n**g**'.

**Comment by krisk** [comment]
@janraasch yes, 3 years later :smile:. Mea culpa. It took @marcoala to kickstart it, so many thanks to him!

**Comment by Abhinav1217** [comment]
Wow. Works great. so far. I did get some unwanted results.  Will post some results after I find some definite pattern.

**Comment by krisk** [comment]
@Abhinav1217 any word on the unwanted results? Thanks! :smile:

**Comment by krisk** [comment]
Also, does anyone want to volunteer to create more test cases, and adding documentation to the README? I'd be forever indebted  :sweat_smile:

**Comment by farzher** [comment]
Sometimes indicies[0] is greater than indicies[1], which messes up the loop that inserts wrapper html.

![](http://i.imgur.com/4XLo5mS.png)

Idk too many details about this, I just wanted to make you aware that this happens sometimes

**Comment by Pysis868** [comment]
Saw [krisk's sample highlighting method](https://github.com/krisk/Fuse/issues/6#issuecomment-191937490).  It was useful as a reference!  I made a slightly different one that uses substring functions instead of going by each character:
```
// Does not account for overlapping highlighted regions, if that exists at all O_o..
function generateHighlightedText(text, regions) {
  if(!regions) return text;

  var content = '', nextUnhighlightedRegionStartingIndex = 0;

  regions.forEach(function(region) {
    content += '' +
      text.substring(nextUnhighlightedRegionStartingIndex, region[0]) +
      '<span class="highlight">' +
        text.substring(region[0], region[1]) +
      '</span>' +
    '';
    nextUnhighlightedRegionStartingIndex = region[1];
  });

  content += text.substring(nextUnhighlightedRegionStartingIndex);

  return content;
};
```

Added a comment thinking it could be more complex, but not sure if anybody needs overlapping highlights yet.  Not sure how to implement it that way, but a different `matches` data structure would probably be needed, like having a sort of tree array.

**Comment by evenfrost** [comment]
Thanks for the helper @Pysis868, I took the liberty of modifying it a little bit and made a function to format the `fuse.search` output right away. It returns input objects with modified highlighted values (using TypeScript):

```ts
const highlight = (fuseSearchResult: any, highlightClassName: string = 'highlight') => {
  const set = (obj: object, value: any, path: string) => {
      const pathValue = path.split('.');
      let i;

      for (i = 0; i < pathValue.length - 1; i++) {
        obj = obj[pathValue[i]];
      }

      obj[pathValue[i]] = value;
  };

  const generateHighlightedText = (inputText: string, regions: number[] = []) => {
    let content = '';
    let nextUnhighlightedRegionStartingIndex = 0;

    regions.forEach(region => {
      const lastRegionNextIndex = region[1] + 1;

      content += [
        inputText.substring(nextUnhighlightedRegionStartingIndex, region[0]),
        `<span class="${highlightClassName}">`,
        inputText.substring(region[0], lastRegionNextIndex),
        '</span>',
      ].join('');

      nextUnhighlightedRegionStartingIndex = lastRegionNextIndex;
    });

    content += inputText.substring(nextUnhighlightedRegionStartingIndex);

    return content;
  };

  return fuseSearchResult.map(({ item, matches }: any) => {
    const highlightedItem = { ...item };

    matches.forEach((match: any) => {
      set(highlightedItem, generateHighlightedText(match.value, match.indices), match.key);
    });

    return highlightedItem;
  });
};

// usage:

const res = highlight(fuse.search(text)); // array of items with highlighted fields
```

**Comment by reverie** [comment]
Removed `_.` on line 41 and it worked great - thanks!
