### ISSUE TITLE
Latest minor relase v6.5.0 expects node >=14

### ISSUE THREAD

**Issue by sushant24** [krisk/Fuse#600]
### Describe the bug
Installing the latest version gives error of type - 
"error fuse.js@6.5.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.18.3"

Since this is a minor release we shouldn't be updating the node version requirement.

### Version
6.5.0

**Comment by krisk** [comment]
Horrid. On it.

**Comment by SergeAstapov** [comment]
@krisk thank you for quick turn around!
