### ISSUE TITLE
cdn.jsdelivr.net is serving v6.5.0

### ISSUE THREAD

**Issue by michaeljoelphillips** [krisk/Fuse#602]
Fuse v6.5.0 is being served from https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.min.js:
```
/**
 * Fuse.js v6.5.0 - Lightweight fuzzy-search (http://fusejs.io)
 *
 * Copyright (c) 2021 Kiro Risk (http://kiro.me)
 * All Rights Reserved. Apache Software License 2.0
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */
undefined
```

It looks like there was a problem with the release for this version, so it was pulled from Github, but cdn.jsdelivr.net is still serving it.  Is there any way that this can be fixed within cdn.jsdelivr.net?

**Comment by jimaek** [comment]
Best thing to do is probably release a fixed 6.5.1 and purge the CDN cache. Let me know when its done and we can purge

**Comment by krisk** [comment]
6.5.1 has been released. Though I'm still seeing `undefined'

**Comment by krisk** [comment]
Ok, I know the problem. Currently fixing it.

**Comment by krisk** [comment]
`6.5.2` has been released. The issue was due to Terser which affected minification.

**Comment by jimaek** [comment]
Everything should be good on the jsDelivr side too. Let me know if we can help with anything else
