### ISSUE TITLE
PascalCase ,snake_case or dash-case search

### ISSUE THREAD

**Issue by arnoson** [krisk/Fuse#609]
### Description
When searching for a file in vscode with the name  `MyFile`, `my_file` or `my-file` it will match the names with this pattern: `mf` (using the first character of each word of the file name). Would be great to have this feature in fuse too. 

### Describe the solution you'd like
On option to toggle this search behavior.

**Comment by krisk** [comment]
This is tokenization that varies by domain — camelCase, snake_case, kebab-case, PascalCase all have different splitting rules. A `getFn` handles it cleanly:

```js
const fuse = new Fuse(files, {
  keys: [{
    name: 'filename',
    getFn: (item) => {
      const name = item.filename
      const parts = name.split(/(?=[A-Z])|[-_]/)
      const initials = parts.map(s => s[0]).join('')
      return [name, initials] // "MyFile" searchable as "myfile" or "mf"
    }
  }]
})
```

This gives you full control over how tokens are generated without Fuse needing to know about case conventions.
