### ISSUE TITLE
Demo filter doesn't work properly

### ISSUE THREAD

**Issue by smutnyleszek** [krisk/Fuse#61]
I tried using [demo example](http://kiro.me/exp/fuse.html) filtering with **"omw"** string on simplified original data with default options. I get completely wrong results.

Data:

```
[
   { title: "Old Man's War" },
   { title: "The Lock Artist" },
   { title: "HTML5" },
   { title: "Right Ho Jeeves" },
   { title: "Incompetence" }
]
```

Options:

```
var options = {
  caseSensitive: false,
  includeScore: false,
  shouldSort: true,
  threshold: 0.6,
  location: 0,
  distance: 100,
  maxPatternLength: 32,
  keys: ["title","author.firstName"]
};
var fuse = new Fuse(list, options); // "list" is the item array
var result = fuse.search("omw");
```

I would expect to get "Old Man's War" item, but got this one instead:

```
[
  {
    "title": "Incompetence"
  }
]
```

**Comment by jeancroy** [comment]
Basically this library does not have a built in notion of word or acronym.
What it does is matching string against string

````
Incompetence
   ||:
---omw------
````
9 insertion, 1 p<>w substitution, edit distance 10.

````
Old Man's War
|   |     |
o---m-----w--
````
10 insertion

Then incompetence is of length 12, and old man 13.

**Comment by smutnyleszek** [comment]
Oh, I thought that it compares letters from the "search string". I understand that I would have to type "o m w" to match the spaces.

So is there an option to ignore spaces?

**Comment by krisk** [comment]
Hi @smutnyleszek -currently there's no option for that. To be honest, I am unsure as to its usefulness. Searching by a group of initials to match a group of words does not seem to really fall under approximate **string** matching :)
