### ISSUE TITLE
Scoring incorrect when multi word tokens given in different keys

### ISSUE THREAD

**Issue by prajavk** [krisk/Fuse#610]
Describe the bug
The scoring logic is not working when using extended search. When multiple words with spaces are given as keys, returning results with shorter string scores are higher.

Version
v6.4.6

1. I saw an open issue https://github.com/krisk/Fuse/issues/235   is this fixed in fusejs 6.4.6?   
2. Here I created Js fiddle to reproduce issue with multi words tokens given from different keys. scoring is in correct or results is empty.  
https://jsfiddle.net/prajavk/n79upa8w/22/
3. Please suggest work around if any for this fiddle

Issue: 
fusejs search results order was same when we gave multiple tokens from different keys { title: "drain refill ", tags: ["oil", "flush"] }
For example, "drain oil" will not work when I add token of tags[]. This way, searches as either "drain refill" or "refill drain", would return the expected match.

**Comment by renanvalentin** [comment]
I've recently stumble across a similar issue related to word spacing. Word-spacing gets tokenized as 
```
{
 '  ': /*..*/
}
```

But it fails in case receive `\s` instead of `' '`. My workaround was to replace `\s` by `' '` and it did the trick:

`
w.title.replace(/\s/g, ' ')
`

**Comment by prajavk** [comment]
Team, 
where can we apply this wild card setting in fuseJs.
`w.title.replace(/\s/g, ' ')`
If I have these results to filter using keywords as below
 `const list = [
  {
    "title": "replace engine oil",
    "tags": [ "exchange", "R&R", "rpl", "change"]
  },
  {
    "title": "cabin air filter & engine air filter",
    "tags": ["dust", "pollen", "air"]
  },
  {
    "title": "Headlamp / Daytime Running Light Bulb",
    "tags": [ "lamp","light","headlight","rpl", "R&R"]    
  }
];` 
For eg:  search keywords as 
// drain r&r
// headlamp dust
// headlamp R&R
let pattern = "cabin & engine  r&r";
fuse.search(pattern);

**Comment by Telematica** [comment]
> Team, where can we apply this wild card setting in fuseJs. `w.title.replace(/\s/g, ' ')` If I have these results to filter using keywords as below `const list = [ { "title": "replace engine oil", "tags": [ "exchange", "R&R", "rpl", "change"] }, { "title": "cabin air filter & engine air filter", "tags": ["dust", "pollen", "air"] }, { "title": "Headlamp / Daytime Running Light Bulb", "tags": [ "lamp","light","headlight","rpl", "R&R"] } ];` For eg: search keywords as // drain r&r // headlamp dust // headlamp R&R let pattern = "cabin & engine r&r"; fuse.search(pattern);

https://jsfiddle.net/gorn3ks7/

`let pattern = "cabin r&r	rpl";
let r = pattern.replace(/\s/g, '|');
document.getElementById("code").innerHTML = JSON.stringify(fuse.search(r), null, 2);`
