### ISSUE TITLE
Question: Largest dataset tested?

### ISSUE THREAD

**Issue by onassar** [krisk/Fuse#612]
Hey there :)
Thanks for the gr8 library.

I'm using Fuse on a lil project where there will reasonably be about 400 - 800 objects that are being searched through. However, I'm wondering what the largest dataset that has tested has been.

I'm thinking about making a few changes to my usage, which would result in 5k+ objects being searched, but I'm not sure if Fuse would be the right fit for this.

Would love to read a bit about the test cases that have been run through Fuse, as far as performance goes.

Thanks!

**Comment by jmargail** [comment]
Hi,
I just tested with 9k items (with 3 fields, searching in 2) and it's a bit laggy.
Maybe I reach the "maximum" capacity for such search on client side... or use a bad implementation or have side effects.
First attempt with 800 items was just magic ;)
