### ISSUE TITLE
The extended search operator = (exact match) is not working, every time I use it I get no results. 

### ISSUE THREAD

**Issue by jmdiazlr** [krisk/Fuse#633]
### Describe the bug
The exact match operator of extended search is not working, every time I use it I get no results. 

### Version
Latest to date.

### Is this a regression?
Do not know.

### 🔬Minimal Reproduction
In any index, use a search expression including a exact match request like:

       fuse.search("=term1  term2 term3");
You won't get results but if you take out the equal sign , voyla, there are results including term1 and other terms.

### Additional context

I followed the code, a thing the problem is in ExactMath.js, it compares item's full text === search term, but it should compare every token in item's text against search_term...   

I do not know how to regenerate (compile) the project to test my previous finding. 

In the mean time, I instructed my users to use the contains operator ('term), it works well.

**Comment by krisk** [comment]
Apologies for the very long delay on this one. The `=` operator is working as designed — it matches when the entire field value equals the search term exactly. For matching a term anywhere within the text, the include operator `'term` is the right choice, which it sounds like you already found. The [extended search docs](https://github.com/krisk/Fuse/blob/main/docs/extended-search.md) have the full list of operators.
