### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by Kayxue** [krisk/Fuse#639]
### Describe the bug
When I import the module, it said "Module not found https://deno.land/x/fuse@v6.4.1/src/core/register"

### Version
For deno, V6.4.1

### Is this a regression?
I don't know

### 🔬Minimal Reproduction
just create mod.ts & import the module with import fuse from "https://deno.land/x/fuse@v6.4.1/src/entry.js"

### Additional context
Deno Version: 1.17.3

**Comment by binyamin** [comment]
@krisk this is because the deno module is still on v6.4.1, for some reason. Maybe the publishing process changed. According to [the Deno website](https://deno.land/add_module), you just need to add webhooks.
