### ISSUE TITLE
Weighted queries

### ISSUE THREAD

**Issue by polx** [krisk/Fuse#643]
### Description

We would like to query in different manners with different weights.

### Describe the solution you'd like

Our goal is, today, for auto-completion: we wish to take a query for "math" and that it queries, in any of the index-defined fields:
- exact word math
- words that start with math (e.g. mathematics) (but with less score)
- words that include math (e.g. polymath) (but with less score)
- words that match math fuzzily (e.g. matrix) (with even less score)

In Lucene parlance, this called a query-weight and is written with a hat.
We think there might be other use cases.

### Describe alternatives you've considered

We think that it might be possible to try to merge several search results where each sub-query is done independently (but will it be comparable?).

**Comment by springuper** [comment]
There is an option [`sortFn`](https://fusejs.io/api/options.html#sortfn) which might be useful for your case.

You could re-compute the score according to your own standard and then sort the results, here is how we use it:

```js
const sortFn = (a, b) => {
  const getScore = (matches) => {
    return matches.reduce((acc, match) => {
      const score = (match.key.weight || 1) * match.norm * (1 - Math.max(match.score, Number.EPSILON));
      acc += score;
      return acc;
    }, 1);
  };
  return getScore(b.matches) - getScore(a.matches);
};
```

**Comment by krisk** [comment]
Extended search already supports this via OR groups — the first matching group wins:

```js
fuse.search("=math | ^math | 'math | math")
```

This finds exact matches, then prefix, then include, then fuzzy. However, exact/prefix/include all return score 0 when they match, so there's no score differentiation between them.

Adding per-strategy weight multipliers would change scoring behavior for all users. The boost factors are also inherently app-specific — an autocomplete widget wants different ranking than a document search.

If you need fine-grained control, run separate searches and merge:

```js
const exact = fuse.search("=math").map(r => ({ ...r, score: 0 }))
const prefix = fuse.search("^math").map(r => ({ ...r, score: 0.25 }))
const include = fuse.search("'math").map(r => ({ ...r, score: 0.5 }))
const fuzzy = fuse.search("math")
// Dedupe and sort by score
```

This gives you full control over the boost factors.
