### ISSUE TITLE
How does it search and rank multiple terms in multiple fields

### ISSUE THREAD

**Issue by MichaelRoger** [krisk/Fuse#644]
hi,

i have got the following configuration:

`{
            includeScore: true,
            includeMatches: true,
            minMatchCharLength: 3,
            findAllMatches: true,
            keys: [
                'persondata.basic.givenNameReal',
                'persondata.basic.surnameReal',
               'persondata.basic.mainTasks'
            ]

        }`

lets say i have got an document with the following data:

`{persondata:
                {basic:
                          {
                       givenNameReal:'Michael',
                       surnameReal:'Mustermann',
                       mainTasks : 'handarbeiter'
                        }
                  }
} `

let's search for 'michael musermann' and it just finds a match in the column 'persondata.basic.givenNameReal' 

:-(

shouldn't be a finding in multiple columns been ranked up?

**Comment by krisk** [comment]
If a single record contains a match in multiple keys, currently only the best score is used. For better or worse, the score is not a compound function of multiple matches. 

I wavered with this in the past, whether compound scoring should be the default behavior or not. Curious to get people's thoughts on this.

**Comment by MichaelRoger** [comment]
i would definitly say it has to be compound. because i search the best matching entry and therefor it should find the most interessting match (also in multiple columns)
