### ISSUE TITLE
Limit search results

### ISSUE THREAD

**Issue by sean-au** [krisk/Fuse#645]
### Description
the only way to limit search results, is to slice the returned results and limit the length of the slice e.g. results.slice(0,5)

### Describe the solution you'd like
create a config parameter for fuse.js so that fuse will stop searching when the desired number of results is reached, speeding the search (rather than throwing away results)

### Describe alternatives you've considered
I am currently using results.slice(0,5) which is not very efficient.

Thanks for all your hard work!

**Comment by krisk** [comment]
Not sure I agree with this. How can you be certain the search result is the best if it didn't search through all records? It would first have to search everything, then sort them, and then return the list of results. Slicing or limiting at search time would produce an incorrect result.

**Comment by springuper** [comment]
In case you missed it, there is a second parameter in `search` method where you could specify how many results you'd like to get: `search(query, { length: 10 })`.

Another thought is, if you don't need to sort the results, it means you don't care how much the documents match the query, in this scenario, probably Fuse could stop searching once it gets enough results.
