### ISSUE TITLE
Issue with IDs of zero

### ISSUE THREAD

**Issue by sconstantinides** [krisk/Fuse#65]
Thanks for the awesome plugin.

When using a numerical ID, values of 0 are returned as undefined. For example, if the result array should be [0, 10, 20] it is returned as [undefined, 10, 20].

**Comment by kylehalleman** [comment]
I think I know what's causing this and could do a pull request to fix it, but just to clarify: you're setting the `id` option to `0`? 
<img width="892" alt="screen shot 2016-01-19 at 7 22 29 pm" src="https://cloud.githubusercontent.com/assets/5906056/12437262/0627b918-bee2-11e5-82a2-ebd7415ca26e.png">

**Comment by sconstantinides** [comment]
I don't think so... I'm setting the id option to a string, in this case 'Row number'. The problem is that when 'Row number' is 0, the result array doesn't include it.
