### ISSUE TITLE
[Typescript] fieldNormWeight is non-optional

### ISSUE THREAD

**Issue by kejistan** [krisk/Fuse#650]
### Describe the bug
`IFuseOptions.fieldNormWeight` is required, but [the documentation](https://fusejs.io/api/options.html#fieldnormweight) suggests it should be optional.

### Version
6.6.0

### Is this a regression?
5.5.3 didn't include this option in the type

### Additional context
https://github.com/krisk/Fuse/blob/3fe88cf26cd313d65085066f618127465913674e/src/index.d.ts#L255

**Comment by krisk** [comment]
Fixed in v6.6.1
