### ISSUE TITLE
Variable conflict when using optional includes

### ISSUE THREAD

**Issue by eponym** [krisk/Fuse#66]
There is a conflict with the variable i in getItem().

It's using i to loop through the include array.

`for(var i = 0; i < options.include.length; i++)`

However this conflicts with the i in getItem(), so when the loop sets the property:

`rawResults[i][includeVal]`

It will reference the wrong array element and also cause an error if the include length is longer than the raw results.

**Comment by krisk** [comment]
Fixed by #67
