### ISSUE TITLE
Return all results if not search query is passed

### ISSUE THREAD

**Issue by mrleblanc101** [krisk/Fuse#664]
### Description
I used Fuse.js in a Vue application.
I wish to display all results if no search params is passed.
I can't loop on the original data since the format is not exactly the same so it would complexify my code quite a bit.

### Describe the solution you'd like
Add an option to return all results when no search query is provided

### Describe alternatives you've considered
Loop on my original object and use if/else to handle the different structure.

**Comment by springuper** [comment]
You could make it with Fuse's APIs, like this:


```js
const fuse = new Fuse(...);

const searchWrapper = query => {
  if (!query) return fuse.getIndex().records.map(({ $: item, i: idx }) => ({ idx, item }));
  return fuse.search(query);
};
```

**Comment by jaitaiwan** [comment]
Just came across this exact issue and wanted to note a couple of things about the second reply just in case someone goes to use it. 

`fuse.getIndex()` doesn't have a `records` property in the type definition (so it will error if using typescript).
`$` doesn't actually contain an item from the collection so that won't work as a solution.

**Comment by jaitaiwan** [comment]
We’re still affected by this, but haven’t had the time to do a PR

**Comment by jaitaiwan** [comment]
I'm not sure why the bot closed this? I commented afterwards to stop it from getting closed.

**Comment by mboudreau** [comment]
Yep, agreed.  It seems like a very obvious oversight, considering that I have a custom sort function.  It simply doesn't make sense to repeat it twice.

Just have all the results come in with a score of one if nothing is specified, or if an empty string is passed.

**Comment by krisk** [comment]
Hey folks, sorry this got auto-closed by the stale bot without a clear answer. The feature actually did land: as of v7.3.0, passing an empty or whitespace-only string to `fuse.search('')` returns all docs in their original order. So the workaround in the original comment isn't needed anymore.

One caveat worth flagging: the empty-query path returns `{ item, refIndex }` without a `score`, and skips `sortFn`. If you're using a custom sort or `includeScore: true` and want shape parity with non-empty queries, that's a separate gap. Happy to track it as a follow-up if anyone hits it in practice, just open a new issue.

Thanks for the patience.
