### ISSUE TITLE
reported scores are all 0 (same as first result)

### ISSUE THREAD

**Issue by johnwillyn** [krisk/Fuse#67]
There is a bug that I think I have chased down to the getItem function where it is returning the value from the options.include array for the *first* result item.  I noticed this with an include: ["score"] case I was using, but I suspect it would impact other values in this array as well.

Essentially, the bug is that the for loop uses a local variable i, but this is also the name of the argument to the getItem() function.  In Chrome, this results in referencing the i variable in the for loop, which is 0 in my case, so it is returning the score from rawResult[0] instead of the one desired.

I changed for loop to use j and it fixed this issue for me:

```javascript
var getItem = function(i) {
      var resultItem;

      if(options.include.length > 0) // If `include` has values, put the item under result.item
      {
        resultItem = {
          item: rawResults[i].item,
        };

        // Then include the includes
        for(var j = 0; j < options.include.length; j++)
        {
          var includeVal = options.include[j];
          resultItem[includeVal] = rawResults[i][includeVal];
        }
      }
      else
      {
        resultItem = rawResults[i].item;
      }

      return resultItem;
    };

```

I hope this helps.  I would be happy to submit a pull request if desired.

John

**Comment by nathanmarks** [comment]
@johnwillyn can you submit a pull request -- that way I can atleast use your version :)

**Comment by johnwillyn** [comment]
Done.

**Comment by nathanmarks** [comment]
@johnwillyn Thanks, hopefully it gets merged soon

**Comment by krisk** [comment]
Thanks @johnwillyn
