### ISSUE TITLE
Return removed item when calling `removeAt`

### ISSUE THREAD

**Issue by GMartigny** [krisk/Fuse#675]
### Description
When calling `remove`, Fuse.js returns all removed items. This is not the case with `removeAt` and I found it confusing.

### Describe the solution you'd like
Saving the [result of the `splice` method](https://github.com/krisk/Fuse/blob/master/src/core/index.js#L69) and returning it to the user would be great.

### Describe alternatives you've considered
I can look at the `docs` in the fuse instance before calling `removeAt`.

**Comment by krisk** [comment]
Fixed in 8cec7e2f. `removeAt(idx)` now returns the removed item, consistent with `remove()`.
