### ISSUE TITLE
Searching text in a subtitle file

### ISSUE THREAD

**Issue by uriva** [krisk/Fuse#695]
I want to search for a quote, which is potentially multiple sentences, on a large string and get back the locations in the string.

I can just break it down into sentences because often my query will be across sentences.

I'm not knowledgeable about the underlying algorithm, is it hard to make it work for such a use case?

Thanks!

**Comment by krisk** [comment]
This is a usage question rather than a feature request. To search subtitle files, parse the `.srt` into an array of objects and pass it to Fuse:

```js
const subs = parseSrt(fileContents) // [{text: '...', start: 0, end: 5}, ...]
const fuse = new Fuse(subs, { keys: ['text'] })
fuse.search('hello')
```

The parsing step is outside Fuse's scope.
