### ISSUE TITLE
Add an option with dictionary of synonyms

### ISSUE THREAD

**Issue by mirorac** [krisk/Fuse#698]
### Description
Synonyms are words that are considered equal to its associated word for the purposes of calculating search results.

### Describe the solution you'd like
Add `synonyms` option object that can contain words and their respective synonyms.

```javascript
const list = ["Old Man's War", "The Lock Artist"]
const options = {
  synonyms: {
    artist: ['composer', 'maestro']
  }
}
const fuse = new Fuse(list, options)

fuse.search('composer') // result: ['The Lock Artist']
fuse.search('cmposer') // result: ['The Lock Artist']
fuse.search('maestro') // result: ['The Lock Artist']
fuse.search('artist') // result: ['The Lock Artist']
```

### Describe alternatives you've considered
Add an array of synonyms to each item in the list. However, this way neglects the token location, context, etc...
```javascript
const list = [
  {
    string: "Old Man's War",
    synonyms: [],
  },
  {
    string: "The Lock Artist",
    synonyms: ['composer', 'maestro']
  }
]
```

**Comment by ShahriarKh** [comment]
This will be a great feature, especially for multi-language contexts. I think, it will be better if the "synonyms" is added as a search option, and not directly on data; for cases when the data is loaded from a remote source.

**Comment by krisk** [comment]
This is outside Fuse's scope — synonym expansion is a data preprocessing concern that varies by domain. I'd recommend expanding synonyms before indexing or before querying:

```js
// Expand at query time
const synonyms = { car: ['automobile', 'vehicle'] }
const terms = expandSynonyms(query, synonyms)
const results = fuse.search({ \$or: terms.map(t => ({ field: t })) })
```

Every domain has different synonym needs, so this is better handled in userland.
