### ISSUE TITLE
Feature request: Only begin search after typing N characters

### ISSUE THREAD

**Issue by annapowellsmith** [krisk/Fuse#70]
Thanks for an amazing plugin. It is so simple to use and works so well. 

I have a feature request. Would it be possible to add an option to specify that the search should only begin after the user has entered N characters?

I find that with longer lists, beginning the search after typing one character can result in a very long results list. This can be slow to render in the browser, especially on mobile.

**Comment by ptz0n** [comment]
I don't see why this should be an option in the lib. Simply check the length of your pattern before executing a search.

**Comment by krisk** [comment]
Agree with @ptz0n.
