### ISSUE TITLE
Fuse Bundle size issue

### ISSUE THREAD

**Issue by prophet1996** [krisk/Fuse#713]
### Describe the bug
 A clear and concise description of what the bug is.
if you visit https://bundlephobia.com/package/fuse@0.4.0 the 
### Version
 The Fuse.js version where this bug is happening.
0.4.0
### Is this a regression?
no
### 🔬Minimal Reproduction
go to https://bundlephobia.com/package/fuse@0.4.0
### Additional context

JShint is taking 30% of the bundle size and underscore is also over represented.

**Comment by Svish** [comment]
The linked version [0.4.0](https://bundlephobia.com/package/fuse@0.4.0) was 119.1kB/39.4kB, but the current version [6.6.2](https://bundlephobia.com/package/fuse.js@6.6.2) is only 15.4kB/5.1kB, with no dependencies.

I suppose this issue could be closed now?
