### ISSUE TITLE
Exact matching not working

### ISSUE THREAD

**Issue by rachelrj** [krisk/Fuse#717]
I am using the following for options and my matches are not exact.
Is there something I'm doing wrong?

`const options = {
  keys: fieldsToCheck,
  includeMatches: true,
  threshold: 0.0,
  ignoreLocation: true,
  minMatchCharLength: 3,
};`

**Comment by rachelrj** [comment]
Hello, does anyone know whether this is currently a bug with Fuse or whether this is an implementation issue?

**Comment by MathieuMz** [comment]
Same issue here, but it caused by scoring. I never reach the perfect match with a 0 score.
My "best" score is 8.569061098350962e-12

**Comment by erquhart** [comment]
For anyone watching and still experiencing this issue, please thumb up #756.
