### ISSUE TITLE
Add option to ignore diacritics

### ISSUE THREAD

**Issue by mgrabovsky** [krisk/Fuse#723]
### Description

I'd find it extremely useful if Fuse had the ability to ignore diacritics/accents both in the search string and in the indexed content. However, I don't want to lose the diacritics completely, i.e. I want the diacritics to appear in the search results for the matched items.

Based on the comments in a previous issue (#415), I have implemented a quick prototype (see below), but it falls short of being usable: the getter strips the diacritics and it's impossible to recover them from the results. (See below for an illustration.)

### Describe the solution you'd like

Have a configuration option like `ignoreAccents: boolean`, disabled by default, that would toggle this functionality.

### Describe alternatives you've considered

I have read through #415 and [implemented a prototype](https://github.com/faktaoklimatu/web-core/issues/172#issuecomment-1165540250) in our app, but it has the problem of losing the diacritics. The implementation basically boils down to stripping diacritics from the search string and a custom getter which does the same to the content:

```js
// Code by Mathieu TUDISCO via GitHub:
// https://github.com/krisk/Fuse/issues/415#issuecomment-634348136
const stripAccents = String.prototype.normalize
    ? ((str) => str.normalize('NFD').replace(/[\u0300-\u036F]/g, ''))
    : ((str) => str);

const options = {
    // ...
    getFn: (obj, path) => stripAccents(Fuse.config.getFn(obj, path)),
    includeMatches: true,
    // ...
};

const fuse = new Fuse(data, options);
const searchResults = fuse.search(stripAccents(this.searchString));
```

To illustrate the problem, see the screenshot below. The title of the first two items should be _“Lesnatost v přírodních lesních oblastech”_ and _“Proč dnes příroda tak rychle přichází o svou rozmanitost?”_, respectively, but the diacritics are stripped by the getter and they cannot be recovered.

![](https://user-images.githubusercontent.com/134321/175538713-4446a158-5501-43fc-9f83-2818e4006778.png)

**Comment by mgrabovsky** [comment]
Is this a feature that would be welcome by the maintainers but there's not enough capacity to implement it? If so, I would be happy to take a look and try to submit a patch myself.

**Comment by mgrabovsky** [comment]
This still appears to be a problem and I'm still open to collaboration.

**Comment by boydkelly** [comment]
Would love to see this option...
