### ISSUE TITLE
Extended search not working with AND at all

### ISSUE THREAD

**Issue by marceloverdijk** [krisk/Fuse#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

This is similar as https://github.com/krisk/Fuse/issues/633 but which was closed.

With example from https://www.fusejs.io/demo.html and extended search enabled,
searching `^old scal` gives no results although I would have expected that Old Man's War from John Scalzi would have been returned.

Changing to `^old | scal` does give the result.

Also just `old scal` does not give any results, but with `old | scal` it does.

When disabling `useExtendedSearch = false` then `old scal` gives the result.

It seems when `useExtendedSearch = true` is set an AND search is not working at all (compared to OR search with `|` is working).

### The Fuse.js version where this bug is happening.

6.6.2

### Is this a regression?

- [ ] This is a regression bug

### Which version did this behavior use to work in?

None

### Steps To Reproduce

See description.

### Expected behavior

AND to work with extend search enabled.

**Comment by marceloverdijk** [comment]
Note that this works as well:

```
fuse.search({
  $and: [
    { 'seasons.year': '^old' }, 
    { name: 'scal' }, 
  ]
})
```

but `fuse.search('^old scal')` does not.

The spaces seem not to be parsed correctly.

**Comment by krisk** [comment]
Unable to reproduce on v7.2.0 — space-separated AND terms in extended search work correctly in our testing. If you're still seeing this on the latest version, please reopen with a minimal reproduction.
