### ISSUE TITLE
Release 7.0.0 ? 

### ISSUE THREAD

**Issue by tmaihoff** [krisk/Fuse#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

[Here on npmjs](https://www.npmjs.com/package/fuse.js/v/7.0.0 ) it says version 7.0.0 was released 7 days ago.

However the [Github release page](https://github.com/krisk/Fuse/releases) still shows 6.6.2 from 2022 as the latest release. 

Which is correct? Where can I find a changelog for version 7.0.0? Are there breaking changes which require migrating? 

Looking forward to hearing from you.

**Comment by Nercus** [comment]
Hey there,
had the exact same question and found the changes in the current changelog markdown file :)
https://github.com/krisk/Fuse/blob/main/CHANGELOG.md

**Comment by PhiLhoSoft** [comment]
For information, we use Fuse with TypeScript.
In v. 6, we were doing:
```
import Fuse from 'fuse.js';

private options: Fuse.IFuseOptions<T>;
const filterResults: ReadonlyArray<Fuse.FuseResult<T>> = this.search();
const filterResultsMap: Map<T['id'], readonly Fuse.FuseResultMatch[]> = new Map();
```
(For example…)

In v. 7, we must do:
```
import Fuse, { FuseResult, FuseResultMatch, IFuseOptions } from 'fuse.js';

private options: IFuseOptions<T>;
const filterResults: ReadonlyArray<FuseResult<T>> = this.search();
const filterResultsMap: Map<T['id'], readonly FuseResultMatch[]> = new Map();
```
