### ISSUE TITLE
Usage in deno

### ISSUE THREAD

**Issue by sandrodw3** [krisk/Fuse#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

Hi! I'm trying to use this in a deno app but I'm not being able right now. 

I saw [this](https://www.fusejs.io/getting-started/installation.html#deno) in the official doc, but it's not working for me. It seems the 7.0.0 is still not available in https://deno.land/x, is that right?

I also tried with latest https://deno.land/x version, that seems to be @6.4.1, but I tried to import `Fuse` in some different ways and couldn't get it to work. Could someone help? Thanks! 😄

**Comment by brc-dd** [comment]
As a workaround, one can use esm.sh:

```ts
import Fuse from 'https://esm.sh/fuse.js@7.0.0'
```
