### ISSUE TITLE
Returned indexes are incorrect

### ISSUE THREAD

**Issue by dafi** [krisk/Fuse#761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I search using `includeMatches` option and when the pattern contains round brackets `(` or `)` the returned indexes are incorrect

### The Fuse.js version where this bug is happening.

7.0.0

### Is this a regression?

- [ ] This is a regression bug

### Which version did this behavior use to work in?

7.0.0

### Steps To Reproduce

I created a complete example to reproduce the issue at https://stackblitz.com/edit/vitejs-vite-ml32lm?file=main.js

As you can see in the first case the returned indexes are identical

Index 0 **start 0 end 25**

Index 1 **start 0 end 25**

In second case the index at 1 differs from start only by 1, this create incorrect results when I highlight in HTML

Index 0 **start 0** end 23

Index 1 **start 1** end 23

### Expected behavior

I expect no duplicated indexes and start at index >= 1 always greater than previous end valuey

**Comment by krisk** [comment]
Unable to reproduce on v7.2.0. Patterns with parentheses return correct indices in our testing. If you're still seeing this on the latest version, please reopen with a minimal reproduction.
