### ISSUE TITLE
minMatchCharLength not working as expected

### ISSUE THREAD

**Issue by DesmondHsu** [krisk/Fuse#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When looking for a x-character item, result is not actually limit result at minMatchCharLength.

Version replicable: 7.0.0

### The Fuse.js version where this bug is happening.

Other (please specify in description)

### Is this a regression?

- [ ] This is a regression bug

### Which version did this behavior use to work in?

None

### Steps To Reproduce

using [Live demo](https://www.fusejs.io/demo.html)

list.json
```
[
  "Taylor Swift", "or something rather"
]
```

Input: 
```
taylor swft
```

With config being:
```
const fuseOptions = {
	minMatchCharLength: 12,
};
```

### Expected behavior

It is expected "Taylor Swift" would be the result for it is 12 characters long. For such input "taylor swft" which is 11 characters long, the acceptable value for `minMatchCharLength` appears to be 9. It should rather work for 9, 10, 11, and 12.

### Screenshots

<img width="593" alt="Screenshot 2024-04-08 at 10 36 10 am" src="https://github.com/krisk/Fuse/assets/5046056/2a62da8f-01c9-4887-bd68-a1414e413286">

**Comment by krisk** [comment]
This is working as designed. `minMatchCharLength` filters by the length of the **matched character sequence** in the match indices, not the length of the result item or search pattern.

In your example, searching `"taylor swft"` against `"Taylor Swift"` produces a match span of `[0, 8]` (9 characters). With `minMatchCharLength: 12`, this 9-character span is too short, so the result is excluded. With `minMatchCharLength: 9`, it passes.

This option is primarily useful for filtering out short, low-quality matches when `includeMatches` is true — for example, ignoring single-character matches in the result set.
