### ISSUE TITLE
7.0.0 Breaking Change Documentation Unclear

### ISSUE THREAD

**Issue by jgillick** [krisk/Fuse#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

In the 7.0.0 changelog, under "BREAKING CHANGES" simply lists the item: "Extension changed". What does this mean? How do I upgrade?  Is this the module name extension? From the documentation, it looks like it's still imported as `fuse.js`.

### The Fuse.js version where this bug is happening.

Other (please specify in description)

### Is this a regression?

- [ ] This is a regression bug

### Which version did this behavior use to work in?

None

### Steps To Reproduce

1. View the [changelog](https://github.com/krisk/Fuse/blob/main/CHANGELOG.md)
2. Read the log for version 7.0.0
3. Ponder what "Extension changed" means and how a project should upgrade. 🤔

### Expected behavior

The Breaking Changes section should explain how to upgrade to this version.

**Comment by davidstackio** [comment]
This comment clarifies things a bit: https://github.com/krisk/Fuse/issues/746#issuecomment-1895603227
