### ISSUE TITLE
Having problems on node 5.6

### ISSUE THREAD

**Issue by jloveric** [krisk/Fuse#85]
Fuse seems to be giving me errors, I'm not totally sure if this is because sys is deprecated or something else.  I'm using node v5.6.0.  Here is the ouput of the command line.  I realize I'm not passing any parameters to new Fuse(), but it doesn't seem to make a difference.  Thanks for any help.

node --version
v5.6.0

node

> let Fuse = require('fuse')
> (node) sys is deprecated. Use util instead.
> undefined
> Fuse
> { fuseContent: [Function], fuseFile: [Function] }
> let a = new Fuse()
> TypeError: Fuse is not a function
>     at repl:1:31
>     at REPLServer.defaultEval (repl.js:252:27)
>     at bound (domain.js:287:14)
>     at REPLServer.runBound [as eval](domain.js:300:12)
>     at REPLServer.<anonymous> (repl.js:417:12)
>     at emitOne (events.js:95:20)
>     at REPLServer.emit (events.js:182:7)
>     at REPLServer.Interface._onLine (readline.js:211:10)
>     at REPLServer.Interface._line (readline.js:550:8)
>     at REPLServer.Interface._ttyWrite (readline.js:827:14)

**Comment by shri3k** [comment]
@jloveric you're requiring the wrong packages. It's supposed to be `fuse.js`.

**Comment by ptz0n** [comment]
Close?
