### ISSUE TITLE
`cc` should match `carbon copy` better than `catsarecool`

### ISSUE THREAD

**Issue by farzher** [krisk/Fuse#89]
When the character is matched at the start of a new word, it should get bonus points (idk how to explain this well, I think you know what I mean, (ask questions if you don't))

This is sublime:
![image](https://cloud.githubusercontent.com/assets/1005136/15731706/18a85e86-2845-11e6-8f46-447ef0bfd9b6.png)

This is fuse:
![image](https://cloud.githubusercontent.com/assets/1005136/15733811/bab99908-2857-11e6-9582-60b41b926a9d.png)

**Comment by cshoredaniel** [comment]
@farzher what you're thinking of is 'semantic' or 'natural language' search not 'fuzzy' search.

**Comment by cshoredaniel** [comment]
@farzher Ah, only saw the title in my email.  'catsarecool' (only one word as far as fuse is concerned -- it doesn't use a dictionary to identify substrings, nor should it) wouldn't match higher if one emphasized the first letter after a space anyway.
