### ISSUE TITLE
not all keys are used when calculating the final average scores

### ISSUE THREAD

**Issue by Gtoffo** [krisk/Fuse#90]
**A query is being performed on three keys and returns the following results:**

record A:
key1 score: no match so not shown in results
key2 score :0.61
key3 score: no match so not shown in results
Average score: 0.61

record B:
key1 score: 0.5
key2 score :0.95
key3 score: 0.59
Average score: 0.69

_Record A will be incorrectly selected as the best result._

**The correct behaviour should be:**

record A:
key1 score: no match = 1
key2 score :0.61
key3 score: no match = 1
Average score: 0.87

record B:
key1 score: 0.5
key2 score :0.95
key3 score: 0.59
Average score: 0.69

_Record B is the best result._

**How to fix:**
A fork by @planeguy already exists with a possible fix to this problem. I'm not sure if it causes additional issues though. It should probably be included in the main branch.
https://github.com/planeguy/Fuse/commit/bf43629c30112710845734612fe5e3a33aae563b

EDIT: @planeguy's fix doesn't seem to work...

**Comment by Gtoffo** [comment]
We are currently testing a fix to this issue.

This is how we did it: https://github.com/buildo/Fuse/commit/71a99a2a83e237637b95cc634ff475878efd9167

**Comment by krisk** [comment]
Can you submit a PR, along with tests? Even with those commits, I'm not seeing any difference in the results. Thanks!

**Comment by planeguy** [comment]
Nah don't use my fork. I haven't pushed my final changes + I haven't tests + my solution breaks weighting keys so it's totally just for internal use. I'll push it eventually just do people can look at it, just busy right now.

**Comment by Gtoffo** [comment]
We are seeing results with our fix. This is the logic behind it:

record A:
key1 score: no match
key2 score: 0.6
key3 score: no match
NumMatchedKeys: 1
Average score: 0.6+(MaxMatchedKeys- NumMatchedKeys) / MaxMatchedKeys=(0.6+1)/2= 0.8

record B:
key1 score: 0.3
key2 score: 0.95
key3 score: no match
NumMatchedKeys: 2
Average score: (0.2+0.96)+(MaxMatchedKeys- NumMatchedKeys) / MaxMatchedKeys = (1.25+0)/2= 0,625

Record B will be the best result.

With the previous method of just taking into account the matched keys and averaging them record A would have incorrectly won. This method takes into account while calculating scores that other results may have matched a bigger number of keys and therefore takes into account records with lower key matches (by adding 1=no match for the unmatched keys)

I'll post a PR as soon as I can.

We **haven't touched weighted searches** but I believe there may be bigger issues there.
