### ISSUE TITLE
Weighted search not working?

### ISSUE THREAD

**Issue by rohmann** [krisk/Fuse#92]
For example, if I pass `keys` like this:

```
keys: [{ name: 'title', weight: 0.3 }, { name: 'parent', weight: 0.6 }, { name: 'grandparent', weight: 0.9 }]
```

I get this error:
```
fuse.js:238 Uncaught TypeError: path.indexOf is not a function
```

It looks like `path` is receiving a full object instead of a string.
<img width="918" alt="screenshot 2016-06-20 13 29 28" src="https://cloud.githubusercontent.com/assets/1506848/16204063/1acda608-36eb-11e6-98f7-ac57ea17a9c3.png">

**Comment by krisk** [comment]
Which version of Fuse are you using? I'm unable to replicate this with the current version 😄

**Comment by rohmann** [comment]
I'm so sorry. I hadn't updated my dependancies. Works great with the latest.

**Comment by marshallford** [comment]
I am getting the same error on version 3.2.0.

**Comment by Sigmus** [comment]
Can you provide an example script so we can reproduce the error?

**Comment by marshallford** [comment]
While putting together a snippet I discovered the issue. When **only** providing a list of keys and one of the elements in the array is a function, fuse will not throw an error. When providing keys and weights however fuse will throw an error if one of the keys is a function.
