### ISSUE TITLE
Fuse install, working project compile fails relating to 'fs'

### ISSUE THREAD

**Issue by fairbairn** [krisk/Fuse#94]
If I install fuse (`npm i -S fuse) and recompile a working webpack project (prior to using Fuse), I get the following compile errors.

```
WARNING in ./~/colors/lib/colors.js
Critical dependencies:
138:29-43 the request of a dependency is an expression
 @ ./~/colors/lib/colors.js 138:29-43

WARNING in ./~/colors/lib/extendStringPrototype.js
Critical dependencies:
101:31-45 the request of a dependency is an expression
 @ ./~/colors/lib/extendStringPrototype.js 101:31-45

ERROR in ./~/fuse/lib/fuse.js
Module not found: Error: Cannot resolve module 'fs' in ./node_modules/fuse/lib
 @ ./~/fuse/lib/fuse.js 6:9-22

ERROR in ./~/uglify-js/tools/node.js
Module not found: Error: Cannot resolve module 'fs' in ./node_modules/uglify-js/tools
 @ ./~/uglify-js/tools/node.js 8:9-22
```

Also, there's no `src` folder in the fuse install.  I suspect if I could alias directly into the src folder I could bypass the issue (but not certain).

I have to remove fuse from my package.json and rm -fr node_modules/fuse in order to get it to compile correctly again.

node --version => v6.2.2

Any suggestions on how to integrate into a working project without the 'fs' conflict?

**Comment by fairbairn** [comment]
Certainly not an elegant solution for packaging and future updates, but if I pull from git and just include the src/fuse.js file in my project, it does compile, so at least there appears to be a simple workaround.

**Comment by patrik-piskay** [comment]
I think you made the same mistake I just did and installed package `fuse` instead of `fuse.js` :)

**Comment by fairbairn** [comment]
I think you might be right!  Could have sworn I checked the package.json.  Thanks.

**Comment by krisk** [comment]
I guess this is resolved then 😅 ?

**Comment by fairbairn** [comment]
Yes!

**Comment by mat2maa** [comment]
Would it not make sense to have a line in the README:

> To install with NPM, do the following:
> `npm install --save fuse.js`

Rather than having to follow the existing link: [demo & usage](http://fusejs.io/) and scrolling some distance down the page to find it? I think one could otherwise be forgiven for leaving off the ".js"...
