### ISSUE TITLE
Option to only return results that match all tokens

### ISSUE THREAD

**Issue by keeganstreet** [krisk/Fuse#95]
For the purposes of this example you can assume I have set the fuzziness threshold to 0.

Given I have a list of items like this:

```js
var items = [
  'large red shirt',
  'large green shirt',
  'large blue shirt',
  'medium red shirt',
  'medium green shirt',
  'medium blue shirt',
  'small red shirt',
  'small green shirt',
  'small blue shirt',
  'large red trousers',
  'large green trousers',
  'large blue trousers',
  'medium red trousers',
  'medium green trousers',
  'medium blue trousers',
  'small red trousers',
  'small green trousers',
  'small blue trousers',
  'large red socks',
  'large green socks',
  'large blue socks',
  'medium red socks',
  'medium green socks',
  'medium blue socks',
  'small red socks',
  'small green socks',
  'small blue socks'
];
```

I would like a search of `large shirt` to return the 3 results that match *both* words in the input:
```js
[
  'large red shirt',
  'large green shirt',
  'large blue shirt'
]
```

A default search returns 0 results.

Enabling the`tokenize` option to search for individual words does successfully return these 3 results, however it also returns the other 12 `large` or `shirt` items. I am only interested in items that match both search tokens.

Could a `matchAllTokens` option be added to Fuse to achieve this?

https://jsbin.com/hifegi/17/edit?js,console

**Comment by krisk** [comment]
Hey @keeganstreet. 

Just a side note: when `tokenize` is `true`, the `threshold` is ignored 😅 

 > I am only interested in items that match both search tokens

Fuse is all about **string approximation**. when `tokenize` is `true`, using your example, searching for "large shirt" in  the string "medium red shirt" will (internally) do the following:

1. Search for `"large"` in `["medium", "red",  "shirt"]`:

  ```
  Pattern: large
  Token scores: [ { medium: 1 }, { red: 0.6 }, { shirt: 1 } ]
  ```
2. Search for `"shirt"` in `["medium", "red",  "shirt"]`:

  ```
  Pattern: shirt
  Token scores: [ { large: 1 }, { red: 1 }, { shirt: 0 } ]
  ```

A match is determined by a score less than 1 (where 0 = exact score, 1 = no match). Notice in the above that the score between the word "large" and "red" is 0.6. That is the reason why you see all those records in the result list: **there is a similarity match between "large" and "red".**

What you're interested in, however, would be more of an **exact match**, as opposed to string approximation, but that's not what Fuse is about 😄 

An alternative approach (perhaps more in line with the essence of the library) would be to include the score in the result, and remove from the list all records whose score is greater than some number. For example:

```javascript
var fuse = new Fuse(items, {
  include: ['score'],
  tokenize: true
})

var result = fuse.search('large shirt')
result.forEach(function (record) {
  if (record.score < 0.53) {
    console.log(items[record.item])
  }
})
```

**Comment by keeganstreet** [comment]
Hey @krisk,

Thanks for taking the time to reply (and for building the library of course!)

I do appreciate that Fuse is all about string approximation, and I am using it for this feature. In my actual implementation I have not set the `threshold` to `0`. I have just used that as an example in this ticket because I thought taking fuzziness out of the equation would make this issue clearer.

Maybe a more real-world example would better explain what I mean.

Say I have this list of companies, and I want to filter the list down based on a user entered search term:

```
AustralianSuper - Corporate Division
Aon Master Trust - Corporate Super
Promina Corporate Superannuation Fund
Workforce Superannuation Corporate
```

A search input of "Australia" will return 1 result.

And a search input of "corporate" will return all 4 results.

A search input of "Australia corporate", which in the user's mind is a more specific search term, will return all 4 results. It seems counter-intuitive for a more specific search term ("Australia corporate") to return more results than a less specific search term ("Australia").

I understand that this is useful behaviour in some use-cases, because we may want Fuse to uncover more results even if some of the tokens don't match. But in this use case, we want to reduce the number of results as more tokens are provided as input.

Here's a demo:
https://jsbin.com/zuqugudehe/1/edit?js,console


Also its not really important, but you may have been mistaken about the `threshold` parameter not having an effect when `tokenize` is `true`. On https://jsbin.com/pehixamoba/edit?js,console, this returns 15 results:

```
fuse = new Fuse(items, {
  threshold: 0,
  tokenize: true
});
result = fuse.search('large shirt');
```

And this returns 27:
```
fuse = new Fuse(items, {
  threshold: 1,
  tokenize: true
});
result = fuse.search('large shirt');
```

**Comment by SusanthCom** [comment]
@keeganstreet give a try guided by @krisk. I too like the fuse very much. 
If nothing works as per you need, Try an alternative https://github.com/bevacqua/fuzzysearch

**Comment by krisk** [comment]
@keeganstreet, your example illustrates the problem quite nicely. I do agree that when there are more matched words (somewhat irrespective of distance), it should rank higher in the result set.

I'm currently working on potential improvement to Fuse.js which would address the issue. Coding it right now. I will post updates on this thread.

And about this:

> Also it's not really important, but you may have been mistaken about the threshold parameter not having an effect when tokenize is true.

You're absolutely right. Mea culpa. I had made this change a while ago, and had forgotten about it😅

**Comment by krisk** [comment]
@keeganstreet, I created a new branch [feature/match-all-tokens](https://github.com/krisk/Fuse/tree/feature/match-all-tokens) which has this fix. You can use the option `matchAllTokens:true`, (only works if `tokenize:true`)

**Comment by keeganstreet** [comment]
Hey @krisk, awesome thanks for that!

I have tried grabbing fuse.js from the feature/match-all-tokens branch, and setting matchAllTokens to true, but it still seems to be returning results that only match one of the tokens.

Would you like me to submit a PR with some additional unit tests for the matchAllTokens option? Maybe that would help.

**Comment by krisk** [comment]
@keeganstreet yes please! Thanks!
