### ISSUE TITLE
Thoughts on a "donate" button?

### ISSUE THREAD

**Issue by krisk** [krisk/Fuse#96]
I've been thinking about adding a _donate_ button, a la PayPal, to Fuse, mainly so I can justify spending a good chunk of time doing the following:
- Create new features
- Bug fixes
- Better project page and documentation
- Tech support
- More examples
- Visually driven customization (think of wizards) for non-developers

Do you think such a button would be seen as a personal affront to the Open Source community?

**Comment by Sigmus** [comment]
I think it's perfectly moral to get paid for your work. Example: https://twitter.com/dan_abramov/status/618466568213778432

**Comment by krisk** [comment]
Took the plunge. Added the lovely button: 

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/kirorisk)

**Comment by SusanthCom** [comment]
Please do that. [This](http://vuejs.org/support-vuejs/) is a good strategy from www.vuejs.org . He is doing great too.

**Comment by krisk** [comment]
http://fusejs.io is up, with a live demo and more examples. I've added the support/donation at the bottom 😅

**Comment by jiechelle** [comment]
This is such a great tool ! I am a summer intern, and I find Fuse really
cool so I am implementing it in my current project. I sincerely like it and
once I am on the track of using it, I am thinking of asking my boss for
donation for you! great job

**Comment by SusanthCom** [comment]
Wow @krisk http://fusejs.io looks Cool ❤️
Good domain name, easy to remember. more over an exclusive site shows your dedication towards FuseJs.

Nice to see that you provided Patreon (recurring pledge) in addition to Paypal. 
Good move.
