### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by krisk** [krisk/Fuse#97]
Anyone wants to volunteer to create a logo for this library?

**Reward**: perpetual placement and visibility on a library that gets [50k+](https://www.npmjs.com/package/fuse.js) downloads/month, plus your name in the contribution list.

And if that doesn't work, then supposing the [donations](96) thing works out, I may just have to hire somebody.

**Comment by SusanthCom** [comment]
Nice to see 👀  the improvement plan
To which mail id should sent the samples ?

**Comment by krisk** [comment]
@SusanthCom pardon the late reply. You can send them to kirollos@gmail.com 😄

**Comment by SusanthCom** [comment]
@krisk Thanks.

Will send 📫  u shortly. 😄

**Comment by levimichael** [comment]
Hey Kiro,

Is this still something you need help with?

**Comment by theodorosploumis** [comment]
Me too, asking the same question ^.
