### ISSUE TITLE
Allow to use functions instead of strings for keys specification

### ISSUE THREAD

**Issue by Phyks** [krisk/Fuse#99]
Hi,

When using [`Immutable.JS`](https://facebook.github.io/immutable-js/), one has to convert back and forth between `Immutable` objects and JavaScript objects, to pass them to `Fuse`.

If we could use functions to specify which key to use, it would allow the use of non-array objects such as Immutable ones:

```javascript
var books = Immutable.fromJS([{
  title: "Old Man's War"
  author: {
    firstName: "John",
    lastName: "Scalzi"
  }
}]);

var fuse = new Fuse(books, { keys: [item -> item.title, item -> item.getIn(["author", "firstName"])] });
```

Thanks

**Comment by krisk** [comment]
@Phyks, in your example you're passing in books into the `Fuse` instance, however, the first arguments is required to be an `array`, and not an `object`. This is because it needs to be properly iterated on. I'm all for being able to use functions as key accessors, but the list must remain an `array`.

**Comment by Phyks** [comment]
Hmm, books should be an Immutable List of Immutable Map. Immutable List is indeed an object, but is the Immutable equivalent of Array I think?

**Comment by krisk** [comment]
By doing `var books = Immutable.fromJS([...])`, `books` is now not an Array:

```javascript
 Object.prototype.toString.call(books) // [object Object]
```

As a result, Fuse.js cannot iterate on that 😢 .

**Comment by Phyks** [comment]
`forEach` is implemented in `Immutable.List`, so replacing looping by functional `forEach` would make the code work for both `Array` and `Immutable.List` I think. https://facebook.github.io/immutable-js/docs/#/List/forEach

**Comment by krisk** [comment]
I'm merely saying that Fuse.js should **not** (arguably) be making that decision 😄 . 

The object being passed in should be `[object Array]`, and not an object which is Array-like. 

Also, note the following:
- `forEach` is not supported in all platforms
- `length` is not a property of `Immutable.List`. Instead, we'd have to use the `count()` function. Which, again, is "Immutable" specific.

**Comment by Phyks** [comment]
Ok. I got your point. So being able to support Immutable objects directly in Fuse would add to Immutable-specific code and it would be better to convert back to JS Arrays and pass them?

**Comment by krisk** [comment]
@Phyks, exactly 😄
